(()=>{'use strict';
const STORAGE_KEY='aioc-state';
const BACKUP_KEY='aioc-backups-v1';
const DB_VERSION=3;
const BUILD='consolidation-3.0';
const listeners=new Map();
const arrays=['gameObjects','authoringEntries','packLists','featureModules','testPlans','testSessions','testFindings','balanceBenchmarks','agents','decisions','alerts','approvals','artifacts','tasks','sessions','notes','knowledge'];
const clone=v=>JSON.parse(JSON.stringify(v));
function normalize(input={}){const s=input&&typeof input==='object'?input:{};arrays.forEach(k=>{if(!Array.isArray(s[k]))s[k]=[]});s.meta=s.meta&&typeof s.meta==='object'?s.meta:{};s.meta.databaseVersion=Number(s.meta.databaseVersion||0);s.meta.createdAt=s.meta.createdAt||new Date().toISOString();s.meta.updatedAt=s.meta.updatedAt||s.meta.createdAt;s.meta.build=s.meta.build||BUILD;s.migrationsApplied=Array.isArray(s.migrationsApplied)?s.migrationsApplied:[];return s}
function migrate(raw){let s=normalize(clone(raw||{}));const applied=[];
 if(s.meta.databaseVersion<1){s.gameObjects=s.gameObjects.length?s.gameObjects:[...s.abilities,...s.creatures,...s.species,...s.items,...s.vehicles,...s.worlds,...s.quests].filter(Boolean).map((o,i)=>({...o,id:o.id||`legacy.${o.type||'object'}.${i+1}`,name:o.name||o.title||`Legacy object ${i+1}`,legacySource:true}));s.meta.databaseVersion=1;applied.push('v1-normalize-collections')}
 if(s.meta.databaseVersion<2){s.decisions=s.decisions.map(d=>({...d,status:d.status||'open'}));s.alerts=s.alerts.map(a=>({...a,status:a.status||'open'}));s.approvals=s.approvals.map(a=>({...a,status:a.status||'pending'}));s.meta.databaseVersion=2;applied.push('v2-normalize-attention-status')}
 if(s.meta.databaseVersion<3){s.auditLog=Array.isArray(s.auditLog)?s.auditLog:[];s.schemaRegistry=s.schemaRegistry||{version:'candidate',connected:false};s.meta.databaseVersion=3;applied.push('v3-audit-and-schema-registry')}
 if(applied.length){s.migrationsApplied.push(...applied.map(id=>({id,at:new Date().toISOString()})));s.meta.updatedAt=new Date().toISOString();s.meta.build=BUILD}
 return {state:s,applied}}
function rawLoad(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(error){return {__loadError:String(error)}}}
function load(){const raw=rawLoad();const result=migrate(raw);if(result.applied.length)save(result.state,{reason:'automatic-migration',backup:true,silent:true});return result.state}
function backups(){try{return JSON.parse(localStorage.getItem(BACKUP_KEY)||'[]')}catch{return []}}
function backup(reason='manual'){const raw=rawLoad();const list=backups();const entry={id:`backup-${Date.now()}`,createdAt:new Date().toISOString(),reason,databaseVersion:raw?.meta?.databaseVersion||0,data:raw};list.unshift(entry);localStorage.setItem(BACKUP_KEY,JSON.stringify(list.slice(0,20)));emit('backup-created',entry);return entry}
function save(next,{reason='update',backup=false,silent=false}={}){let s=normalize(clone(next));if(backup)api.backup(`before-${reason}`);s.meta.databaseVersion=DB_VERSION;s.meta.updatedAt=new Date().toISOString();s.meta.build=BUILD;s.auditLog=Array.isArray(s.auditLog)?s.auditLog:[];s.auditLog.unshift({id:`audit-${Date.now()}`,at:s.meta.updatedAt,reason});s.auditLog=s.auditLog.slice(0,500);localStorage.setItem(STORAGE_KEY,JSON.stringify(s));if(!silent){emit('state-changed',{reason,state:s});try{window.dispatchEvent(new CustomEvent('aioc:state-changed',{detail:{reason}}))}catch{}}return s}
function update(mutator,options={}){const current=load();const draft=clone(current);const value=mutator(draft);return save(value&&typeof value==='object'?value:draft,options)}
function restore(id){const entry=backups().find(x=>x.id===id);if(!entry)throw new Error('Backup not found');backup('before-restore');const migrated=migrate(entry.data).state;save(migrated,{reason:`restore-${id}`,silent:false});return migrated}
function downloadBackup(){const payload={format:'multiversal-aioc-backup',exportedAt:new Date().toISOString(),databaseVersion:DB_VERSION,state:load(),backups:backups().slice(0,5)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`multiversal-aioc-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function attention(s=load()){const unresolvedDecisions=s.decisions.filter(x=>!['resolved','closed','approved','rejected'].includes(String(x.status||'open').toLowerCase()));const pendingApprovals=s.approvals.filter(x=>String(x.status||'pending').toLowerCase()==='pending');const activeAlerts=s.alerts.filter(x=>!['done','closed','resolved'].includes(String(x.status||'open').toLowerCase()));const blockedWork=[...s.agents.filter(x=>String(x.status).toLowerCase()==='blocked'),...s.tasks.filter(x=>String(x.status).toLowerCase()==='blocked')];return {unresolvedDecisions,pendingApprovals,activeAlerts,blockedWork,total:unresolvedDecisions.length+pendingApprovals.length+activeAlerts.length+blockedWork.length}}
function metrics(s=load()){const a=attention(s);return {gameObjects:s.gameObjects.length,packLists:s.packLists.length,...Object.fromEntries(Object.entries(a).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,v.length])),attentionTotal:a.total,lastUpdated:s.meta.updatedAt,databaseVersion:s.meta.databaseVersion,build:s.meta.build}}
function validate(s=load()){const issues=[];if(s.__loadError)issues.push({severity:'error',code:'storage.parse',message:s.__loadError});const ids=new Set();s.gameObjects.forEach((o,i)=>{if(!o.id)issues.push({severity:'error',code:'object.id',message:`Game object ${i+1} has no stable ID`});else if(ids.has(o.id))issues.push({severity:'error',code:'object.duplicate',message:`Duplicate ID ${o.id}`});else ids.add(o.id);if(!o.name)issues.push({severity:'warning',code:'object.name',message:`${o.id||`Object ${i+1}`} has no name`})});return issues}
function on(type,fn){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn);return()=>listeners.get(type)?.delete(fn)}
function emit(type,data){listeners.get(type)?.forEach(fn=>{try{fn(data)}catch(error){console.error(error)}})}
const api={DB_VERSION,BUILD,load,save,update,backup,backups,restore,downloadBackup,attention,metrics,validate,on,emit,migrate};window.AIOCData=api;
try{const state=load();window.dispatchEvent(new CustomEvent('aioc:data-ready',{detail:{version:state.meta.databaseVersion,build:BUILD}}))}catch(error){console.error('AIOC data initialization failed',error)}
})();