const FEATURE_GROUPS = [
  ['Command', [['dashboard','Executive Dashboard'],['assistant','AIOC Assistant'],['search','Semantic Search'],['twin','Project Digital Twin'],['alerts','Decision & Alert Inbox']]],
  ['AI Operations', [['sessions','Session Manager'],['agents','Agent Team'],['routing','Task Router'],['workload','Workload & Performance'],['dispatcher','Agent Dispatcher'],['packets','Task Packet Builder'],['compressor','Context Compressor'],['prompts','Prompt Library'],['credits','Credit & Efficiency']]],
  ['Knowledge', [['knowledge','Knowledge Graph'],['decisions','Decision History'],['livingdocs','Living Documentation'],['notebook','AI Notebook'],['voice','Voice Capture'],['imports','Photo & File Capture']]],
  ['Repository', [['repository','Repository Intelligence'],['dependencies','Dependency Graph'],['conflicts','Conflict Detector'],['releases','Release Notes'],['migrations','Migration Planner'],['artifacts','Artifacts & Receipts'],['approvals','Approval Queue']]],
  ['Analytics', [['analytics','Development Analytics'],['heatmap','Progress Heatmap'],['timeline','Timeline & Critical Path'],['estimator','Time Estimator'],['bottlenecks','Bottleneck Detection']]],
  ['Multiversal Authoring', [['worlds','World Builder'],['worldtimeline','World Timeline'],['abilities','Ability Designer'],['creatures','Creature Builder'],['species','Species Builder'],['items','Item Builder'],['vehicles','Vehicle Builder'],['quests','Quest Builder'],['dialogue','Dialogue Builder'],['storyflow','Story Flow Graph'],['relationships','Relationship Map'],['rules','Rule Validator'],['packvalidator','Pack Validator']]],
  ['Personal & Safety', [['daily','Daily Plan'],['calendar','Calendar & Deadlines'],['focus','Focus Timer'],['checkpoints','Version Time Machine'],['recovery','Emergency Recovery'],['settings','Settings']]]
];
const ALL_FEATURES = FEATURE_GROUPS.flatMap(g=>g[1]);
const now=()=>new Date().toISOString(); const today=()=>now().slice(0,10);
const defaults={
 version:'0.2.0', project:{name:'Multiversal',phase:'MS-02',workPackage:'WP-011',progress:67,branch:'main',commit:'f1f49b5',nextDecision:'Run Apple spike on borrowed Mac',targetDate:'',risk:'medium'},
 agents:[{id:1,name:'Codex Lead',role:'Implementation',status:'idle',task:'Awaiting Mac execution',capacity:100,quality:92,credits:0},{id:2,name:'Architecture Agent',role:'Architecture',status:'ready',task:'Repository review',capacity:75,quality:94,credits:0},{id:3,name:'Rules Agent',role:'Game systems',status:'blocked',task:'Awaiting source packet',capacity:40,quality:90,credits:0}],
 approvals:[],alerts:[],decisions:[],sessions:[],artifacts:[],notes:[],prompts:[{id:1,title:'Resume governed work',category:'Continuation',body:'Read the current work order, continuity packet, control state, and latest receipt. Resume from the first incomplete governed step. Do not repeat completed work.'}],
 knowledge:[{id:1,title:'WP-011 Apple Spike',type:'work-package',tags:'apple,tauri,ios',links:'Multiversal repository; WP-010',summary:'One-pass borrowed-Mac validation gate.'}], docs:[],tasks:[],dependencies:[],releases:[],migrations:[],checkpoints:[],calendar:[],
 worlds:[],worldtimeline:[],abilities:[],creatures:[],species:[],items:[],vehicles:[],quests:[],dialogue:[],storyflow:[],relationships:[],
 timeline:[{id:1,title:'WP-011 Apple Spike',status:'active',date:today(),progress:67,dependsOn:''}],
 credits:{used:0,budget:100,entries:[]}, focus:{minutes:25,running:false,endsAt:null,label:'Current work package'},
 settings:{githubRepo:'cybalicistjt-stack/Multiversal-app',githubToken:'',aiKey:'',owner:'John Brandon Turner',theme:'dark',autosnapshot:true}
};
let state=load(), view='dashboard', modal=null, drawer=false, timerHandle=null;
function clone(x){return JSON.parse(JSON.stringify(x))} function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k])merge(a[k],b[k]);else a[k]=b[k]}return a}
function load(){try{return merge(clone(defaults),JSON.parse(localStorage.getItem('aioc-state')||'{}'))}catch{return clone(defaults)}}
function save(silent=false){localStorage.setItem('aioc-state',JSON.stringify(state)); if(state.settings.autosnapshot&&!silent)autoSnapshot()}
function autoSnapshot(){const last=state.checkpoints[0]; if(!last||Date.now()-new Date(last.created).getTime()>3600000){state.checkpoints.unshift({id:uid(),title:'Automatic checkpoint',created:now(),data:JSON.stringify({...state,checkpoints:[]})});state.checkpoints=state.checkpoints.slice(0,20);localStorage.setItem('aioc-state',JSON.stringify(state))}}
function uid(){return Date.now()+Math.floor(Math.random()*1000)} function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badge(s=''){const v=String(s).toLowerCase(),c=/done|ready|approved|pass|complete/.test(v)?'ok':/block|deny|fail|risk|overdue/.test(v)?'danger':'warn';return `<span class="badge ${c}">${esc(s)}</span>`}
function title(id){return (ALL_FEATURES.find(x=>x[0]===id)||['',id])[1]}
function icon(id){return ({dashboard:'⌂',assistant:'✦',search:'⌕',twin:'◎',alerts:'!',sessions:'↻',agents:'♟',routing:'⇢',workload:'◫',dispatcher:'▶',packets:'▣',compressor:'≋',prompts:'❝',credits:'◉',knowledge:'⌘',decisions:'◆',livingdocs:'▤',notebook:'✎',voice:'◖',imports:'▧',repository:'⌥',dependencies:'⌁',conflicts:'⚠',releases:'◇',migrations:'⇄',artifacts:'□',approvals:'✓',analytics:'⌁',heatmap:'▦',timeline:'↝',estimator:'◷',bottlenecks:'⌛',worlds:'◉',worldtimeline:'⌛',abilities:'✧',creatures:'♞',species:'♧',items:'◇',vehicles:'▷',quests:'⚑',dialogue:'❞',storyflow:'⑂',relationships:'⌬',rules:'§',packvalidator:'✓',daily:'☀',calendar:'▥',focus:'◷',checkpoints:'↶',recovery:'☂',settings:'⚙'})[id]||'•'}
function render(){document.querySelector('#app').innerHTML=`<div class="app-shell"><aside class="sidebar ${drawer?'open':''}">${sideNav()}</aside><main class="main"><header class="topbar"><button class="menu" onclick="drawer=!drawer;render()">☰</button><div class="brand"><div class="logo">M</div><div><h1>Multiversal AIOC</h1><small>${esc(state.project.workPackage)} · ${esc(state.project.phase)}</small></div></div><div class="top-actions"><button class="iconbtn" onclick="openFeature('search')">⌕</button><button class="iconbtn" onclick="quickAdd()">＋</button></div></header><div class="page">${featureBody(view)}</div></main></div>${modal?modalHtml():''}`;startTimerLoop()}
function sideNav(){return `<div class="side-brand"><div class="logo">M</div><div><b>AIOC</b><small>Operations OS</small></div></div>${FEATURE_GROUPS.map(([g,items])=>`<div class="navgroup"><span>${g}</span>${items.map(([id,n])=>`<button class="${view===id?'active':''}" onclick="openFeature('${id}')"><i>${icon(id)}</i>${n}</button>`).join('')}</div>`).join('')}<div class="side-foot">Standalone · Local-first · v${state.version}</div>`}
function openFeature(id){view=id;drawer=false;modal=null;render();scrollTo(0,0)} function quickAdd(){openForm('note')} function pageHead(kicker,head,desc='',actions=''){return `<div class="page-head"><div><div class="kicker">${kicker}</div><h2>${head}</h2>${desc?`<p>${desc}</p>`:''}</div>${actions?`<div class="toolbar">${actions}</div>`:''}</div>`}
function metric(label,val,detail=''){return `<div class="metric"><span>${label}</span><b>${val}</b><small>${detail}</small></div>`}
function featureBody(id){const map={dashboard,assistant,search,twin,alerts,sessions,agents,routing,workload,dispatcher,packets,compressor,prompts,credits,knowledge,decisions,livingdocs,notebook,voice,imports,repository,dependencies,conflicts,releases,migrations,artifacts,approvals,analytics,heatmap,timeline,estimator,bottlenecks,worlds:()=>author('worlds','World Builder'),worldtimeline:()=>author('worldtimeline','World Timeline'),abilities:()=>author('abilities','Ability Designer'),creatures:()=>author('creatures','Creature Builder'),species:()=>author('species','Species Builder'),items:()=>author('items','Item Builder'),vehicles:()=>author('vehicles','Vehicle Builder'),quests:()=>author('quests','Quest Builder'),dialogue:()=>author('dialogue','Dialogue Builder'),storyflow:()=>author('storyflow','Story Flow Graph'),relationships:()=>author('relationships','Relationship Map'),rules,packvalidator,daily,calendar,focus,checkpoints,recovery,settings};return (map[id]||dashboard)()}
function dashboard(){const open=state.alerts.filter(x=>x.status!=='done').length+state.approvals.filter(x=>x.status==='pending').length;const blockers=state.agents.filter(x=>x.status==='blocked').length;return `${pageHead('Mission control','Executive Intelligence Dashboard','A synthesized view of progress, risk, decisions, and the safest next move.',`<button class="primary" onclick="openFeature('dispatcher')">Continue work</button>`)}<section class="hero"><div class="panel mission"><div class="kicker">Current mission</div><h3>${esc(state.project.workPackage)} · ${esc(state.project.phase)}</h3><p>${esc(state.project.nextDecision)}</p><div class="progress"><span style="width:${state.project.progress}%"></span></div><div class="row"><b>${state.project.progress}% complete</b>${badge(state.project.risk+' risk')}</div></div><div class="insight panel"><div class="kicker">Executive intelligence</div><h3>${esc(executiveInsight())}</h3><button class="secondary" onclick="openFeature('bottlenecks')">See reasoning</button></div></section><div class="metrics">${metric('Open decisions',open,'Needs owner attention')}${metric('Blocked agents',blockers,'Resolve before dispatch')}${metric('Knowledge nodes',state.knowledge.length,'Linked project memory')}${metric('Credit remaining',Math.max(0,state.credits.budget-state.credits.used),'Estimated budget units')}</div><section class="panel pad"><div class="row"><h3>Priority queue</h3><button class="textbtn" onclick="openFeature('daily')">Plan today</button></div>${priorityRows()}</section><section class="two"><div class="panel pad"><h3>Agent pulse</h3>${state.agents.slice(0,5).map(a=>`<div class="line"><div><b>${esc(a.name)}</b><small>${esc(a.task)}</small></div>${badge(a.status)}</div>`).join('')}</div><div class="panel pad"><h3>Project systems</h3>${systemProgress().map(x=>`<div class="barrow"><span>${x[0]}</span><div class="progress"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</div></section>`}
function executiveInsight(){if(state.agents.some(a=>a.status==='blocked'))return 'Blocked work is the immediate schedule risk. Clear the oldest blocker before starting new work.';if(state.approvals.some(a=>a.status==='pending'))return 'A pending approval is the safest next action and may unlock downstream tasks.';if(state.project.progress<50)return 'Focus on the current work package; expanding scope now would increase context and coordination cost.';return 'The project is moving. Preserve continuity, finish the current gate, then select the highest-dependency next package.'}
function priorityRows(){let rows=[...state.alerts.filter(x=>x.status!=='done').map(x=>({t:x.title,d:x.detail,s:x.status||'open'})),...state.approvals.filter(x=>x.status==='pending').map(x=>({t:x.title,d:x.detail,s:'approval'})),...state.tasks.filter(x=>x.status!=='done').map(x=>({t:x.title,d:x.detail||x.owner,s:x.status||'open'}))].slice(0,6);if(!rows.length)rows=[{t:state.project.nextDecision,d:'Current governed next action',s:'active'}];return rows.map(x=>`<div class="line"><div><b>${esc(x.t)}</b><small>${esc(x.d||'')}</small></div>${badge(x.s)}</div>`).join('')}
function systemProgress(){return [['Planning',96],['Documentation',90],['Rules',82],['Application',state.project.progress],['Testing',Math.max(15,state.project.progress-30)],['Release',Math.max(5,state.project.progress-55)]]}
function assistant(){return `${pageHead('Local command layer','AIOC Assistant','Ask project questions or issue local commands. It uses your stored AIOC data and does not send anything off-device.')}<section class="panel pad"><div id="chat" class="chat"><div class="bubble ai">Try: “What is blocking development?”, “Resume WP-011”, “Create the next task packet”, “Project status”, or “What should I do next?”</div></div><div class="composer"><textarea id="assistantInput" placeholder="Ask AIOC…"></textarea><button class="primary" onclick="askAssistant()">Send</button></div></section>`}
function askAssistant(){const q=document.querySelector('#assistantInput').value.trim();if(!q)return;const chat=document.querySelector('#chat');chat.innerHTML+=`<div class="bubble user">${esc(q)}</div>`;let a=assistantAnswer(q);chat.innerHTML+=`<div class="bubble ai">${esc(a)}</div>`;document.querySelector('#assistantInput').value='';chat.scrollTop=chat.scrollHeight}
function assistantAnswer(q){const s=q.toLowerCase();if(/block/.test(s)){const b=state.agents.filter(a=>a.status==='blocked');return b.length?b.map(x=>`${x.name}: ${x.task}`).join('\n'):'No agent is currently marked blocked.'}if(/resume|continue/.test(s))return dispatchText();if(/packet/.test(s))return JSON.stringify(makePacketObject(),null,2);if(/status|where.*project/.test(s))return `${state.project.name} is ${state.project.progress}% complete in ${state.project.phase}, currently on ${state.project.workPackage}. Next: ${state.project.nextDecision}`;if(/next|should.*do/.test(s))return executiveInsight()+`\nRecommended action: ${state.project.nextDecision}`;if(/credit/.test(s))return `${state.credits.used} of ${state.credits.budget} units recorded; ${Math.max(0,state.credits.budget-state.credits.used)} remain.`;const hit=searchAll(q)[0];return hit?`Closest project record: ${hit.title} — ${hit.text}`:'I do not have a matching local record yet. Add it to the notebook or knowledge graph, or phrase the request as a status, blocker, continuation, packet, or credit question.'}
function search(){return `${pageHead('Project memory','Semantic Search','Search across decisions, notes, sessions, knowledge, artifacts, authoring records, and tasks.')}<section class="panel pad"><div class="searchbox"><input id="searchInput" placeholder="Example: social combat, old ability schema, Apple spike" oninput="runSearch()"><button class="primary" onclick="runSearch()">Search</button></div><div id="searchResults" class="list"><div class="empty">Type a question or concept.</div></div></section>`}
function searchAll(q){const words=q.toLowerCase().split(/\W+/).filter(x=>x.length>2);const sources=[['knowledge',state.knowledge],['decision',state.decisions],['note',state.notes],['session',state.sessions],['artifact',state.artifacts],['task',state.tasks],...['worlds','abilities','creatures','species','items','vehicles','quests','dialogue','relationships'].map(k=>[k,state[k]])];return sources.flatMap(([type,arr])=>arr.map(x=>{const title=x.title||x.name||type,text=Object.values(x).filter(v=>typeof v==='string').join(' ');const hay=(title+' '+text).toLowerCase(),score=words.reduce((n,w)=>n+(hay.includes(w)?2:0)+(title.toLowerCase().includes(w)?2:0),0);return {type,title,text,score}})).filter(x=>x.score).sort((a,b)=>b.score-a.score)}
function runSearch(){const q=document.querySelector('#searchInput').value, r=searchAll(q);document.querySelector('#searchResults').innerHTML=r.length?r.slice(0,30).map(x=>`<div class="item"><div class="row"><b>${esc(x.title)}</b><span class="badge">${esc(x.type)}</span></div><p>${esc(x.text.slice(0,260))}</p></div>`).join(''):'<div class="empty">No matching local records.</div>'}
function twin(){const deps=state.dependencies.length, stale=state.docs.filter(d=>d.status==='stale').length, blocked=state.agents.filter(a=>a.status==='blocked').length;return `${pageHead('Live project model','Multiversal Development Digital Twin','Model dependencies, simulate changes, and identify stale documentation or downstream effects.')}<div class="metrics">${metric('Dependencies',deps,'Recorded links')}${metric('Stale docs',stale,'Need reconciliation')}${metric('Blocked nodes',blocked,'Agent or work gates')}${metric('Active package',state.project.workPackage,state.project.phase)}</div><section class="two"><div class="panel pad"><h3>Impact simulation</h3><label>Change or delayed component</label><input id="impactNode" placeholder="Example: WP-014 or ability schema"><label>Delay in days</label><input id="impactDays" type="number" value="14"><button class="primary" onclick="simulateImpact()">Simulate impact</button><div id="impactOut" class="code">Enter a component to model.</div></div><div class="panel pad"><h3>Model health</h3>${modelHealth().map(x=>`<div class="line"><span>${x[0]}</span>${badge(x[1])}</div>`).join('')}</div></section><section class="panel pad"><h3>Dependency model</h3>${dependencyVisual()}</section>`}
function simulateImpact(){const n=document.querySelector('#impactNode').value||'Unnamed component',d=Number(document.querySelector('#impactDays').value||0),matches=state.dependencies.filter(x=>JSON.stringify(x).toLowerCase().includes(n.toLowerCase()));document.querySelector('#impactOut').textContent=`SIMULATION\nChanged node: ${n}\nDelay: ${d} days\nDirect recorded links: ${matches.length}\nLikely effects: ${matches.length?matches.map(x=>x.to||x.target||x.title).join(', '):'No explicit links recorded; treat impact as unknown and add dependencies before authorizing the change.'}\nRecommended response: freeze dependent work, update the decision record, mark affected documentation stale, and recalculate the critical path.`}
function modelHealth(){return [['Repository pointer',state.project.commit?'ready':'missing'],['Current work package',state.project.workPackage?'ready':'missing'],['Dependency coverage',state.dependencies.length?'partial':'missing'],['Decision provenance',state.decisions.length?'partial':'missing'],['Recovery checkpoint',state.checkpoints.length?'ready':'missing']]}
function dependencyVisual(){const rows=state.dependencies.length?state.dependencies:[{from:'WP-010',to:'WP-011',type:'blocks'},{from:'WP-011',to:'WP-012',type:'unlocks'}];return `<div class="graph">${rows.map(x=>`<div class="node">${esc(x.from||'source')}</div><div class="edge">${esc(x.type||'→')} →</div><div class="node">${esc(x.to||'target')}</div>`).join('')}</div>`}
function alerts(){return genericList('alerts','Decision & Alert Inbox','Only owner decisions, blockers, risks, and required interventions belong here.','alert')}
function sessions(){return genericList('sessions','AI Session Manager','Capture checkpoints, summaries, pending questions, and one-tap resume prompts.','session')}
function agents(){return genericList('agents','Agent Team','Roles, status, active task, capacity, quality, and specialty profiles.','agent')}
function routing(){return `${pageHead('Coordination','Automatic Task Router','Score agents by role, status, capacity, and task keywords.')}<section class="panel pad"><label>Task request</label><textarea id="routeTask" placeholder="Describe the work to route"></textarea><button class="primary" onclick="routeTask()">Recommend agent</button><div id="routeOut" class="code">No task routed yet.</div></section>`}
function routeTask(){const text=document.querySelector('#routeTask').value.toLowerCase();const scores=state.agents.map(a=>{let score=(a.status==='ready'?30:a.status==='idle'?20:a.status==='blocked'?-100:0)+(Number(a.capacity)||0)/5+(Number(a.quality)||0)/10;for(const w of (a.role+' '+a.name).toLowerCase().split(/\W+/))if(w.length>3&&text.includes(w))score+=25;return {a,score}}).sort((x,y)=>y.score-x.score);const best=scores[0];document.querySelector('#routeOut').textContent=best?`Recommended: ${best.a.name}\nRole: ${best.a.role}\nScore: ${Math.round(best.score)}\nReason: availability, capacity, quality, and keyword fit.\n\nCreate a governed task packet before dispatch.`:'No agents are configured.'}
function workload(){return `${pageHead('Team intelligence','Agent Workload & Performance','Compare utilization, block time, quality, and recorded credit use.')}<section class="panel pad">${state.agents.map(a=>`<div class="workrow"><div><b>${esc(a.name)}</b><small>${esc(a.role)} · ${esc(a.task)}</small></div><div class="mini"><span>Capacity ${a.capacity||0}%</span><div class="progress"><span style="width:${a.capacity||0}%"></span></div></div><div class="mini"><span>Quality ${a.quality||0}%</span><div class="progress"><span style="width:${a.quality||0}%"></span></div></div>${badge(a.status)}</div>`).join('')}</section>`}
function dispatcher(){const p=dispatchText();return `${pageHead('Execution','Agent Dispatcher','Generate a bounded continuation command using project state and credit-saving protocols.')}<section class="panel pad"><div class="code">${esc(p)}</div><button class="primary" onclick='copyText(${JSON.stringify(p)})'>Copy dispatch prompt</button></section>`}
function dispatchText(){return `You are the active Multiversal development agent.\nRepository: ${state.settings.githubRepo}\nBranch: ${state.project.branch}\nCommit: ${state.project.commit}\nCurrent phase: ${state.project.phase}\nCurrent work package: ${state.project.workPackage}\nNext required action: ${state.project.nextDecision}\n\nRead the governed work order, current control state, continuity packet, and latest receipts. Resume at the first incomplete step. Use the context, task-packet, workflow, control, and continuity protocols to minimize credit use. Do not repeat completed work. Stop only for a genuine credential, destructive, legal, or owner-authority gate.`}
function packets(){return `${pageHead('Governance','Task Packet Builder','Create deterministic, portable work packets.')}<section class="panel pad"><div class="formgrid"><label>Work ID<input id="pid" value="${esc(state.project.workPackage)}"></label><label>Owner/agent<input id="powner" value="Codex Lead"></label></div><label>Objective<textarea id="pobj">${esc(state.project.nextDecision)}</textarea></label><label>Constraints<textarea id="pcon">Use governed repository rules. Minimize repeated context and credit use. Produce tests, receipts, checksums, and continuity state.</textarea></label><button class="primary" onclick="renderPacket()">Generate packet</button><div id="packetout" class="code"></div></section>`}
function makePacketObject(){return {schema:'mv.task.packet.1',id:document.querySelector('#pid')?.value||state.project.workPackage,owner:document.querySelector('#powner')?.value||'Codex Lead',objective:document.querySelector('#pobj')?.value||state.project.nextDecision,constraints:(document.querySelector('#pcon')?.value||'Use governed project rules.').split('\n'),requiredOutputs:['implementation','tests','receipt','checksums','continuity update'],stopConditions:['credential gate','destructive owner decision','contradictory canonical authority'],contextPointers:[state.settings.githubRepo,state.project.commit,state.project.workPackage]}}
function renderPacket(){document.querySelector('#packetout').textContent=JSON.stringify(makePacketObject(),null,2)}
function compressor(){return toolPage('Context Compressor','Produce a compact mission/current-state/open-items/source-pointer continuation packet.','Compress','compress')}
function prompts(){return genericList('prompts','Prompt Library','Reusable governed prompts, recovery prompts, and role instructions.','prompt')}
function credits(){const c=state.credits,p=Math.min(100,Math.round(c.used/c.budget*100)||0),quality=state.agents.length?Math.round(state.agents.reduce((n,a)=>n+(Number(a.quality)||0),0)/state.agents.length):0;return `${pageHead('Resource control','Credit & AI Efficiency','Manual usage ledger, forecast, and output-quality indicators.')}<div class="metrics">${metric('Used',c.used,`of ${c.budget}`)}${metric('Remaining',Math.max(0,c.budget-c.used),'budget units')}${metric('Average quality',quality+'%','agent profiles')}${metric('Efficiency',c.used?Math.round(state.project.progress/c.used*100)/100:'—','progress per unit')}</div><section class="panel pad"><div class="progress"><span style="width:${p}%"></span></div><div class="toolbar"><button class="primary" onclick="openForm('credit')">Record usage</button><button class="secondary" onclick="editBudget()">Change budget</button></div>${state.credits.entries.map(e=>`<div class="line"><span>${esc(e.label)}</span><b>${e.amount}</b></div>`).join('')||'<div class="empty">No usage entries.</div>'}</section>`}
function knowledge(){return genericList('knowledge','AI Knowledge Graph','Link work packages, documents, rules, systems, sources, and decisions.','knowledge')}
function decisions(){return genericList('decisions','Decision History','Record what changed, why, alternatives, authority, and affected systems.','decision')}
function livingdocs(){return genericList('docs','Living Documentation','Track canonical documents, generated summaries, owners, and staleness.','doc')}
function notebook(){return genericList('notes','AI Notebook','Capture ideas and convert them into tasks, records, or authoring entries.','note')}
function voice(){const supported=('webkitSpeechRecognition'in window)||('SpeechRecognition'in window);return `${pageHead('Fast capture','Voice Capture','Dictate ideas and save them directly to the local notebook.')}<section class="panel pad"><textarea id="voiceText" placeholder="Transcript appears here"></textarea><div class="toolbar"><button class="primary" onclick="startVoice()" ${supported?'':'disabled'}>${supported?'Start dictation':'Speech recognition unavailable'}</button><button class="secondary" onclick="saveVoice()">Save to notebook</button></div><p class="muted">Browser speech recognition may use your Android speech service. The saved record remains local.</p></section>`}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;const r=new R();r.continuous=true;r.interimResults=true;r.onresult=e=>{document.querySelector('#voiceText').value=Array.from(e.results).map(x=>x[0].transcript).join(' ')};r.start();toast('Listening…')}
function saveVoice(){const body=document.querySelector('#voiceText').value.trim();if(!body)return;state.notes.unshift({id:uid(),title:'Voice capture '+new Date().toLocaleString(),kind:'voice',body,created:now()});save();toast('Voice note saved')}
function imports(){return `${pageHead('Capture','Photo & File Capture','Attach a photo or text file, add notes, and preserve a local reference.')}<section class="panel pad"><input id="captureFile" type="file" accept="image/*,.txt,.md,.json" capture="environment"><label>Title<input id="captureTitle" placeholder="What is this?"></label><label>Notes<textarea id="captureNotes"></textarea></label><button class="primary" onclick="captureImport()">Save capture record</button><p class="muted">To keep backups small, images are referenced by filename and metadata rather than stored permanently. Text files up to 200 KB are imported into the note.</p></section>`}
function captureImport(){const f=document.querySelector('#captureFile').files[0];if(!f)return toast('Choose a file');const base={id:uid(),title:document.querySelector('#captureTitle').value||f.name,kind:'capture',body:document.querySelector('#captureNotes').value,filename:f.name,mime:f.type,size:f.size,created:now()};if((f.type.startsWith('text/')||/\.(md|json)$/i.test(f.name))&&f.size<200000){const r=new FileReader();r.onload=()=>{base.body+='\n\n'+r.result;state.notes.unshift(base);save();toast('Text imported')};r.readAsText(f)}else{state.notes.unshift(base);save();toast('Capture recorded')}}
function repository(){const health=repoHealth();return `${pageHead('Code intelligence','Repository Intelligence','Local repository pointer, health checklist, risks, and integration-ready settings.')}<div class="metrics">${metric('Health',health.score+'%',health.label)}${metric('Branch',state.project.branch,'current')}${metric('Commit',state.project.commit,'recorded head')}${metric('Artifacts',state.artifacts.length,'receipts and logs')}</div><section class="two"><div class="panel pad"><h3>${esc(state.settings.githubRepo)}</h3><div class="line"><span>Clean commit pointer</span>${badge(state.project.commit?'pass':'missing')}</div><div class="line"><span>Recovery checkpoint</span>${badge(state.checkpoints.length?'pass':'missing')}</div><div class="line"><span>Recorded dependencies</span>${badge(state.dependencies.length?'partial':'missing')}</div><div class="line"><span>Pending migrations</span>${badge(state.migrations.filter(x=>x.status!=='done').length?'review':'pass')}</div></div><div class="panel pad"><h3>Risk areas</h3>${repoRisks().map(x=>`<div class="line"><span>${x}</span>${badge('review')}</div>`).join('')}</div></section>`}
function repoHealth(){let score=20+(state.project.commit?20:0)+(state.checkpoints.length?20:0)+(state.dependencies.length?20:0)+(state.artifacts.length?20:0);return {score,label:score>79?'healthy':score>49?'partial':'under-documented'}}
function repoRisks(){const r=[];if(!state.dependencies.length)r.push('Dependency graph not populated');if(!state.checkpoints.length)r.push('No AIOC checkpoint');if(!state.artifacts.length)r.push('No receipts recorded');if(state.migrations.some(x=>x.status!=='done'))r.push('Open migration plan');return r.length?r:['No obvious local-data risks recorded']}
function dependencies(){return genericList('dependencies','Dependency Graph','Record package, module, document, and system relationships.','dependency')}
function conflicts(){const conflicts=detectConflicts();return `${pageHead('Change safety','Conflict Detector','Find tasks or migrations that name the same files, modules, or systems.')}<section class="panel pad">${conflicts.length?conflicts.map(x=>`<div class="item"><b>${esc(x.key)}</b><p>${esc(x.items.join(' ↔ '))}</p>${badge('review')}</div>`).join(''):'<div class="empty">No local conflicts detected. Add file or system scope to tasks and migrations for stronger detection.</div>'}</section>`}
function detectConflicts(){const map={};[...state.tasks,...state.migrations].forEach(x=>String(x.scope||x.files||'').split(/[,;\n]/).map(v=>v.trim()).filter(Boolean).forEach(k=>(map[k]??=[]).push(x.title||x.name)));return Object.entries(map).filter(x=>x[1].length>1).map(([key,items])=>({key,items}))}
function releases(){return genericList('releases','Automatic Release Notes','Build release entries from completed work packages, decisions, and artifacts.','release',`<button class="secondary" onclick="generateRelease()">Generate from current state</button>`)}
function generateRelease(){state.releases.unshift({id:uid(),title:`${state.project.workPackage} progress release`,version:'0.0.0-dev',date:today(),status:'draft',summary:`Current package ${state.project.workPackage} reached ${state.project.progress}%.`,changes:state.decisions.slice(0,5).map(x=>x.title).join('; '),artifacts:state.artifacts.slice(0,5).map(x=>x.title).join('; ')});save();render();toast('Draft release generated')}
function migrations(){return genericList('migrations','Migration Planner','Plan schema, data, API, pack, and document migrations with rollback and affected scope.','migration')}
function artifacts(){return genericList('artifacts','Artifacts & Receipts','Track logs, screenshots, checksums, evidence, packages, and canonical outputs.','artifact')}
function approvals(){return genericList('approvals','Approval Queue','Approve or deny governed changes from the phone.','approval')}
function analytics(){const completed=state.timeline.filter(x=>/done|complete/.test(x.status)).length,total=Math.max(1,state.timeline.length),velocity=Math.round(completed/Math.max(1,new Set(state.timeline.map(x=>x.date)).size)*10)/10;return `${pageHead('Measurement','Development Analytics','Progress, velocity, decision load, agent efficiency, and completion forecasts.')}<div class="metrics">${metric('Overall',state.project.progress+'%','owner estimate')}${metric('Velocity',velocity,'milestones/day')}${metric('Decision load',state.decisions.filter(x=>x.status!=='done').length,'unresolved')}${metric('Recorded output',state.artifacts.length,'artifacts')}</div><section class="panel pad"><h3>Progress by system</h3>${systemProgress().map(x=>`<div class="barrow"><span>${x[0]}</span><div class="progress"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</section>`}
function heatmap(){return `${pageHead('Coverage','Progress Heatmap','A quick visual map of complete, active, weak, and untracked project systems.')}<section class="heatmap">${systemProgress().concat([['World packs',45],['Creatures',38],['Items',34],['Species',41],['Vehicles',28],['Settings',55],['AI operations',85],['Recovery',state.checkpoints.length?90:30]]).map(([n,p])=>`<div class="heat" style="--p:${p}"><b>${esc(n)}</b><span>${p}%</span></div>`).join('')}</section>`}
function timeline(){return genericList('timeline','Timeline & Critical Path','Milestones, dependencies, progress, dates, and active critical path.','timeline')}
function estimator(){const remaining=100-state.project.progress,velocity=Math.max(1,state.timeline.filter(x=>/done|complete/.test(x.status)).length||1),days=Math.ceil(remaining/Math.max(1,velocity*2));return `${pageHead('Forecasting','Time Estimator','A simple transparent estimate based on remaining progress and recorded completion velocity.')}<section class="panel pad"><div class="big-number">${days} days</div><p>Estimated to reach the current project target at the recorded pace. This is directional, not a commitment.</p><div class="code">Remaining progress: ${remaining}%\nVelocity signal: ${velocity}\nRisk modifier: ${state.project.risk}\nConfidence: ${state.timeline.length>5?'moderate':'low — add more milestones'}</div></section>`}
function bottlenecks(){const b=[];state.agents.filter(a=>a.status==='blocked').forEach(a=>b.push({title:a.name,why:a.task,impact:'Agent work cannot proceed'}));if(state.approvals.some(x=>x.status==='pending'))b.push({title:'Pending approvals',why:`${state.approvals.filter(x=>x.status==='pending').length} waiting`,impact:'May block merges or releases'});if(!state.dependencies.length)b.push({title:'Dependency visibility',why:'No formal links recorded',impact:'Critical path cannot be trusted'});if(state.credits.budget-state.credits.used<state.credits.budget*.2)b.push({title:'Credit budget',why:'Less than 20% remains',impact:'AI work may stop unexpectedly'});return `${pageHead('Risk intelligence','Bottleneck Detection','Find the constraints most likely to delay the next meaningful result.')}<section class="panel pad">${b.length?b.map(x=>`<div class="item"><b>${esc(x.title)}</b><p>${esc(x.why)}</p><small>${esc(x.impact)}</small></div>`).join(''):'<div class="empty">No strong local bottleneck signal. Continue the current work package and preserve evidence.</div>'}</section>`}
const authorConfig={worlds:['World','name,description,tags,status'],worldtimeline:['World event','title,date,world,description,impact'],abilities:['Ability','name,description,cost,target,range,duration,effect,scaling,tags'],creatures:['Creature','name,description,role,level,environment,abilities,tags'],species:['Species','name,description,traits,culture,environments,progression,tags'],items:['Item','name,description,type,cost,rarity,effects,tags'],vehicles:['Vehicle','name,description,type,crew,capacity,speed,defenses,tags'],quests:['Quest','title,description,objective,rewards,dependencies,status'],dialogue:['Dialogue node','title,speaker,text,choices,conditions,outcomes'],storyflow:['Story node','title,type,description,from,to,condition'],relationships:['Relationship','name,type,from,to,strength,status,notes']};
function author(key,head){const [sing]=authorConfig[key];return `${pageHead('Multiversal authoring',head,`Create structured ${sing.toLowerCase()} records and preserve them in portable backups.`,`<button class="primary" onclick="openForm('${key}')">Add ${sing.toLowerCase()}</button>`)}<section class="panel pad">${state[key].length?state[key].map(x=>entryCard(x,key)).join(''):'<div class="empty">No records yet.</div>'}</section>`}
function rules(){return toolPage('Rule Validator','Check a rule or ability for timing, target, range, cost, effect, duration, scaling, failure handling, and ambiguous language.','Validate','rules')}
function packvalidator(){return `${pageHead('Content quality','Pack Validator','Paste a JSON record or array to check IDs, names, duplicates, missing fields, and broken local references.')}<section class="panel pad"><textarea id="packInput" placeholder='[{"id":"creature.wolf","name":"Wolf"}]'></textarea><button class="primary" onclick="validatePack()">Validate pack</button><div id="packOut" class="code">No pack checked yet.</div></section>`}
function validatePack(){let out=[];try{let d=JSON.parse(document.querySelector('#packInput').value),a=Array.isArray(d)?d:[d],ids=new Set; a.forEach((x,i)=>{if(!x.id)out.push(`Row ${i+1}: missing id`);if(!x.name&&!x.title)out.push(`Row ${i+1}: missing name/title`);if(x.id&&ids.has(x.id))out.push(`Row ${i+1}: duplicate id ${x.id}`);ids.add(x.id)});if(!out.length)out.push(`PASS: ${a.length} record(s), unique IDs, basic naming present.`)}catch(e){out.push('FAIL: invalid JSON — '+e.message)}document.querySelector('#packOut').textContent=out.join('\n')}
function daily(){const choices=[...state.alerts.filter(x=>x.status!=='done').map(x=>x.title),...state.approvals.filter(x=>x.status==='pending').map(x=>`Approve: ${x.title}`),state.project.nextDecision,...state.tasks.filter(x=>x.status!=='done').map(x=>x.title)].filter(Boolean).slice(0,5);return `${pageHead('Owner focus','Daily Plan','Reduce the project to a small, ordered list of owner actions.')}<section class="panel pad"><h3>Today’s recommended order</h3>${choices.map((x,i)=>`<div class="line"><b>${i+1}. ${esc(x)}</b><button class="textbtn" onclick="copyText(${JSON.stringify(x)})">Copy</button></div>`).join('')}<button class="primary" onclick="openFeature('focus')">Start focus session</button></section>`}
function calendar(){return genericList('calendar','Calendar & Deadlines','Track deadlines and export them as a standard .ics calendar file.','calendar',`<button class="secondary" onclick="exportICS()">Export .ics</button>`)}
function exportICS(){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Multiversal AIOC//EN'];state.calendar.forEach(e=>{lines.push('BEGIN:VEVENT',`UID:${e.id}@multiversal-aioc`,`DTSTART:${String(e.date||today()).replaceAll('-','')}T${String(e.time||'0900').replace(':','')}00`,`SUMMARY:${e.title||'Multiversal task'}`,`DESCRIPTION:${(e.notes||'').replace(/\n/g,'\\n')}`,'END:VEVENT')});lines.push('END:VCALENDAR');download('multiversal-calendar.ics',lines.join('\r\n'),'text/calendar')}
function focus(){return `${pageHead('Deep work','Focus Timer','Run a bounded work session and automatically create a checkpoint when it ends.')}<section class="panel pad focus"><div id="focusClock" class="big-number">${focusDisplay()}</div><input id="focusLabel" value="${esc(state.focus.label)}"><div class="toolbar"><button class="primary" onclick="toggleFocus()">${state.focus.running?'Pause':'Start'}</button><button class="secondary" onclick="setFocus(25)">25 min</button><button class="secondary" onclick="setFocus(50)">50 min</button><button class="danger" onclick="resetFocus()">Reset</button></div></section>`}
function focusDisplay(){if(!state.focus.running||!state.focus.endsAt)return `${state.focus.minutes}:00`;const s=Math.max(0,Math.ceil((state.focus.endsAt-Date.now())/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function toggleFocus(){state.focus.label=document.querySelector('#focusLabel')?.value||state.focus.label;if(state.focus.running){const left=Math.max(1,Math.ceil((state.focus.endsAt-Date.now())/60000));state.focus.minutes=left;state.focus.running=false;state.focus.endsAt=null}else{state.focus.running=true;state.focus.endsAt=Date.now()+state.focus.minutes*60000}save(true);render()}
function setFocus(n){state.focus.minutes=n;state.focus.running=false;state.focus.endsAt=null;save(true);render()} function resetFocus(){setFocus(25)}
function startTimerLoop(){clearInterval(timerHandle);if(state.focus.running){timerHandle=setInterval(()=>{const e=document.querySelector('#focusClock');if(e)e.textContent=focusDisplay();if(Date.now()>=state.focus.endsAt){state.focus.running=false;state.focus.endsAt=null;createCheckpoint('Focus complete: '+state.focus.label);save(true);clearInterval(timerHandle);toast('Focus session complete');render()}},1000)}}
function checkpoints(){return `${pageHead('Recovery','Version Time Machine','Save and restore local AIOC snapshots.',`<button class="primary" onclick="createCheckpoint('Manual checkpoint')">Create checkpoint</button>`)}<section class="panel pad">${state.checkpoints.length?state.checkpoints.map(x=>`<div class="line"><div><b>${esc(x.title)}</b><small>${new Date(x.created).toLocaleString()}</small></div><button class="secondary" onclick="restoreCheckpoint(${x.id})">Restore</button></div>`).join(''):'<div class="empty">No checkpoints yet.</div>'}</section>`}
function createCheckpoint(name){const data=JSON.stringify({...state,checkpoints:[]});state.checkpoints.unshift({id:uid(),title:name,created:now(),data});state.checkpoints=state.checkpoints.slice(0,30);save(true);render();toast('Checkpoint saved')}
function restoreCheckpoint(id){const x=state.checkpoints.find(x=>x.id===id);if(!x||!confirm('Restore this checkpoint? Current unsaved state will be replaced.'))return;const kept=state.checkpoints;state=merge(clone(defaults),JSON.parse(x.data));state.checkpoints=kept;save(true);render();toast('Checkpoint restored')}
function recovery(){return `${pageHead('Safety','Emergency Recovery','Back up the full local database, restore it, and preserve the exact continuation pointer.')}<section class="two"><div class="panel pad"><h3>Recovery pointer</h3><p>Repository: ${esc(state.settings.githubRepo)}</p><p>Branch: ${esc(state.project.branch)}</p><p>Commit: ${esc(state.project.commit)}</p><p>Work package: ${esc(state.project.workPackage)}</p><div class="code">1. Restore repository at recorded commit.\n2. Import latest AIOC backup.\n3. Read current work order and receipt.\n4. Generate dispatcher prompt.\n5. Resume first incomplete step only.</div></div><div class="panel pad"><h3>Backup controls</h3><button class="primary block" onclick="exportData()">Export full backup</button><label class="secondary block">Import backup<input type="file" hidden onchange="importData(event)"></label><button class="secondary block" onclick="createCheckpoint('Pre-recovery checkpoint')">Create local checkpoint</button><button class="danger block" onclick="testBackup()">Test backup integrity</button><div id="backupTest" class="code">Not tested.</div></div></section>`}
function testBackup(){try{const s=JSON.stringify(state),x=JSON.parse(s);document.querySelector('#backupTest').textContent=`PASS\nJSON bytes: ${new Blob([s]).size}\nTop-level collections: ${Object.keys(x).length}\nVersion: ${x.version}` }catch(e){document.querySelector('#backupTest').textContent='FAIL: '+e.message}}
function settings(){const s=state.settings;return `${pageHead('Configuration','Settings','Core operation is offline. Tokens are optional and stored only in this browser profile.')}<section class="panel pad"><div class="formgrid"><label>Project owner<input id="setOwner" value="${esc(s.owner)}"></label><label>Repository<input id="setRepo" value="${esc(s.githubRepo)}"></label><label>Current branch<input id="setBranch" value="${esc(state.project.branch)}"></label><label>Current commit<input id="setCommit" value="${esc(state.project.commit)}"></label><label>Phase<input id="setPhase" value="${esc(state.project.phase)}"></label><label>Work package<input id="setWP" value="${esc(state.project.workPackage)}"></label><label>Progress<input id="setProgress" type="number" min="0" max="100" value="${state.project.progress}"></label><label>Risk<select id="setRisk"><option ${state.project.risk==='low'?'selected':''}>low</option><option ${state.project.risk==='medium'?'selected':''}>medium</option><option ${state.project.risk==='high'?'selected':''}>high</option></select></label></div><label>Next action<textarea id="setNext">${esc(state.project.nextDecision)}</textarea></label><label class="check"><input id="setAuto" type="checkbox" ${s.autosnapshot?'checked':''}> Automatic hourly local checkpoints</label><div class="toolbar"><button class="primary" onclick="saveSettings()">Save settings</button><button class="danger" onclick="resetAll()">Erase all local data</button></div></section>`}
function saveSettings(){state.settings.owner=document.querySelector('#setOwner').value;state.settings.githubRepo=document.querySelector('#setRepo').value;state.settings.autosnapshot=document.querySelector('#setAuto').checked;state.project.branch=document.querySelector('#setBranch').value;state.project.commit=document.querySelector('#setCommit').value;state.project.phase=document.querySelector('#setPhase').value;state.project.workPackage=document.querySelector('#setWP').value;state.project.progress=Math.max(0,Math.min(100,Number(document.querySelector('#setProgress').value)));state.project.risk=document.querySelector('#setRisk').value;state.project.nextDecision=document.querySelector('#setNext').value;save();render();toast('Settings saved')}
function genericList(key,head,desc,type,extra=''){return `${pageHead('Operations',head,desc,`${extra}<button class="primary" onclick="openForm('${type}')">Add record</button>`)}<section class="panel pad">${state[key].length?state[key].map(x=>entryCard(x,key)).join(''):'<div class="empty">No records yet.</div>'}</section>`}
function entryCard(x,key){const name=x.title||x.name||'Untitled',status=x.status||x.type||x.category||'',text=x.summary||x.detail||x.description||x.body||x.notes||x.text||x.task||'';let actions='';if(key==='approvals')actions=`<button class="primary small" onclick="setStatus('approvals',${x.id},'approved')">Approve</button><button class="danger small" onclick="setStatus('approvals',${x.id},'denied')">Deny</button>`;if(key==='sessions')actions=`<button class="secondary small" onclick='copyText(${JSON.stringify(`Resume ${name}. Checkpoint: ${text}. Continue from the first incomplete step without repeating completed work.`)})'>Resume</button>`;return `<div class="item"><div class="row"><div><b>${esc(name)}</b>${text?`<p>${esc(String(text).slice(0,420))}</p>`:''}</div>${status?badge(status):''}</div>${actions?`<div class="toolbar">${actions}</div>`:''}<button class="delete" onclick="removeRecord('${key}',${x.id})">Remove</button></div>`}
function removeRecord(k,id){if(confirm('Remove this local record?')){state[k]=state[k].filter(x=>x.id!==id);save();render()}} function setStatus(k,id,s){const x=state[k].find(x=>x.id===id);if(x)x.status=s;save();render()}
function toolPage(head,desc,button,mode){return `${pageHead('Local tool',head,desc)}<section class="panel pad"><textarea id="toolInput" placeholder="Paste content here"></textarea><button class="primary" onclick="runTool('${mode}')">${button}</button><div id="toolOut" class="code">Output appears here.</div></section>`}
function runTool(mode){const t=document.querySelector('#toolInput').value;let o='';if(mode==='compress'){const l=t.split(/\n+/).map(x=>x.trim()).filter(Boolean);o=`MISSION: ${l[0]||'Not stated'}\n\nCURRENT STATE: ${l.slice(1,5).join(' ')}\n\nOPEN ITEMS: ${l.filter(x=>/todo|pending|next|block|remain/i.test(x)).slice(0,8).join(' ')}\n\nSOURCE POINTERS: Preserve full source outside this packet.`}else{const req=['cost','target','duration','range','effect','timing','failure'],m=req.filter(x=>!t.toLowerCase().includes(x)),amb=(t.match(/\b(may|might|usually|reasonable|appropriate|some|often)\b/gi)||[]);o=(m.length?`Potential missing fields: ${m.join(', ')}\n`:'Core fields present.\n')+(amb.length?`Ambiguous terms: ${[...new Set(amb)].join(', ')}\n`:'No obvious ambiguity terms.\n')+'Balance and canonical-authority review still required.'}document.querySelector('#toolOut').textContent=o}
const formDefs={
 agent:['name','role','status','task','capacity:number','quality:number'],approval:['title','detail','status'],alert:['title','detail','status','severity'],decision:['title','status','reason:textarea','alternatives:textarea','affected:textarea','authority'],prompt:['title','category','body:textarea'],session:['title','agent','status','summary:textarea','pending:textarea'],artifact:['title','type','location','notes:textarea','checksum'],note:['title','kind','body:textarea'],knowledge:['title','type','tags','links:textarea','summary:textarea'],doc:['title','type','status','owner','source','summary:textarea'],dependency:['from','to','type','notes:textarea'],release:['title','version','date:date','status','summary:textarea','changes:textarea'],migration:['title','type','status','scope:textarea','steps:textarea','rollback:textarea'],timeline:['title','status','date:date','progress:number','dependsOn'],calendar:['title','date:date','time:time','notes:textarea'],credit:['label','amount:number'],
 worlds:authorConfig.worlds[1].split(','),worldtimeline:authorConfig.worldtimeline[1].split(','),abilities:authorConfig.abilities[1].split(','),creatures:authorConfig.creatures[1].split(','),species:authorConfig.species[1].split(','),items:authorConfig.items[1].split(','),vehicles:authorConfig.vehicles[1].split(','),quests:authorConfig.quests[1].split(','),dialogue:authorConfig.dialogue[1].split(','),storyflow:authorConfig.storyflow[1].split(','),relationships:authorConfig.relationships[1].split(',')};
function openForm(type){modal={type};render()}
function modalHtml(){
  const t=modal.type, fields=formDefs[t]||['title'];
  const inputs=fields.map(spec=>{
    const parts=spec.split(':'), f=parts[0], kind=parts[1]||'text';
    const control=kind==='textarea' ? `<textarea name="${f}"></textarea>` : `<input name="${f}" type="${kind}">`;
    return `<label>${esc(f)}${control}</label>`;
  }).join('');
  return `<div class="modal" onclick="if(event.target===this){modal=null;render()}"><div class="modalbox"><div class="row"><h2>Add ${esc(t)}</h2><button class="iconbtn" onclick="modal=null;render()">✕</button></div><form onsubmit="submitForm(event,'${t}')" class="stack">${inputs}<button class="primary">Save</button></form></div></div>`;
}
function submitForm(e,t){e.preventDefault();const o={id:uid(),created:now(),...Object.fromEntries(new FormData(e.target).entries())};for(const k in o)if(formDefs[t]?.includes(k+':number'))o[k]=Number(o[k]||0);if(t==='credit'){state.credits.entries.unshift(o);state.credits.used+=o.amount}else{const map={agent:'agents',approval:'approvals',alert:'alerts',decision:'decisions',prompt:'prompts',session:'sessions',artifact:'artifacts',note:'notes',knowledge:'knowledge',doc:'docs',dependency:'dependencies',release:'releases',migration:'migrations',timeline:'timeline',calendar:'calendar'};const k=map[t]||t;if((t==='approval'||t==='alert')&&!o.status)o.status='pending';state[k].unshift(o)}save();modal=null;render();toast('Saved')}
function editBudget(){const n=Number(prompt('Credit budget',state.credits.budget));if(n>0){state.credits.budget=n;save();render()}}
function copyText(t){navigator.clipboard?.writeText(t);toast('Copied')} function download(name,text,type='application/json'){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportData(){download(`multiversal-aioc-${today()}.json`,JSON.stringify(state,null,2))}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=merge(clone(defaults),JSON.parse(r.result));save(true);render();toast('Backup imported')}catch{alert('Invalid backup')}};r.readAsText(f)}
function resetAll(){if(confirm('Erase every AIOC record stored in this browser?')){localStorage.removeItem('aioc-state');state=clone(defaults);view='dashboard';render()}}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
