(()=>{'use strict';
const URL='./canonical-schema-registry.json';let registry=null;
const isObj=v=>v&&typeof v==='object'&&!Array.isArray(v);
async function load(){if(registry)return registry;const r=await fetch(URL,{cache:'no-store'});if(!r.ok)throw new Error(`Schema registry unavailable (${r.status})`);registry=await r.json();return registry}
function stableId(v){return typeof v==='string'&&/^[a-z0-9]+(?:[._-][a-z0-9]+)+$/i.test(v)}
function semver(v){return typeof v==='string'&&/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(v)}
function typeFor(obj,reg){const raw=obj.objectType||obj.objectKind||obj.recordType||'';if(reg.objects.some(x=>x.objectId===raw))return raw;const key=String(obj.builderType||obj.authoringType||raw).toLowerCase();const map=reg.builderMappings[key];return map?.[0]||null}
function normalize(obj,opts={}){const now=new Date().toISOString(),o=structuredClone?structuredClone(obj):JSON.parse(JSON.stringify(obj));const type=opts.objectType||typeFor(o,registry||{objects:[],builderMappings:{}})||o.objectType||'mv.object.base-definition';o.id=o.id||`mv.user.${String(o.name||'object').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}.${Date.now()}`;o.objectType=type;o.recordLayer=String(o.recordLayer||o.layer||'definition').toLowerCase().replace('live instance','live_instance');o.schemaVersion=o.schemaVersion||'0.1.0';o.contentVersion=o.contentVersion||'0.1.0';o.name=o.name||o.title||'Untitled';o.status=o.status||'draft';o.canonStatus=o.canonStatus||'provisional';o.createdAt=o.createdAt||now;o.updatedAt=now;o.spec=isObj(o.spec)?o.spec:{};o.dependencies=Array.isArray(o.dependencies)?o.dependencies.map(d=>typeof d==='string'?{id:d}:d):[];o.provenance=isObj(o.provenance)?o.provenance:{sourceRefs:[{type:'authoring',label:'AIOC authoring'}],conversionNotes:'Created or normalized by Multiversal AIOC'};return o}
async function validate(input,opts={}){const reg=await load(),o=opts.normalize?normalize(input,opts):input,issues=[];const add=(severity,path,message,code)=>issues.push({severity,path,message,code});if(!isObj(o))return {valid:false,issues:[{severity:'error',path:'$',message:'Record must be an object',code:'record.type'}]};for(const f of reg.baseRequired)if(o[f]===undefined||o[f]===null||o[f]==='')add('error',f,`Required canonical field is missing: ${f}`,'required');if(o.id&&!stableId(o.id))add('error','id','Stable ID must use dot/dash/underscore-separated identifier segments.','stable-id');if(o.objectType&&!reg.objects.some(x=>x.objectId===o.objectType))add('error','objectType',`Unknown canonical object type: ${o.objectType}`,'object-type');if(o.contentVersion&&!semver(o.contentVersion))add('error','contentVersion','Content version must be semantic versioning.','semver');if(o.schemaVersion&&typeof o.schemaVersion!=='string')add('error','schemaVersion','Schema version must be a string.','schema-version');if(o.status&&!reg.baseStatuses.includes(o.status))add('error','status',`Status must be one of: ${reg.baseStatuses.join(', ')}`,'status');if(o.canonStatus&&!reg.canonStatuses.includes(o.canonStatus))add('error','canonStatus',`Canon status must be one of: ${reg.canonStatuses.join(', ')}`,'canon-status');if(o.recordLayer==='variant'&&!o.baseDefinitionId&&!o.baseDefinitionRef)add('error','baseDefinitionId','Variants require a base Definition reference.','variant-base');if(['definition','variant'].includes(o.recordLayer)&&!isObj(o.provenance))add('error','provenance','Definitions and variants require provenance.','provenance');const def=reg.objects.find(x=>x.objectId===o.objectType);if(def){if(!def.layers.includes(o.recordLayer))add('error','recordLayer',`${o.objectType} does not permit layer ${o.recordLayer}. Allowed: ${def.layers.join(', ')}`,'layer');for(const f of def.specRequired||[])if(o.spec?.[f]===undefined)add('error',`spec.${f}`,`Required domain field is missing: ${f}`,'spec-required')}if(Array.isArray(o.dependencies)){o.dependencies.forEach((d,i)=>{const id=typeof d==='string'?d:d?.id;if(!id||!stableId(id))add('error',`dependencies[${i}]`,'Dependency must contain a canonical stable ID.','dependency')})}return {valid:!issues.some(x=>x.severity==='error'),issues,normalized:o,schema:def||null,registryVersion:reg.version,authorityStatus:reg.authorityStatus}}
async function validatePack(pack){const state=window.AIOCData?.load?.()||{},objects=pack?.objects||state.gameObjects||[],results=await Promise.all(objects.map(o=>validate(o))),ids=new Set(),issues=[];for(let i=0;i<objects.length;i++){const id=objects[i]?.id;if(ids.has(id))issues.push({severity:'error',path:`objects[${i}].id`,message:`Duplicate stable ID: ${id}`,code:'duplicate'});ids.add(id);issues.push(...results[i].issues.map(x=>({...x,path:`objects[${i}].${x.path}`})))}for(const o of objects)for(const d of o.dependencies||[]){const id=typeof d==='string'?d:d.id;if(id&&!ids.has(id))issues.push({severity:'error',path:`${o.id}.dependencies`,message:`Dependency closure failure: ${id} is not in this pack.`,code:'closure'})}return {valid:!issues.some(x=>x.severity==='error'),issues,objectResults:results,registryVersion:(await load()).version}}
window.MultiversalSchema={load,validate,validatePack,normalize,get registry(){return registry}};
})();
