(()=>{'use strict';
const D=()=>window.AIOCData;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const collections={gameObjects:'Game Object',authoringEntries:'Authoring Entry',packLists:'Pack List',featureModules:'Feature Module',testPlans:'Test Plan',testSessions:'Test Session',testFindings:'Finding',agents:'Agent',decisions:'Decision',alerts:'Alert',approvals:'Approval',artifacts:'Artifact',tasks:'Task',sessions:'Session',notes:'Note',knowledge:'Knowledge'};
function state(){return D()?.load?.()||JSON.parse(localStorage.getItem('aioc-state')||'{}')}
function records(s=state()){return Object.entries(collections).flatMap(([k,label])=>(Array.isArray(s[k])?s[k]:[]).map((r,i)=>({collection:k,label,index:i,id:r.id||`${k}-${i}`,name:r.name||r.title||r.id||`${label} ${i+1}`,record:r})))}
function search(q=''){const words=q.toLowerCase().split(/\s+/).filter(Boolean);return records().map(x=>{const hay=JSON.stringify(x.record).toLowerCase();return {...x,score:words.reduce((n,w)=>n+(x.name.toLowerCase().includes(w)?5:0)+(hay.includes(w)?1:0),0)}}).filter(x=>!words.length||x.score).sort((a,b)=>b.score-a.score).slice(0,100)}
function ensure(){if(document.querySelector('#mvConsolidation'))return;document.body.insertAdjacentHTML('beforeend',`<button id="mvControlBtn" aria-label="Open project control">⌘ CONTROL</button><div id="mvConsolidation"><section class="mvc-shell"><header><b>MULTIVERSAL PROJECT CONTROL</b><button data-close>✕</button></header><nav><button data-tab="search">Search</button><button data-tab="health">Health</button><button data-tab="pipeline">Pipeline</button><button data-tab="access">Accessibility</button></nav><main id="mvcBody"></main></section></div>`);document.querySelector('#mvControlBtn').onclick=()=>open('search');document.querySelector('[data-close]').onclick=close;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>open(b.dataset.tab));applyAccess();}
function open(tab){document.querySelector('#mvConsolidation').classList.add('open');({search:renderSearch,health:renderHealth,pipeline:renderPipeline,access:renderAccess}[tab]||renderSearch)()}
function close(){document.querySelector('#mvConsolidation').classList.remove('open')}
function renderSearch(){const body=document.querySelector('#mvcBody');body.innerHTML=`<div class="mvc-head"><h2>Global Search & Inspector</h2><input id="mvcSearch" placeholder="Search objects, tests, decisions, modules, packs…"></div><div class="mvc-grid"><div id="mvcResults"></div><article id="mvcInspector" class="mvc-card"><p>Select a record.</p></article></div>`;const input=document.querySelector('#mvcSearch');input.oninput=()=>showResults(input.value);showResults('')}
function showResults(q){document.querySelector('#mvcResults').innerHTML=search(q).map(x=>`<button class="mvc-result" data-c="${x.collection}" data-i="${x.index}"><b>${esc(x.name)}</b><small>${x.label}</small></button>`).join('')||'<p>No matches.</p>';document.querySelectorAll('.mvc-result').forEach(b=>b.onclick=()=>inspect(b.dataset.c,Number(b.dataset.i)))}
function inspect(c,i){const s=state(),r=s[c]?.[i];if(!r)return;const id=r.id||'',deps=[...(r.dependencies||[]),...(r.baseDefinitionRef?[r.baseDefinitionRef]:[])];const inbound=(s.gameObjects||[]).filter(o=>(o.dependencies||[]).includes(id)||o.baseDefinitionRef===id);const packed=(s.packLists||[]).filter(p=>(p.objectIds||[]).includes(id));const balance=r.extensions?.['app.multiversal.aioc']?.balanceReport;const tests=(s.testPlans||[]).filter(t=>t.subjectId===id);document.querySelector('#mvcInspector').innerHTML=`<h2>${esc(r.name||r.title||id||collections[c])}</h2><div class="mvc-tabs"><span>${esc(collections[c])}</span><span>${esc(id||'No stable ID')}</span></div><h3>Overview</h3><pre>${esc(JSON.stringify(r,null,2))}</pre><h3>Connections</h3><p>${deps.length} outgoing · ${inbound.length} incoming · ${packed.length} packs</p><h3>Evidence</h3><p>${balance?'Balance report attached':'No balance report'} · ${tests.length} test plans</p><div class="mvc-actions"><button onclick="window.MVControl.edit('${c}',${i})">Edit</button><button onclick="window.MVControl.history('${c}',${i})">History</button></div>`}
function edit(c,i){const s=state(),r=s[c]?.[i];if(!r)return;const box=document.querySelector('#mvcInspector');box.innerHTML=`<h2>Edit ${esc(collections[c])}</h2><label>Name/title<input id="mveName" value="${esc(r.name||r.title||'')}"></label><label>Status<input id="mveStatus" value="${esc(r.status||r.canonStatus||'')}"></label><label>Notes<textarea id="mveNotes">${esc(r.notes||r.description||'')}</textarea></label><div class="mvc-actions"><button id="mveSave">Save with history</button><button onclick="window.MVControl.inspect('${c}',${i})">Cancel</button></div>`;document.querySelector('#mveSave').onclick=()=>D().update(s2=>{const target=s2[c][i];target.name=document.querySelector('#mveName').value||target.name;target.title=target.title!==undefined?document.querySelector('#mveName').value:target.title;if(document.querySelector('#mveStatus').value){if(target.canonStatus!==undefined)target.canonStatus=document.querySelector('#mveStatus').value;else target.status=document.querySelector('#mveStatus').value}target.notes=document.querySelector('#mveNotes').value;target.updatedAt=new Date().toISOString();target.history=Array.isArray(target.history)?target.history:[];target.history.unshift({at:target.updatedAt,event:'edited-in-project-control'});},{reason:`edit-${c}`,backup:true});inspect(c,i)}
function history(c,i){const r=state()[c]?.[i];document.querySelector('#mvcInspector').innerHTML=`<h2>History</h2>${(r?.history||[]).map(h=>`<div class="mvc-card"><b>${esc(h.event||h.reason||'Change')}</b><small>${esc(h.at||'')}</small></div>`).join('')||'<p>No object-level history yet. Global changes remain in the audit log.</p>'}`}
function healthData(){const s=state(),objects=s.gameObjects||[],findings=s.testFindings||[];const unresolved=objects.filter(o=>!o.id||!o.name||!o.spec||!o.provenance?.source);const unbalanced=objects.filter(o=>!o.extensions?.['app.multiversal.aioc']?.balanceReport);const untested=objects.filter(o=>!(s.testPlans||[]).some(t=>t.subjectId===o.id));const critical=findings.filter(f=>['critical','blocker'].includes(String(f.severity).toLowerCase())&&!['closed','resolved'].includes(String(f.status).toLowerCase()));return {s,objects,unresolved,unbalanced,untested,critical}}
function renderHealth(){const {s,objects,unresolved,unbalanced,untested,critical}=healthData();const mods=s.featureModules||[];document.querySelector('#mvcBody').innerHTML=`<h2>Project Health</h2><div class="mvc-metrics"><div><b>${objects.length}</b><span>Objects</span></div><div><b>${unresolved.length}</b><span>Need structure</span></div><div><b>${unbalanced.length}</b><span>Need balance</span></div><div><b>${untested.length}</b><span>Need tests</span></div><div><b>${critical.length}</b><span>Critical findings</span></div></div><h3>Evidence-derived module readiness</h3>${mods.map(m=>{const ev=moduleEvidence(m,s);return `<div class="mvc-row"><div><b>${esc(m.name||m.title||m.id)}</b><small>${ev.summary}</small></div><strong>${ev.score}%</strong></div>`}).join('')||'<p>No feature modules.</p>'}`}
function moduleEvidence(m,s){let n=0,total=7;const text=JSON.stringify(m).toLowerCase();if(text.includes('design'))n++;if(text.includes('rule'))n++;if(text.includes('schema')||text.includes('data'))n++;if(text.includes('ui')||text.includes('ux'))n++;if(Number(m.progress?.implementation||m.implementation||0)>0)n++;if((s.testPlans||[]).some(t=>t.moduleId===m.id||t.subjectId===m.id))n++;if(Array.isArray(m.dependencies))n++;return {score:Math.round(n/total*100),summary:`${n}/${total} evidence gates present`}}
function pipelineStage(o,s){if(o.canonStatus==='released')return'released';if(o.canonStatus==='approved')return'approved';if((s.testPlans||[]).some(t=>t.subjectId===o.id))return'testing';if(o.extensions?.['app.multiversal.aioc']?.balanceReport)return'balance';if(o.validation?.status==='ready')return'expert-review';return o.id?'draft':'concept'}
function renderPipeline(){const s=state(),stages=['concept','draft','expert-review','balance','testing','approved','released'];document.querySelector('#mvcBody').innerHTML=`<h2>Connected Content Pipeline</h2><p>Stages are derived from structure, review, balance evidence, tests, approval and release state.</p><div class="mvc-board">${stages.map(st=>`<section><h3>${st}</h3>${(s.gameObjects||[]).filter(o=>pipelineStage(o,s)===st).map(o=>`<div class="mvc-card"><b>${esc(o.name||o.id)}</b><small>${esc(o.id)}</small></div>`).join('')}</section>`).join('')}</div>`}
function accessSettings(){const s=state();s.settings=s.settings||{};s.settings.accessibility=s.settings.accessibility||{theme:'neon',glow:'normal',fontScale:100,reducedMotion:false,highContrast:false};return s.settings.accessibility}
function renderAccess(){const a=accessSettings();document.querySelector('#mvcBody').innerHTML=`<h2>Accessibility & Display</h2><label>Visual mode<select id="mvaTheme"><option value="neon">Multiversal Neon</option><option value="low-glow">Low Glow</option><option value="high-contrast">High Contrast</option></select></label><label>Font size <input id="mvaFont" type="range" min="90" max="140" value="${a.fontScale||100}"><span id="mvaFontOut">${a.fontScale||100}%</span></label><label class="mvc-check"><input id="mvaMotion" type="checkbox" ${a.reducedMotion?'checked':''}> Reduced motion</label><button id="mvaApply">Apply and save</button>`;document.querySelector('#mvaTheme').value=a.theme||'neon';document.querySelector('#mvaFont').oninput=e=>document.querySelector('#mvaFontOut').textContent=e.target.value+'%';document.querySelector('#mvaApply').onclick=()=>D().update(s=>{s.settings=s.settings||{};s.settings.accessibility={theme:document.querySelector('#mvaTheme').value,fontScale:Number(document.querySelector('#mvaFont').value),reducedMotion:document.querySelector('#mvaMotion').checked};},{reason:'accessibility-settings'}),applyAccess()}
function applyAccess(){const a=accessSettings();document.documentElement.dataset.mvTheme=a.theme||'neon';document.documentElement.classList.toggle('mv-reduced-motion',!!a.reducedMotion);document.documentElement.style.fontSize=(a.fontScale||100)+'%'}
function workflow(){if(!D())return;D().on('state-changed',()=>{try{const s=state();let changed=false;(s.gameObjects||[]).forEach(o=>{o.provenance=o.provenance||{};if(!o.provenance.source){o.provenance.source='AIOC authoring';changed=true}o.provenance.createdBy=o.provenance.createdBy||s.settings?.owner||'Project owner';o.provenance.schemaVersion=o.provenance.schemaVersion||s.schemaRegistry?.version||'candidate';});if(changed)D().save(s,{reason:'provenance-normalization',silent:true})}catch(e){console.error(e)}})}
window.MVControl={open,close,inspect,edit,history,search};window.addEventListener('DOMContentLoaded',()=>{ensure();workflow()});})();