(() => {
'use strict';
const VERSION='11.1';
const LABELS={worlds:'Worlds & Settings',worldtimeline:'World Timelines',abilities:'Abilities & Trees',creatures:'Creatures & NPCs',species:'Species',items:'Items',vehicles:'Vehicles, Mecha & Ships',quests:'Quests & Adventures',dialogue:'Dialogue',storyflow:'Story Flow',relationships:'Relationships'};
const ICONS={worlds:'◉',worldtimeline:'⌛',abilities:'✦',creatures:'◆',species:'◌',items:'⬡',vehicles:'▰',quests:'◇',dialogue:'❝',storyflow:'⌁',relationships:'∞'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function readState(){try{return JSON.parse(localStorage.getItem('aioc-state')||'{}')}catch{return {}}}
function writeState(s){localStorage.setItem('aioc-state',JSON.stringify(s))}
function objects(){const s=readState();return Array.isArray(s.gameObjects)?s.gameObjects:[]}
function packs(){const s=readState();return Array.isArray(s.packLists)?s.packLists:[]}
function typeOf(o){const k=String(o.objectKind||o.objectType||o.id||'').toLowerCase();for(const t of Object.keys(LABELS)){const root=t.replace(/s$/,'');if(k.includes(root))return t}return 'other'}
function review(o){let score=100;const issues=[];if(!o.id){score-=30;issues.push('Missing stable ID')}if(!o.name){score-=20;issues.push('Missing name')}if(!o.objectKind){score-=10;issues.push('Missing object kind')}if(!o.layer){score-=10;issues.push('Missing record layer')}if(!o.spec){score-=20;issues.push('Missing domain spec')}if(!o.provenance?.source){score-=10;issues.push('Missing provenance')}if(o.layer==='Variant'&&!o.baseDefinitionRef){score-=30;issues.push('Variant missing base Definition')}const unresolved=(o.dependencies||[]).filter(d=>!objects().some(x=>x.id===d));if(unresolved.length){score-=Math.min(30,unresolved.length*5);issues.push(`${unresolved.length} unresolved dependencies`)}score=Math.max(0,score);return {score,status:score>=75?'ready':score>=45?'review':'blocked',issues}}
function open(html){document.querySelector('#mvstudio')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="mvstudio">${html}</div>`);document.body.style.overflow='hidden'}
function close(){document.querySelector('#mvstudio')?.remove();document.body.style.overflow=''}
function shell(title,body,back='DesignStudio11.home()'){return `<header><button onclick="${back}">←</button><div><small>Multiversal Design Studio · ${VERSION}</small><h2>${esc(title)}</h2></div><span style="flex:1"></span><button onclick="DesignStudio11.close()">✕</button></header><main>${body}</main>`}
function home(){const all=objects(),ps=packs(),packed=new Set(ps.flatMap(p=>p.objectIds||[])),alerts=all.filter(o=>review(o).score<75).length;open(shell('Design command center',`<section class="mvs-hero"><h1>What are you designing today?</h1><p>Create, expand, improve, vary, analyze, and stage Multiversal content from one place.</p><button class="mvs-primary" onclick="DesignStudio11.chooseIntent()">Start design work</button></section><section class="mvs-grid"><article class="mvs-card"><h3>Design Inbox</h3><p>${alerts} objects need review.</p><button onclick="DesignStudio11.inbox()">Open inbox</button></article><article class="mvs-card"><h3>Project Health</h3><p>${all.length} game objects across ${new Set(all.map(typeOf).filter(x=>x!=='other')).size} domains.</p><button onclick="DesignStudio11.health()">View health</button></article><article class="mvs-card"><h3>Pack Workspace</h3><p>${ps.length} Pack Lists · ${all.filter(o=>!packed.has(o.id)).length} unstaged objects.</p><button onclick="DesignStudio11.packWorkspace()">Open packs</button></article></section><h3>Content domains</h3><section class="mvs-grid">${Object.keys(LABELS).map(t=>`<article class="mvs-card"><h3>${ICONS[t]} ${esc(LABELS[t])}</h3><small>${all.filter(o=>typeOf(o)===t).length} objects</small><button onclick="DesignStudio11.domain('${t}')">Open domain</button></article>`).join('')}</section>`))}
function chooseIntent(type=''){open(shell('Choose your design approach',`<section class="mvs-hero"><h1>${type?esc(LABELS[type]):'How would you like to work?'}</h1></section><div class="mvs-modes"><button class="mvs-mode" onclick="DesignStudio11.create('${type}')"><b>Create</b><span>Make something new.</span></button><button class="mvs-mode" onclick="DesignStudio11.pick('analyze','${type}')"><b>Analyze</b><span>Inspect structure, dependencies, and readiness.</span></button><button class="mvs-mode" onclick="DesignStudio11.pick('improve','${type}')"><b>Improve</b><span>Review an existing object.</span></button><button class="mvs-mode" onclick="DesignStudio11.pick('variant','${type}')"><b>Variant</b><span>Create a governed derivative.</span></button></div>`))}
function create(type){if(!type)return chooseDomain();close();setTimeout(()=>window.ForgeV2?.start(type),50)}
function chooseDomain(){open(shell('Choose a content domain',`<div class="mvs-grid">${Object.keys(LABELS).map(t=>`<article class="mvs-card"><h3>${ICONS[t]} ${esc(LABELS[t])}</h3><button class="mvs-primary" onclick="DesignStudio11.create('${t}')">Create</button></article>`).join('')}</div>`,'DesignStudio11.chooseIntent()'))}
function pick(mode,type=''){let list=objects();if(type)list=list.filter(o=>typeOf(o)===type);open(shell(`${mode==='variant'?'Create variant from':mode==='improve'?'Improve':'Analyze'} existing content`,`<div class="mvs-list">${list.length?list.map(o=>`<button class="mvs-row" onclick="DesignStudio11.object('${mode}','${esc(o.id)}')"><span>${ICONS[typeOf(o)]||'□'}</span><span class="grow"><b>${esc(o.name||o.id)}</b><small>${esc(o.id)}</small></span></button>`).join(''):'<div class="mvs-empty">No game objects yet.</div>'}</div>`,'DesignStudio11.chooseIntent()'))}
function object(mode,id){const o=objects().find(x=>x.id===id);if(!o)return;if(mode==='variant')return variant(o);const r=review(o);open(shell(`${mode==='improve'?'Improve':'Analyze'}: ${o.name||o.id}`,`<section class="mvs-hero"><h1>${esc(o.name||o.id)}</h1><p>${esc(o.id)}</p></section><article class="mvs-card"><h3>Design health: ${r.score}%</h3><progress max="100" value="${r.score}"></progress>${r.issues.length?r.issues.map(x=>`<p>⚠ ${esc(x)}</p>`).join(''):'<p>✓ No structural issues found.</p>'}</article><article class="mvs-card"><h3>Dependencies</h3>${(o.dependencies||[]).length?(o.dependencies||[]).map(x=>`<p>${esc(x)}</p>`).join(''):'<p>No declared dependencies.</p>'}</article>`,'DesignStudio11.pick("'+mode+'")'))}
function variant(o){const concept=prompt(`Describe what differs from ${o.name||o.id}:`);if(!concept)return;const name=prompt('Variant name',`${o.name||'Object'} Variant`);if(!name)return;const s=readState();s.gameObjects=s.gameObjects||[];const id=`${o.id}.variant.${name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`;s.gameObjects.push({$schema:'mv.variant/1.0.0',id,objectKind:o.objectKind,layer:'Variant',schemaVersion:'1.0.0',version:'0.1.0',name,canonStatus:'draft',baseDefinitionRef:o.id,dependencies:[o.id],provenance:{source:`Variant of ${o.id}`,createdIn:`Design Studio ${VERSION}`,createdAt:new Date().toISOString()},spec:{overrides:{designerConcept:concept}}});writeState(s);home()}
function domain(type){const list=objects().filter(o=>typeOf(o)===type);open(shell(LABELS[type],`<section class="mvs-hero"><h1>${ICONS[type]} ${esc(LABELS[type])}</h1><button class="mvs-primary" onclick="DesignStudio11.chooseIntent('${type}')">Start work</button></section><div class="mvs-list">${list.map(o=>`<button class="mvs-row" onclick="DesignStudio11.object('analyze','${esc(o.id)}')"><span class="grow"><b>${esc(o.name||o.id)}</b><small>${esc(o.id)}</small></span></button>`).join('')||'<div class="mvs-empty">No objects in this domain.</div>'}</div>`))}
function health(){const all=objects();open(shell('Project health',`<div class="mvs-health">${Object.keys(LABELS).map(t=>{const os=all.filter(o=>typeOf(o)===t),ready=os.filter(o=>review(o).score>=75).length,pct=os.length?Math.round(ready/os.length*100):0;return `<article class="mvs-card"><b>${esc(LABELS[t])}</b><span>${pct}% ready</span><progress max="100" value="${pct}"></progress><small>${ready} ready of ${os.length}</small></article>`}).join('')}</div>`))}
function inbox(){const rows=objects().map(o=>({o,r:review(o)})).filter(x=>x.r.score<75);open(shell('Design Inbox',`<div class="mvs-list">${rows.length?rows.map(x=>`<button class="mvs-row" onclick="DesignStudio11.object('analyze','${esc(x.o.id)}')"><span>⚠</span><span class="grow"><b>${esc(x.o.name||x.o.id)}</b><small>${esc(x.r.issues.join(' · '))}</small></span></button>`).join(''):'<div class="mvs-empty">No current design alerts.</div>'}</div>`))}
function packWorkspace(){const all=objects();open(shell('Pack Workspace',`<div class="mvs-grid">${packs().map(p=>`<article class="mvs-card"><h3>${esc(p.name)}</h3><p>${(p.objectIds||[]).length} objects</p></article>`).join('')||'<div class="mvs-empty">No Pack Lists yet.</div>'}</div><h3>Unstaged objects</h3><div class="mvs-list">${all.filter(o=>!packs().some(p=>(p.objectIds||[]).includes(o.id))).map(o=>`<div class="mvs-row"><span class="grow"><b>${esc(o.name||o.id)}</b><small>${esc(o.id)}</small></span></div>`).join('')}</div>`))}
function init(){if(!document.querySelector('.mvs-floating')){const b=document.createElement('button');b.className='mvs-floating';b.type='button';b.textContent='Design Studio';b.setAttribute('aria-label','Open Multiversal Design Studio');b.onclick=home;document.body.appendChild(b)}window.DesignStudio11={home,close,chooseIntent,create,chooseDomain,pick,object,variant,domain,health,inbox,packWorkspace}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
new MutationObserver(init).observe(document.documentElement,{childList:true,subtree:true});
})();