const BUILD="2.1.0-migration-control";
const ROUTES=[
  ["dashboard","Developer Dashboard","Project status, priorities, risks, and migration progress"],
  ["migration","Migration Center","All ten rebuild steps and every legacy feature"],
  ["library","Content Library","Canonical object explorer"],
  ["workbench","Object Workbench","Inspect mechanics, provenance, and history"],
  ["graph","Knowledge Graph","Dependencies and incoming references"],
  ["intelligence","Development Intelligence","Coverage, gaps, and consistency"],
  ["assets","Asset Manager","Object-linked media and references"],
  ["pipeline","Content Pipeline","Development stages and release readiness"],
  ["authoring","Authoring Studio","All game-content builders and structured editors"],
  ["packs","Pack Manager","Pack Lists, validation, dependencies, and compilation"],
  ["balance","Balance Lab","Mathematical review and simulation"],
  ["testing","Game Testing","Plans, sessions, findings, and regressions"],
  ["modules","Feature Modules","Internal-alpha feature progress and dependencies"],
  ["devos","Development OS","Work packages, decisions, agents, and release control"],
  ["settings","Settings","Accessibility, data, and display controls"],
  ["diagnostics","Diagnostics","Build, database, and storage health"]
];
const PIPELINE=["Imported","Draft","Review","Balance","Testing","Approved","Released"];
const LEGACY={authoring:"../aioc-core.html",packs:"../aioc-core.html",balance:"../balance.html",testing:"../testing-suite.html",modules:"../feature-modules.html",devos:"../development-os.html"};
const state={records:[],filtered:[],selected:null,route:"dashboard",overrides:{},assets:[],modules:[],tests:[],decisions:[],migration:null,loadedAt:null,loadError:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function loadLocal(){try{const x=JSON.parse(localStorage.getItem("mv-aioc-v2")||"{}");state.overrides=x.overrides||{};state.assets=x.assets||[];state.modules=x.modules||[];state.tests=x.tests||[];state.decisions=x.decisions||[]}catch{}}
function saveLocal(){localStorage.setItem("mv-aioc-v2",JSON.stringify({overrides:state.overrides,assets:state.assets,modules:state.modules,tests:state.tests,decisions:state.decisions,updatedAt:new Date().toISOString()}))}
function normalized(r){const o=state.overrides[r.id]||{};return{...r,stage:o.stage||r.stage||"Imported",notes:o.notes||r.notes||"",tags:o.tags||r.tags||[],dependencies:r.dependencies||[],gameObject:r.gameObject||null}}
function score(r){let n=0,total=8;if(r.id)n++;if(r.name)n++;if(r.objectType)n++;if(r.provenance)n++;if(r.gameObject)n++;if((r.dependencies||[]).length)n++;if(state.assets.some(a=>a.objectId===r.id))n++;if(["Approved","Released"].includes(r.stage))n++;return Math.round(n/total*100)}
function nav(){const n=$("#nav");n.innerHTML=ROUTES.map(([id,name])=>`<button class="nav-btn ${state.route===id?"active":""}" data-route="${id}">${name}</button>`).join("");n.querySelectorAll("button").forEach(b=>b.onclick=()=>route(b.dataset.route))}
function route(id){state.route=id;const r=ROUTES.find(x=>x[0]===id)||ROUTES[0];$("#pageTitle").textContent=r[1];$("#pageSubtitle").textContent=r[2];nav();render();document.querySelector(".sidebar").classList.remove("open")}
function metrics(){const full=state.records.filter(r=>r.gameObject).length,types=new Set(state.records.map(r=>r.objectType)).size,approved=state.records.filter(r=>["Approved","Released"].includes(normalized(r).stage)).length,blocked=state.records.filter(r=>normalized(r).stage==="Blocked").length;return{total:state.records.length,full,types,approved,blocked}}
const metric=(v,l)=>`<div class="metric"><strong>${Number(v).toLocaleString()}</strong><span>${l}</span></div>`;
function progress(status){return status==="complete"?100:status==="active"?45:status==="blocked"?15:0}
function dashboard(){const m=metrics(),steps=state.migration?.steps||[],active=steps.filter(x=>x.status==="active"),features=state.migration?.features||[],done=features.filter(x=>x.status==="complete").length,inProgress=features.filter(x=>x.status==="in-progress").length;return `<section class="hero"><span class="badge">AIOC v2 CONTROL CENTER</span><h2>Developer Dashboard</h2><p>One operational view across content, application modules, testing, decisions, releases, and the ten-step migration.</p></section><section class="metrics">${metric(m.total,"Content records")}${metric(m.full,"Full object bodies")}${metric(m.approved,"Approved or released")}${metric(inProgress,"Features migrating")}</section><section class="workbench-grid"><div class="panel"><div class="panel-head"><h3>Immediate priorities</h3><button data-go="migration">Open migration center</button></div>${active.map(s=>`<div class="card"><b>Step ${s.id}: ${esc(s.name)}</b><div class="bar"><i style="width:${progress(s.status)}%"></i></div><p class="muted">${s.deliverables.map(esc).join(" · ")}</p></div>`).join("")||'<div class="empty">No active migration steps.</div>'}</div><div class="panel"><h3>Project health</h3>${scoreRow("Database availability",state.loadError?10:100)}${scoreRow("Full-object coverage",m.total?Math.round(m.full/m.total*100):0)}${scoreRow("Migration coverage",features.length?Math.round((done+inProgress*.5)/features.length*100):0)}${scoreRow("Pipeline approval",m.total?Math.round(m.approved/m.total*100):0)}<h3>Needs attention</h3><p>${state.loadError?`Database: ${esc(state.loadError)}`:"Database loaded successfully."}</p><p>${m.total-m.full} inventory records still lack complete object bodies.</p><p>${state.decisions.filter(d=>d.status!=="resolved").length} unresolved local decisions.</p></div></section><section class="panel"><div class="panel-head"><h3>All development systems</h3><span class="muted">Migrated tools open natively; remaining tools open their preserved legacy version.</span></div><div class="cards">${state.migration?.features?.map(f=>`<div class="card"><span class="badge">${esc(f.category)}</span><h4>${esc(f.name)}</h4><p>${esc(f.destination)}</p><p class="muted">Status: ${esc(f.status)}</p><button data-feature="${esc(f.id)}">Open</button></div>`).join("")||""}</div></section>`}
function migration(){const steps=state.migration?.steps||[],features=state.migration?.features||[];return `<section class="hero"><h2>Ten-step Migration Center</h2><p>This registry prevents any authoring, development, validation, publishing, AI, or system feature from being forgotten.</p></section><section class="panel"><h3>Rebuild steps</h3>${steps.map(s=>`<div class="card"><div class="panel-head"><b>Step ${s.id}: ${esc(s.name)}</b><span class="badge">${esc(s.status)}</span></div><div class="bar"><i style="width:${progress(s.status)}%"></i></div><p class="muted">${s.deliverables.map(esc).join(" · ")}</p></div>`).join("")}</section><section class="panel"><h3>Feature migration register</h3><div class="table-wrap"><table class="table"><thead><tr><th>Feature</th><th>Category</th><th>Legacy source</th><th>v2 destination</th><th>Status</th></tr></thead><tbody>${features.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td>${esc(f.category)}</td><td>${esc(f.legacy)}</td><td>${esc(f.destination)}</td><td><span class="badge">${esc(f.status)}</span></td></tr>`).join("")}</tbody></table></div></section>`}
function library(){const m=metrics();return `<section class="hero"><h2>Canonical Content Library</h2><p>One repository-backed source of truth for Multiversal game content.</p></section><section class="metrics">${metric(m.total,"Objects")}${metric(m.full,"Full bodies")}${metric(m.types,"Object types")}${metric(m.approved,"Approved")}</section><section class="panel"><div class="filters"><input id="q" placeholder="Search name, stable ID, type, source, tag, or mechanics"><select id="type"><option value="">All types</option>${[...new Set(state.records.map(r=>r.objectType))].sort().map(x=>`<option>${esc(x)}</option>`).join("")}</select><select id="stage"><option value="">All stages</option>${PIPELINE.map(x=>`<option>${x}</option>`).join("")}</select><select id="body"><option value="">Any body state</option><option value="full">Full object body</option><option value="index">Inventory only</option></select></div><div id="results"></div></section>`}
function applyFilters(){const q=($("#q")?.value||"").toLowerCase(),t=$("#type")?.value||"",s=$("#stage")?.value||"",b=$("#body")?.value||"";state.filtered=state.records.filter(x=>{const r=normalized(x),hay=`${r.name} ${r.id} ${r.objectType} ${JSON.stringify(r.provenance||{})} ${JSON.stringify(r.tags||[])} ${JSON.stringify(r.gameObject||{})}`.toLowerCase();return(!q||hay.includes(q))&&(!t||r.objectType===t)&&(!s||r.stage===s)&&(!b||(b==="full"?!!r.gameObject:!r.gameObject))});renderTable()}
function renderTable(){const host=$("#results");if(!host)return;host.innerHTML=`<div class="panel-head"><h3>${state.filtered.length.toLocaleString()} records</h3><span class="spacer muted">Showing first 500</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Type</th><th>Stage</th><th>Completeness</th><th>Stable ID</th></tr></thead><tbody>${state.filtered.slice(0,500).map(r=>{r=normalized(r);return`<tr data-id="${esc(r.id)}"><td><b>${esc(r.name)}</b></td><td><span class="badge">${esc(r.objectType)}</span></td><td>${esc(r.stage)}</td><td>${score(r)}%</td><td class="muted">${esc(r.id)}</td></tr>`}).join("")}</tbody></table></div>`;host.querySelectorAll("tr[data-id]").forEach(tr=>tr.onclick=()=>openObject(tr.dataset.id))}
function openObject(id){state.selected=state.records.find(r=>r.id===id);route("workbench")}
function workbench(){if(!state.selected)return `<section class="panel empty">Select an object from Content Library.</section>`;const r=normalized(state.selected),sc=score(r);return `<section class="hero"><span class="badge">${esc(r.objectType)}</span><h2>${esc(r.name)}</h2><p>${esc(r.id)}</p></section><section class="workbench-grid"><div class="panel"><div class="panel-head"><h3>Structured record</h3><button id="editNotes">Edit notes</button></div><pre>${esc(JSON.stringify(r.gameObject||r,null,2))}</pre></div><div class="panel"><h3>Development state</h3><label>Stage<select id="wbStage">${PIPELINE.map(x=>`<option ${r.stage===x?"selected":""}>${x}</option>`).join("")}</select></label><div class="score-list">${scoreRow("Overall",sc)}${scoreRow("Identity",r.id&&r.name?100:40)}${scoreRow("Mechanics",r.gameObject?100:20)}${scoreRow("Provenance",r.provenance?100:0)}${scoreRow("Relationships",(r.dependencies||[]).length?100:10)}${scoreRow("Assets",state.assets.some(a=>a.objectId===r.id)?100:0)}</div><h3>Notes</h3><p>${esc(r.notes||"No project notes.")}</p><h3>Provenance</h3><pre>${esc(JSON.stringify(r.provenance||{},null,2))}</pre></div></section>`}
function scoreRow(n,v){return `<div class="score-row"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}%</b></div>`}
function graph(){if(!state.selected)return `<section class="panel empty">Select an object first.</section>`;const r=normalized(state.selected),incoming=state.records.filter(x=>(x.dependencies||[]).some(d=>(d.id||d)===r.id));return `<section class="hero"><h2>Knowledge Graph</h2><p>${esc(r.name)} — ${incoming.length} incoming references, ${(r.dependencies||[]).length} outgoing dependencies.</p></section><section class="cards"><div class="card"><h4>Selected</h4><b>${esc(r.name)}</b><p class="muted">${esc(r.id)}</p></div>${incoming.slice(0,30).map(x=>`<div class="card" data-open="${esc(x.id)}"><h4>References selected</h4><b>${esc(x.name)}</b><p class="muted">${esc(x.id)}</p></div>`).join("")}${(r.dependencies||[]).slice(0,30).map(d=>`<div class="card"><h4>Dependency</h4><b>${esc(d.name||d.id||d)}</b></div>`).join("")}</section>`}
function intelligence(){const noBody=state.records.filter(r=>!r.gameObject),noProv=state.records.filter(r=>!r.provenance),broken=[];for(const r of state.records)for(const d of r.dependencies||[]){const id=d.id||d;if(id&&!state.records.some(x=>x.id===id))broken.push({r,id})}const dupes=Object.entries(state.records.reduce((a,r)=>((a[r.name]=(a[r.name]||0)+1),a),{})).filter(([,n])=>n>1);return `<section class="hero"><h2>Development Intelligence</h2><p>Evidence-based observations across the canonical library.</p></section><section class="metrics">${metric(noBody.length,"Inventory-only")}${metric(noProv.length,"Missing provenance")}${metric(broken.length,"Broken references")}${metric(dupes.length,"Repeated names")}</section><section class="cards"><div class="card"><h4>Largest gap</h4><p>${noBody.length.toLocaleString()} records still need full structured bodies.</p></div><div class="card"><h4>Relationship coverage</h4><p>${state.records.filter(r=>(r.dependencies||[]).length).length.toLocaleString()} records declare dependencies.</p></div><div class="card"><h4>Broken references</h4><p>${broken.slice(0,10).map(x=>`${esc(x.r.name)} → ${esc(x.id)}`).join("<br>")||"None detected"}</p></div><div class="card"><h4>Potential duplicates</h4><p>${dupes.slice(0,12).map(([n,c])=>`${esc(n)} (${c})`).join("<br>")||"None detected"}</p></div></section>`}
function assets(){const selected=state.selected?normalized(state.selected):null;return `<section class="hero"><h2>Canonical Asset Manager</h2><p>Link art, maps, documents, audio, and references without changing mechanics.</p></section><section class="panel"><div class="panel-head"><h3>${selected?`Assets for ${esc(selected.name)}`:"Select an object first"}</h3>${selected?'<button id="addAsset" class="primary spacer">Add asset</button>':""}</div><div class="cards">${state.assets.filter(a=>!selected||a.objectId===selected.id).map(a=>`<div class="card"><h4>${esc(a.name)}</h4><p>${esc(a.type)} · v${esc(a.version)}</p><p class="muted">${esc(a.location)}</p></div>`).join("")||'<div class="empty">No linked assets.</div>'}</div></section>`}
function pipeline(){return `<section class="hero"><h2>Content Pipeline</h2><p>Development status is tracked separately from canonical mechanics.</p></section><section class="cards">${PIPELINE.map(g=>{const list=state.records.filter(r=>normalized(r).stage===g);return`<div class="card"><h4>${g}</h4><strong>${list.length.toLocaleString()}</strong><p class="muted">${list.slice(0,8).map(x=>esc(x.name)).join("<br>")}</p></div>`}).join("")}</section>`}
function legacyWorkspace(id,title,description){return `<section class="hero"><span class="badge">MIGRATION IN PROGRESS</span><h2>${esc(title)}</h2><p>${esc(description)}</p></section><section class="panel"><h3>v2 destination</h3><p>This workspace is registered for full native migration. The preserved legacy implementation remains available during reconstruction.</p><div class="panel-head"><button class="primary" data-legacy="${id}">Open preserved legacy tool</button><button data-go="migration">View migration status</button></div></section>`}
function authoring(){return legacyWorkspace("authoring","Authoring Studio","Ability trees, creatures, NPCs, items, species, cultures, vehicles, worlds, environments, adventures, and shared mechanical editors.")}
function packs(){return legacyWorkspace("packs","Pack Manager","Pack Lists, dependency closure, canonical validation, import/export, and final .pack compilation.")}
function balance(){return legacyWorkspace("balance","Balance Lab","Rules-profile analysis, mathematical comparisons, simulations, evidence grading, and balance reports.")}
function testing(){return legacyWorkspace("testing","Game Testing Suite","Test plans, facilitator guidance, sessions, findings, evidence, severity, and regression tests.")}
function modules(){return legacyWorkspace("modules","Feature Module Tracker","Internal-alpha modules, requirements, dependencies, evidence gates, risks, and readiness.")}
function devos(){return legacyWorkspace("devos","Development OS","Work packages, project decisions, AI team coordination, release control, canon checks, and delivery evidence.")}
function settings(){return `<section class="hero"><h2>Settings</h2><p>Accessibility and local project-data controls.</p></section><section class="cards"><div class="card"><h4>Display</h4><label>Font scale<input id="fontScale" type="range" min="90" max="140" value="${localStorage.getItem("mv-v2-font")||100}"></label><label><input id="reducedMotion" type="checkbox" ${localStorage.getItem("mv-v2-motion")==="reduced"?"checked":""}> Reduced motion</label></div><div class="card"><h4>Local data</h4><button id="clearLocal">Clear v2 local overrides</button><p class="muted">Canonical repository content is not deleted.</p></div></section>`}
function diagnostics(){const m=metrics();return `<section class="hero"><h2>Diagnostics</h2><p>Transparent build, migration, database, and storage health.</p></section><section class="cards"><div class="card"><h4>Build</h4><p>${BUILD}</p></div><div class="card"><h4>Database</h4><p>${m.total} records loaded</p></div><div class="card"><h4>Full bodies</h4><p>${m.full}</p></div><div class="card"><h4>Loaded</h4><p>${state.loadedAt||"Not loaded"}</p></div><div class="card"><h4>Database error</h4><p>${esc(state.loadError||"None")}</p></div><div class="card"><h4>Local storage</h4><p>${(new Blob([localStorage.getItem("mv-aioc-v2")||""]).size/1024).toFixed(1)} KB</p></div></section>`}
function modal(title,body,onSave){let d=$("#v2Modal");if(!d){d=document.createElement("dialog");d.id="v2Modal";document.body.appendChild(d)}d.innerHTML=`<form method="dialog" class="panel"><h3>${esc(title)}</h3>${body}<div class="panel-head"><button value="cancel">Cancel</button><button id="modalSave" value="default" class="primary">Save</button></div></form>`;d.showModal();$("#modalSave").onclick=e=>{e.preventDefault();onSave(new FormData(d.querySelector("form")));d.close()}}
function render(){const views={dashboard,migration,library,workbench,graph,intelligence,assets,pipeline,authoring,packs,balance,testing,modules,devos,settings,diagnostics};$("#view").innerHTML=(views[state.route]||dashboard)();document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>route(b.dataset.go));document.querySelectorAll("[data-legacy]").forEach(b=>b.onclick=()=>window.open(LEGACY[b.dataset.legacy],"_blank","noopener"));document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openObject(b.dataset.open));document.querySelectorAll("[data-feature]").forEach(b=>b.onclick=()=>{const map={"developer-dashboard":"dashboard","content-library":"library","diagnostics":"diagnostics","authoring":"authoring","pack-manager":"packs","balance-lab":"balance","testing-suite":"testing","feature-modules":"modules","development-os":"devos","release-control":"devos","settings":"settings","ai-workflows":"authoring"};route(map[b.dataset.feature]||"migration")});if(state.route==="library"){["q","type","stage","body"].forEach(id=>$("#"+id).addEventListener(id==="q"?"input":"change",applyFilters));state.filtered=[...state.records];renderTable()}if(state.route==="workbench"&&$("#wbStage"))$("#wbStage").onchange=e=>{state.overrides[state.selected.id]={...(state.overrides[state.selected.id]||{}),stage:e.target.value};saveLocal();render()};if($("#editNotes"))$("#editNotes").onclick=()=>{const r=normalized(state.selected);modal("Edit project notes",`<label>Notes<textarea name="notes">${esc(r.notes)}</textarea></label>`,fd=>{state.overrides[r.id]={...(state.overrides[r.id]||{}),notes:fd.get("notes")};saveLocal();render()})};if(state.route==="assets"&&$("#addAsset"))$("#addAsset").onclick=()=>modal("Add linked asset",`<label>Name<input name="name" required></label><label>Type<select name="type"><option>Image</option><option>Map</option><option>Document</option><option>Audio</option><option>Video</option><option>Reference</option></select></label><label>Repository path or URL<input name="location"></label><label>Version<input name="version" value="1.0"></label>`,fd=>{state.assets.push({id:uid(),objectId:state.selected.id,name:fd.get("name"),type:fd.get("type"),version:fd.get("version"),location:fd.get("location"),createdAt:new Date().toISOString()});saveLocal();render()});if($("#fontScale"))$("#fontScale").oninput=e=>{document.documentElement.style.fontSize=`${e.target.value}%`;localStorage.setItem("mv-v2-font",e.target.value)};if($("#reducedMotion"))$("#reducedMotion").onchange=e=>{localStorage.setItem("mv-v2-motion",e.target.checked?"reduced":"normal");document.documentElement.classList.toggle("reduced-motion",e.target.checked)};if($("#clearLocal"))$("#clearLocal").onclick=()=>{if(confirm("Clear v2 local overrides, assets, tests, modules, and decisions?")){localStorage.removeItem("mv-aioc-v2");location.reload()}}}
async function loadDatabase(){const candidates=["./data/content.json","../content-db/index.json"];let last;for(const url of candidates)try{const res=await fetch(url,{cache:"no-store"});if(!res.ok)throw new Error(`${url} returned ${res.status}`);const payload=await res.json();const source=payload.records||payload.objects||[];if(!Array.isArray(source)||!source.length)throw new Error(`${url} contained no records`);return source.map((r,i)=>({id:r.id||r.stableId||r.databaseId||`record-${i}`,name:r.name||r.title||r.stableId||`Record ${i+1}`,objectType:r.objectType||r.contentType||r.gameObject?.objectKind||r.type||"Unclassified",stage:r.developmentStage||r.stage||"Imported",provenance:r.provenance||{source:r.source||url},dependencies:r.dependencies||r.gameObject?.dependencies||[],gameObject:r.gameObject||r.object||null,tags:r.tags||[]}))}catch(e){last=e}throw last||new Error("No database source was available")}
async function boot(){loadLocal();document.documentElement.style.fontSize=`${localStorage.getItem("mv-v2-font")||100}%`;document.documentElement.classList.toggle("reduced-motion",localStorage.getItem("mv-v2-motion")==="reduced");$("#build").textContent=`Build ${BUILD}`;nav();$("#menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");$("#backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify({build:BUILD,overrides:state.overrides,assets:state.assets,modules:state.modules,tests:state.tests,decisions:state.decisions},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="multiversal-aioc-v2-state.json";a.click();URL.revokeObjectURL(a.href)};$("#diagnosticsBtn").onclick=()=>route("diagnostics");const [migrationResult,databaseResult]=await Promise.allSettled([fetch("./migration-registry.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`Migration registry ${r.status}`);return r.json()}),loadDatabase()]);if(migrationResult.status==="fulfilled")state.migration=migrationResult.value;else state.migration={steps:[],features:[]};if(databaseResult.status==="fulfilled"){state.records=databaseResult.value;state.loadedAt=new Date().toISOString()}else state.loadError=databaseResult.reason?.message||String(databaseResult.reason);render()}
boot();
