const BUILD="2.0.0-foundation";
const ROUTES=[
  ["library","Content Library","Canonical object explorer"],
  ["workbench","Object Workbench","Inspect mechanics, provenance, and history"],
  ["graph","Knowledge Graph","Dependencies and incoming references"],
  ["intelligence","Development Intelligence","Coverage, gaps, and consistency"],
  ["assets","Asset Manager","Object-linked media and references"],
  ["pipeline","Content Pipeline","Development stages and release readiness"],
  ["diagnostics","Diagnostics","Build, database, and storage health"]
];
const state={records:[],filtered:[],selected:null,route:"library",overrides:{},assets:[],loadedAt:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function loadLocal(){try{const x=JSON.parse(localStorage.getItem("mv-aioc-v2")||"{}");state.overrides=x.overrides||{};state.assets=x.assets||[]}catch{}}
function saveLocal(){localStorage.setItem("mv-aioc-v2",JSON.stringify({overrides:state.overrides,assets:state.assets,updatedAt:new Date().toISOString()}))}
function normalized(r){const o=state.overrides[r.id]||{};return{...r,stage:o.stage||r.stage||"Imported",notes:o.notes||"",tags:o.tags||[],dependencies:r.dependencies||[],gameObject:r.gameObject||null}}
function score(r){let n=0,total=7;if(r.id)n++;if(r.name)n++;if(r.objectType)n++;if(r.provenance)n++;if(r.gameObject)n++;if((r.dependencies||[]).length)n++;if(state.assets.some(a=>a.objectId===r.id))n++;return Math.round(n/total*100)}
function nav(){const n=$("#nav");n.innerHTML=ROUTES.map(([id,name])=>`<button class="nav-btn ${state.route===id?"active":""}" data-route="${id}">${name}</button>`).join("");n.querySelectorAll("button").forEach(b=>b.onclick=()=>route(b.dataset.route))}
function route(id){state.route=id;const r=ROUTES.find(x=>x[0]===id);$("#pageTitle").textContent=r[1];$("#pageSubtitle").textContent=r[2];nav();render();document.querySelector(".sidebar").classList.remove("open")}
function metrics(){const full=state.records.filter(r=>r.gameObject).length;const types=new Set(state.records.map(r=>r.objectType)).size;const reviewed=state.records.filter(r=>(state.overrides[r.id]?.stage||"")==="Approved").length;return{total:state.records.length,full,types,reviewed}}
function library(){const m=metrics();return `<section class="hero"><h2>Canonical Content Library</h2><p>One repository-backed source of truth for Multiversal game content.</p></section><section class="metrics">${metric(m.total,"Objects")}${metric(m.full,"Full bodies")}${metric(m.types,"Object types")}${metric(m.reviewed,"Approved")}</section><section class="panel"><div class="filters"><input id="q" placeholder="Search name, stable ID, type, or source"><select id="type"><option value="">All types</option>${[...new Set(state.records.map(r=>r.objectType))].sort().map(x=>`<option>${esc(x)}</option>`).join("")}</select><select id="stage"><option value="">All stages</option>${["Imported","Draft","Review","Balance","Testing","Approved","Released"].map(x=>`<option>${x}</option>`).join("")}</select><select id="body"><option value="">Any body state</option><option value="full">Full object body</option><option value="index">Inventory only</option></select></div><div id="results"></div></section>`}
function metric(v,l){return `<div class="metric"><strong>${Number(v).toLocaleString()}</strong><span>${l}</span></div>`}
function applyFilters(){const q=($("#q")?.value||"").toLowerCase(),t=$("#type")?.value||"",s=$("#stage")?.value||"",b=$("#body")?.value||"";state.filtered=state.records.filter(x=>{const r=normalized(x),hay=`${r.name} ${r.id} ${r.objectType} ${JSON.stringify(r.provenance||{})}`.toLowerCase();return(!q||hay.includes(q))&&(!t||r.objectType===t)&&(!s||r.stage===s)&&(!b||(b==="full"?!!r.gameObject:!r.gameObject))});renderTable()}
function renderTable(){const host=$("#results");if(!host)return;host.innerHTML=`<div class="panel-head"><h3>${state.filtered.length.toLocaleString()} records</h3><span class="spacer muted">Showing first 500</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Type</th><th>Stage</th><th>Completeness</th><th>Stable ID</th></tr></thead><tbody>${state.filtered.slice(0,500).map(r=>{r=normalized(r);return`<tr data-id="${esc(r.id)}"><td><b>${esc(r.name)}</b></td><td><span class="badge">${esc(r.objectType)}</span></td><td class="stage">${esc(r.stage)}</td><td>${score(r)}%</td><td class="muted">${esc(r.id)}</td></tr>`}).join("")}</tbody></table></div>`;host.querySelectorAll("tr[data-id]").forEach(tr=>tr.onclick=()=>openObject(tr.dataset.id))}
function openObject(id){state.selected=state.records.find(r=>r.id===id);route("workbench")}
function workbench(){if(!state.selected)return `<section class="panel empty">Select an object from Content Library.</section>`;const r=normalized(state.selected),sc=score(r);return `<section class="hero"><span class="badge">${esc(r.objectType)}</span><h2>${esc(r.name)}</h2><p>${esc(r.id)}</p></section><section class="workbench-grid"><div class="panel"><div class="panel-head"><h3>Structured record</h3></div><pre>${esc(JSON.stringify(r.gameObject||r,null,2))}</pre></div><div class="panel"><h3>Development state</h3><label>Stage<select id="wbStage">${["Imported","Draft","Review","Balance","Testing","Approved","Released"].map(x=>`<option ${r.stage===x?"selected":""}>${x}</option>`).join("")}</select></label><div class="score-list">${scoreRow("Overall",sc)}${scoreRow("Identity",r.id&&r.name?100:40)}${scoreRow("Mechanics",r.gameObject?100:20)}${scoreRow("Provenance",r.provenance?100:0)}${scoreRow("Relationships",(r.dependencies||[]).length?100:10)}${scoreRow("Assets",state.assets.some(a=>a.objectId===r.id)?100:0)}</div><h3>Provenance</h3><pre>${esc(JSON.stringify(r.provenance||{},null,2))}</pre></div></section>`}
function scoreRow(n,v){return `<div class="score-row"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}%</b></div>`}
function graph(){if(!state.selected)return `<section class="panel empty">Select an object first.</section>`;const r=normalized(state.selected),incoming=state.records.filter(x=>(x.dependencies||[]).some(d=>(d.id||d)===r.id));return `<section class="hero"><h2>Knowledge Graph</h2><p>${esc(r.name)} — ${incoming.length} incoming references, ${(r.dependencies||[]).length} outgoing dependencies.</p></section><section class="cards"><div class="card"><h4>Selected</h4><b>${esc(r.name)}</b><p class="muted">${esc(r.id)}</p></div>${incoming.slice(0,30).map(x=>`<div class="card"><h4>References selected</h4><b>${esc(x.name)}</b><p class="muted">${esc(x.id)}</p></div>`).join("")}${(r.dependencies||[]).slice(0,30).map(d=>`<div class="card"><h4>Dependency</h4><b>${esc(d.name||d.id||d)}</b></div>`).join("")}</section>`}
function intelligence(){const noBody=state.records.filter(r=>!r.gameObject),noProv=state.records.filter(r=>!r.provenance),dupes=Object.entries(state.records.reduce((a,r)=>((a[r.name]=(a[r.name]||0)+1),a),{})).filter(([,n])=>n>1);return `<section class="hero"><h2>Development Intelligence</h2><p>Evidence-based observations across the canonical library.</p></section><section class="metrics">${metric(noBody.length,"Inventory-only")}${metric(noProv.length,"Missing provenance")}${metric(dupes.length,"Repeated names")}${metric(state.records.filter(r=>score(r)<50).length,"Low completeness")}</section><section class="cards"><div class="card"><h4>Largest gap</h4><p>${noBody.length.toLocaleString()} records still need full structured bodies.</p></div><div class="card"><h4>Relationship coverage</h4><p>${state.records.filter(r=>(r.dependencies||[]).length).length.toLocaleString()} records declare dependencies.</p></div><div class="card"><h4>Potential duplicates</h4><p>${dupes.slice(0,12).map(([n,c])=>`${esc(n)} (${c})`).join("<br>")||"None detected"}</p></div></section>`}
function assets(){const selected=state.selected?normalized(state.selected):null;return `<section class="hero"><h2>Canonical Asset Manager</h2><p>Link art, maps, documents, audio, and references without changing mechanics.</p></section><section class="panel"><div class="panel-head"><h3>${selected?`Assets for ${esc(selected.name)}`:"Select an object first"}</h3>${selected?'<button id="addAsset" class="primary spacer">Add asset</button>':""}</div><div class="cards">${state.assets.filter(a=>!selected||a.objectId===selected.id).map(a=>`<div class="card"><h4>${esc(a.name)}</h4><p>${esc(a.type)} · v${esc(a.version)}</p><p class="muted">${esc(a.location)}</p></div>`).join("")||'<div class="empty">No linked assets.</div>'}</div></section>`}
function pipeline(){const groups=["Imported","Draft","Review","Balance","Testing","Approved","Released"];return `<section class="hero"><h2>Content Pipeline</h2><p>Development status is tracked separately from canonical mechanics.</p></section><section class="cards">${groups.map(g=>{const list=state.records.filter(r=>(state.overrides[r.id]?.stage||"Imported")===g);return`<div class="card"><h4>${g}</h4><strong>${list.length.toLocaleString()}</strong><p class="muted">${list.slice(0,8).map(x=>esc(x.name)).join("<br>")}</p></div>`}).join("")}</section>`}
function diagnostics(){const m=metrics();return `<section class="hero"><h2>Diagnostics</h2><p>Transparent build and database health.</p></section><section class="cards"><div class="card"><h4>Build</h4><p>${BUILD}</p></div><div class="card"><h4>Database</h4><p>${m.total} records loaded</p></div><div class="card"><h4>Full bodies</h4><p>${m.full}</p></div><div class="card"><h4>Loaded</h4><p>${state.loadedAt||"Not loaded"}</p></div><div class="card"><h4>Local overrides</h4><p>${Object.keys(state.overrides).length}</p></div><div class="card"><h4>Storage</h4><p>${(new Blob([localStorage.getItem("mv-aioc-v2")||""]).size/1024).toFixed(1)} KB</p></div></section>`}
function render(){const v=$("#view");v.innerHTML=state.route==="library"?library():state.route==="workbench"?workbench():state.route==="graph"?graph():state.route==="intelligence"?intelligence():state.route==="assets"?assets():state.route==="pipeline"?pipeline():diagnostics();if(state.route==="library"){["q","type","stage","body"].forEach(id=>$("#"+id).addEventListener(id==="q"?"input":"change",applyFilters));state.filtered=[...state.records];renderTable()}if(state.route==="workbench"&&$("#wbStage"))$("#wbStage").onchange=e=>{state.overrides[state.selected.id]={...(state.overrides[state.selected.id]||{}),stage:e.target.value};saveLocal();render()};if(state.route==="assets"&&$("#addAsset"))$("#addAsset").onclick=()=>{const name=prompt("Asset name");if(!name)return;const location=prompt("Repository path or URL")||"";state.assets.push({id:crypto.randomUUID(),objectId:state.selected.id,name,type:"Reference",version:"1.0",location,createdAt:new Date().toISOString()});saveLocal();render()}}
async function boot(){loadLocal();$("#build").textContent=`Build ${BUILD}`;nav();$("#menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");$("#backupBtn").onclick=()=>{const blob=new Blob([JSON.stringify({build:BUILD,overrides:state.overrides,assets:state.assets},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="multiversal-aioc-v2-state.json";a.click();URL.revokeObjectURL(a.href)};$("#diagnosticsBtn").onclick=()=>route("diagnostics");try{const res=await fetch("./data/content.json",{cache:"no-store"});if(!res.ok)throw new Error(`Database request failed (${res.status})`);const payload=await res.json();state.records=(payload.records||[]).map(r=>({...r,dependencies:r.dependencies||[],gameObject:r.gameObject||null}));state.loadedAt=new Date().toISOString();render()}catch(e){$("#view").innerHTML=`<section class="panel"><h2 class="danger">Database failed to load</h2><p>${esc(e.message)}</p></section>`}}
boot();