const BUILD='3.2.0-completion-sprint';
const KEY='mv-aioc-v2-completion-sprint';
const TABS=[['overview','Readiness'],['repair','Repair Queue'],['certify','Batch Certification'],['pipeline','Pipeline Promotion'],['coverage','Coverage Targets']];
const state={tab:'overview',records:[],registry:null,decisions:{},receipts:{},targets:{},history:[]};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(reason){state.history.unshift({at:new Date().toISOString(),reason});state.history=state.history.slice(0,300);localStorage.setItem(KEY,JSON.stringify({...state,records:[],registry:null}))}
function loadLocal(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}}
function refs(o){const out=[];const walk=(v,k='')=>{if(Array.isArray(v))v.forEach(x=>walk(x,k));else if(v&&typeof v==='object')Object.entries(v).forEach(([a,b])=>walk(b,a));else if(typeof v==='string'&&(/Id$/.test(k)||/Ids$/.test(k)||k==='dependencies'))out.push(v)};walk(o);return [...new Set(out)]}
function idOf(r){return r.id||r.stableId||r.gameObject?.id||''} function typeOf(r){return r.objectType||r.objectKind||r.type||r.gameObject?.objectType||'Unclassified'} function bodyOf(r){return r.gameObject||r}
function audit(){const ids=new Map(),names=new Map(),missing=[],invalid=[];for(const r of state.records){const id=idOf(r),name=(r.name||r.title||'').trim().toLowerCase();if(id)(ids.get(id)||ids.set(id,[]).get(id)).push(r);else invalid.push({kind:'identity',record:r});if(name)(names.get(name)||names.set(name,[]).get(name)).push(r)}const known=new Set([...ids.keys()]);for(const r of state.records)for(const ref of refs(bodyOf(r)))if(ref.includes('.')&&!known.has(ref))missing.push({source:idOf(r),target:ref});return{duplicateIds:[...ids].filter(([,v])=>v.length>1),duplicateNames:[...names].filter(([,v])=>v.length>1),missing,invalid}}
function contract(r){const body=bodyOf(r),id=idOf(r),objType=body.objectType||r.objectType;const c=state.registry?.objects?.find(x=>x.objectId===objType);const blockers=[],warnings=[];for(const f of state.registry?.baseRequired||[])if(body[f]===undefined||body[f]===null||body[f]==='')blockers.push(`Missing ${f}`);if(!id)blockers.push('Missing stable ID');if(!c)blockers.push(`Unregistered object type: ${objType||'none'}`);if(c){for(const f of c.specRequired||[])if(body.spec?.[f]===undefined||body.spec?.[f]===null||body.spec?.[f]==='')blockers.push(`Missing spec.${f}`);for(const f of Object.keys(body.spec||{}))if(c.specProperties?.length&&!c.specProperties.includes(f))warnings.push(`Unlisted spec.${f}`)}return{state:blockers.length?'blocked':warnings.length?'provisional':'pass',blockers,warnings,contract:c?.objectId||null}}
function metrics(){const a=audit(),cert=Object.values(state.receipts),pass=cert.filter(x=>x.state==='pass').length,blocked=cert.filter(x=>x.state==='blocked').length;return{total:state.records.length,full:state.records.filter(r=>Object.keys(bodyOf(r)).length>4).length,dup:a.duplicateIds.length+a.duplicateNames.length,missing:a.missing.length,pass,blocked}}
const card=(n,l,c='')=>`<div class="cs-card"><strong class="${c}">${Number(n).toLocaleString()}</strong><div>${l}</div></div>`;
function overview(){const m=metrics(),pct=m.total?Math.round(m.pass/m.total*100):0;return `<div class="cs-grid">${card(m.total,'Known records')}${card(m.full,'Structured bodies','good')}${card(m.dup,'Duplicate groups',m.dup?'warn':'good')}${card(m.missing,'Unresolved references',m.missing?'bad':'good')}${card(m.pass,'Contract passes','good')}${card(m.blocked,'Blocked receipts',m.blocked?'bad':'good')}</div><section class="cs-card" style="margin-top:14px"><h2>Project readiness</h2><div class="bar"><i style="width:${pct}%"></i></div><p>${pct}% of records have current contract-pass receipts. This score does not imply balance, testing, Pack, or owner approval.</p><div class="cs-grid"><div><h3>Completed in this sprint</h3><p>Repair triage, batch certification, coverage targets, promotion gates, portable repair sets, and a consolidated readiness view.</p></div><div><h3>Still external</h3><p>Recovery of source objects not yet present, real app importer testing, human playtesting, and final owner canon approval.</p></div></div></section>`}
function repair(){const a=audit();const rows=[...a.invalid.map(x=>({kind:'Missing identity',source:x.record.name||'Unnamed',target:''})),...a.duplicateIds.map(([k,v])=>({kind:'Duplicate stable ID',source:k,target:`${v.length} records`})),...a.duplicateNames.map(([k,v])=>({kind:'Repeated name',source:k,target:v.map(idOf).join(', ')})),...a.missing.map(x=>({kind:'Unresolved reference',source:x.source,target:x.target}))];return `<section class="cs-card"><div class="cs-head"><div><h2>Repair Queue</h2><p>${rows.length} detected issues. Decisions are tracked separately from canonical records.</p></div><button id="exportRepair">Export repair set</button></div><div class="cs-list">${rows.slice(0,1500).map((r,i)=>{const k=`${r.kind}:${r.source}:${r.target}`;return`<article class="cs-row"><b>${esc(r.kind)}</b><small>${esc(r.source)} ${r.target?'→ '+esc(r.target):''}</small><select data-decision="${esc(k)}"><option value="">Unreviewed</option>${['accept','alias','replace','defer','false-positive'].map(x=>`<option ${state.decisions[k]===x?'selected':''}>${x}</option>`).join('')}</select></article>`}).join('')||'<p class="good">No repair issues detected.</p>'}</div></section>`}
function certify(){const cert=Object.entries(state.receipts);return `<section class="cs-card"><div class="cs-head"><div><h2>Batch Certification</h2><p>Run governed 8D-003 contract checks across the loaded database.</p></div><div><button id="certAll">Certify all</button><button id="exportReceipts">Export receipts</button></div></div><div class="cs-grid">${card(cert.filter(([,x])=>x.state==='pass').length,'Pass','good')}${card(cert.filter(([,x])=>x.state==='provisional').length,'Provisional','warn')}${card(cert.filter(([,x])=>x.state==='blocked').length,'Blocked','bad')}</div><div class="cs-list" style="margin-top:14px">${cert.slice(0,1000).map(([id,x])=>`<article class="cs-row"><b>${esc(id)}</b><small class="${x.state==='pass'?'good':x.state==='blocked'?'bad':'warn'}">${x.state} · ${x.blockers.length} blockers · ${x.warnings.length} warnings</small></article>`).join('')||'<p>No receipts yet.</p>'}</div></section>`}
function pipeline(){const stages=['source','structured','contract-pass','balance','testing','pack-certified','owner-approved','released'];const items=state.records.slice(0,1200).map(r=>{const id=idOf(r),rec=state.receipts[id],local=state.decisions[`stage:${id}`]||'structured';const max=rec?.state==='pass'?2:1;return{id,name:r.name||id,current:stages[Math.max(stages.indexOf(local),max)]||'structured'}});return `<section class="cs-card"><h2>Pipeline Promotion</h2><p>Promotion is explicit. Contract checks can advance readiness but never grant balance, testing, Pack, owner, or release approval.</p><div class="cs-list">${items.map(x=>`<article class="cs-row"><b>${esc(x.name)}</b><small>${esc(x.id)}</small><select data-stage="${esc(x.id)}">${stages.map(s=>`<option ${x.current===s?'selected':''}>${s}</option>`).join('')}</select></article>`).join('')}</div></section>`}
function coverage(){const groups=Object.entries(state.records.reduce((a,r)=>{const t=typeOf(r);(a[t]??=[]).push(r);return a},{})).sort((a,b)=>b[1].length-a[1].length);return `<section class="cs-card"><h2>Coverage Targets</h2><p>Set local planning targets without pretending they are source counts.</p><div class="cs-list">${groups.map(([t,rs])=>{const target=Number(state.targets[t]||rs.length),pct=Math.min(100,Math.round(rs.length/Math.max(1,target)*100));return`<article class="cs-row"><b>${esc(t)}</b><small>${rs.length} current / ${target} target</small><div class="bar"><i style="width:${pct}%"></i></div><input type="number" min="0" data-target="${esc(t)}" value="${target}"></article>`}).join('')}</div></section>`}
function render(){const fn={overview,repair,certify,pipeline,coverage}[state.tab];$('#view').innerHTML=fn();bind()}
function tabs(){$('#tabs').innerHTML=TABS.map(([k,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${l}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;tabs();render()})}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(){document.querySelectorAll('[data-decision]').forEach(x=>x.onchange=()=>{state.decisions[x.dataset.decision]=x.value;save('repair decision')});document.querySelectorAll('[data-stage]').forEach(x=>x.onchange=()=>{state.decisions[`stage:${x.dataset.stage}`]=x.value;save('pipeline stage change')});document.querySelectorAll('[data-target]').forEach(x=>x.onchange=()=>{state.targets[x.dataset.target]=Number(x.value);save('coverage target change');render()});$('#certAll')?.addEventListener('click',()=>{for(const r of state.records){const id=idOf(r)||`unnamed-${Math.random()}`;state.receipts[id]={...contract(r),at:new Date().toISOString(),registry:state.registry?.version,build:BUILD}}save('batch certification');render()});$('#exportRepair')?.addEventListener('click',()=>download('multiversal-repair-set.json',{build:BUILD,generatedAt:new Date().toISOString(),decisions:state.decisions,audit:audit()}));$('#exportReceipts')?.addEventListener('click',()=>download('multiversal-certification-receipts.json',{build:BUILD,registry:state.registry?.version,receipts:state.receipts}));}
async function boot(){loadLocal();tabs();$('#exportBtn').onclick=()=>download('multiversal-completion-sprint.json',{build:BUILD,decisions:state.decisions,receipts:state.receipts,targets:state.targets,history:state.history});try{const [mod,reg]=await Promise.all([import('./data/source-loader.js'),fetch('../canonical-schema-registry.json').then(r=>r.json())]);const p=await mod.loadSourceRecords();state.records=(p.records||[]);state.registry=reg;render()}catch(e){$('#view').innerHTML=`<section class="cs-card"><h2 class="bad">Unable to load project sources</h2><pre>${esc(e.stack||e.message)}</pre></section>`}}boot();