const BUILD='2.4.0-finalization';
const TABS=[['audit','Migration Audit'],['legacy','Legacy Import'],['regression','Regression Suite'],['integrity','Integrity Review'],['promotion','Promotion Gate'],['advisor','AI Workflow Builder']];
const KEYS={core:'mv-aioc-v2',ops:'mv-aioc-v2-operations',legacy:'aioc-state',legacyDesktop:'mv-unified-desktop-v3'};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const state={tab:'audit',core:{},ops:{},legacy:null,checks:[],audit:[],lastRun:null};
function read(key,fallback={}){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function load(){state.core=read(KEYS.core,{});state.ops=read(KEYS.ops,{});state.legacy=read(KEYS.legacy,null);state.audit=read('mv-aioc-v2-finalization',[])}
function saveAudit(entry){state.audit.unshift({id:uid(),at:new Date().toISOString(),...entry});state.audit=state.audit.slice(0,200);localStorage.setItem('mv-aioc-v2-finalization',JSON.stringify(state.audit))}
function nav(){const n=$('#finalNav');n.innerHTML=TABS.map(([k,l])=>`<button class="${state.tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab))}
function openTab(k){state.tab=k;const t=TABS.find(x=>x[0]===k);$('#finalTitle').textContent=t[1];$('#finalSubtitle').textContent=k==='audit'?'Legacy state, regression checks, and promotion readiness':k==='legacy'?'Inspect and migrate preserved browser data':k==='regression'?'Run end-to-end functional checks':k==='integrity'?'Check links, IDs, packs, evidence, and releases':k==='promotion'?'Determine whether v2 can become the default':'Generate contextual prompts for guided AI work';nav();render();document.querySelector('.ops-sidebar').classList.remove('open')}
const metric=(v,l)=>`<div class="metric"><strong>${Number(v).toLocaleString()}</strong><span>${l}</span></div>`;
function collect(){const o=state.ops||{},c=state.core||{};return{drafts:o.drafts||[],packs:o.packs||[],balance:o.balance||[],tests:o.tests||[],modules:o.modules||c.modules||[],work:o.work||[],decisions:o.decisions||c.decisions||[],risks:o.risks||[],releases:o.releases||[],assets:c.assets||[],overrides:c.overrides||{}}}
function legacyCounts(){const l=state.legacy||{};return Object.entries(l).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,v.length]).sort((a,b)=>b[1]-a[1])}
function auditView(){const x=collect(),legacy=legacyCounts();const unresolved=x.decisions.filter(d=>!['resolved','closed','approved'].includes(String(d.status||'').toLowerCase())).length;return `<section class="hero"><span class="badge">FINAL MIGRATION CONTROL</span><h2>AIOC v2 Finalization</h2><p>Evidence-based migration, regression, and promotion status. No legacy data is deleted automatically.</p></section><section class="metrics">${metric(x.drafts.length,'v2 drafts')}${metric(x.packs.length,'v2 packs')}${metric(x.tests.length,'test plans')}${metric(legacy.reduce((a,[,n])=>a+n,0),'legacy records')}</section><section class="workspace-grid"><div class="panel"><h3>Current readiness</h3>${bar('Core state readable',state.core?100:0)}${bar('Operations state readable',state.ops?100:0)}${bar('Legacy state inspected',state.legacy?100:30)}${bar('Regression suite',state.checks.length?Math.round(state.checks.filter(c=>c.pass).length/state.checks.length*100):0)}${bar('Unresolved decisions',unresolved?35:100)}</div><div class="panel"><h3>Recent audit history</h3><div class="timeline">${state.audit.slice(0,12).map(a=>`<article><b>${esc(a.kind||'Audit')}</b><p>${esc(a.message||'')}</p><small>${esc(a.at)}</small></article>`).join('')||'<div class="empty-note">No audit events yet.</div>'}</div></div></section>`}
function bar(name,value){return `<div class="score-row"><span>${esc(name)}</span><div class="bar"><i style="width:${value}%"></i></div><b>${value}%</b></div>`}
function legacyView(){const counts=legacyCounts();return `<section class="hero"><h2>Legacy Browser Data Import</h2><p>Preview preserved legacy collections and merge recognized records into v2 without replacing current work.</p></section><section class="panel"><div class="panel-head"><h3>Detected legacy collections</h3><button id="scanLegacy">Rescan</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Collection</th><th>Records</th><th>Migration target</th></tr></thead><tbody>${counts.map(([k,n])=>`<tr><td><b>${esc(k)}</b></td><td>${n}</td><td>${esc(targetFor(k))}</td></tr>`).join('')||'<tr><td colspan="3">No readable aioc-state data found.</td></tr>'}</tbody></table></div><div class="panel-head"><button id="migrateLegacy" class="primary" ${counts.length?'':'disabled'}>Merge recognized legacy data</button><button id="downloadLegacy">Export untouched legacy snapshot</button></div></section>`}
function targetFor(k){const s=k.toLowerCase();if(s.includes('test'))return'Testing';if(s.includes('module')||s.includes('feature'))return'Feature Modules';if(s.includes('decision')||s.includes('alert')||s.includes('approval'))return'Development OS';if(s.includes('pack'))return'Pack Manager';if(s.includes('balance'))return'Balance Lab';if(s.includes('object')||s.includes('ability')||s.includes('creature')||s.includes('item'))return'Content/Authoring';return'Manual review'}
function regressionView(){return `<section class="hero"><h2>End-to-End Regression Suite</h2><p>Checks the critical workflow from content creation through Pack, evidence, release, backup, and restore.</p></section><section class="panel"><div class="panel-head"><h3>${state.checks.length?`${state.checks.filter(c=>c.pass).length}/${state.checks.length} checks passing`:'Not run'}</h3><button id="runRegression" class="primary">Run regression suite</button></div><div class="cards">${state.checks.map(c=>`<div class="card"><span class="badge ${c.pass?'status-good':'status-warn'}">${c.pass?'PASS':'FAIL'}</span><h4>${esc(c.name)}</h4><p>${esc(c.detail)}</p></div>`).join('')||'<div class="empty-note">Run the suite to generate evidence.</div>'}</div></section>`}
function integrityView(){const x=collect(),draftIds=new Set(x.drafts.map(d=>d.stableId||d.id)),duplicates=[...draftIds].filter((id,i,a)=>a.indexOf(id)!==i);const missingPack=[];for(const p of x.packs)for(const oid of p.objectIds||[])if(!x.drafts.some(d=>d.id===oid||d.stableId===oid))missingPack.push(`${p.name}: ${oid}`);const orphanBalance=x.balance.filter(b=>b.objectId&&!x.drafts.some(d=>d.stableId===b.objectId));const critical=x.tests.flatMap(t=>(t.findings||[]).filter(f=>String(f.severity||'').toLowerCase()==='critical'&&!['resolved','closed'].includes(String(f.status||'').toLowerCase())));return `<section class="hero"><h2>Cross-System Integrity Review</h2><p>Finds mismatches between drafts, Packs, balance evidence, tests, modules, and releases.</p></section><section class="metrics">${metric(duplicates.length,'duplicate IDs')}${metric(missingPack.length,'missing Pack objects')}${metric(orphanBalance.length,'orphan balance records')}${metric(critical.length,'open critical findings')}</section><section class="cards"><div class="card"><h4>Duplicate IDs</h4><p>${duplicates.map(esc).join('<br>')||'None detected'}</p></div><div class="card"><h4>Pack references</h4><p>${missingPack.slice(0,30).map(esc).join('<br>')||'No missing local draft references'}</p></div><div class="card"><h4>Evidence linkage</h4><p>${orphanBalance.slice(0,20).map(b=>esc(b.objectId)).join('<br>')||'No orphan balance evidence'}</p></div><div class="card"><h4>Release blockers</h4><p>${critical.slice(0,20).map(f=>esc(f.title||f.detail||'Critical finding')).join('<br>')||'No unresolved critical findings'}</p></div></section>`}
function promotionView(){const checks=promotionChecks();const ready=checks.every(c=>c.pass);return `<section class="hero"><span class="badge ${ready?'status-good':'status-warn'}">${ready?'PROMOTION READY':'PROMOTION BLOCKED'}</span><h2>v2 Default-Site Gate</h2><p>v2 should become the default only after every required gate has explicit evidence.</p></section><section class="panel"><div class="cards">${checks.map(c=>`<div class="card"><span class="badge ${c.pass?'status-good':'status-warn'}">${c.pass?'PASS':'BLOCK'}</span><h4>${esc(c.name)}</h4><p>${esc(c.detail)}</p></div>`).join('')}</div><div class="panel-head"><button id="exportPromotion">Export promotion receipt</button><button id="markCandidate" class="primary" ${ready?'':'disabled'}>Mark v2 release candidate</button></div></section>`}
function promotionChecks(){const x=collect();const regression=state.checks.length>0&&state.checks.every(c=>c.pass);const critical=x.tests.flatMap(t=>t.findings||[]).filter(f=>String(f.severity||'').toLowerCase()==='critical'&&!['resolved','closed'].includes(String(f.status||'').toLowerCase())).length;return[{name:'v2 core state',pass:!!state.core,detail:'Dashboard state is readable.'},{name:'v2 operations state',pass:!!state.ops,detail:'Operations project state is readable.'},{name:'Regression suite',pass:regression,detail:regression?'All critical workflow checks pass.':'Run and pass the regression suite.'},{name:'Critical findings',pass:critical===0,detail:`${critical} unresolved critical findings.`},{name:'Backup evidence',pass:(state.ops.restore||[]).length>0,detail:`${(state.ops.restore||[]).length} restore points available.`},{name:'Legacy inspection',pass:state.legacy!==undefined,detail:'Legacy storage was inspected; deletion is not required.'}]}
function advisorView(){return `<section class="hero"><h2>Database-Aware AI Workflow Builder</h2><p>Builds a contextual prompt package for ChatGPT without silently changing project data or requiring paid API use.</p></section><section class="panel"><div class="form-grid"><label>Task<select id="aiTask"><option>Improve selected object</option><option>Review Pack consistency</option><option>Design a test plan</option><option>Analyze feature readiness</option><option>Prepare release review</option><option>Resolve migration gaps</option></select></label><label>Object or topic<input id="aiSubject" placeholder="Stable ID, Pack, module, or concept"></label><label class="wide">Goal<textarea id="aiGoal" placeholder="What outcome should the guided conversation produce?"></textarea></label></div><button id="buildPrompt" class="primary">Build contextual prompt</button><div id="promptOutput"></div></section>`}
function render(){const map={audit:auditView,legacy:legacyView,regression:regressionView,integrity:integrityView,promotion:promotionView,advisor:advisorView};$('#finalView').innerHTML=map[state.tab]();bind()}
function bind(){$('#scanLegacy')?.addEventListener('click',()=>{state.legacy=read(KEYS.legacy,null);saveAudit({kind:'Legacy scan',message:`Detected ${legacyCounts().length} legacy collections.`});render()});$('#downloadLegacy')?.addEventListener('click',()=>download('multiversal-legacy-state.json',state.legacy||{}));$('#migrateLegacy')?.addEventListener('click',migrateLegacy);$('#runRegression')?.addEventListener('click',runRegression);$('#exportPromotion')?.addEventListener('click',()=>download('multiversal-v2-promotion-receipt.json',{build:BUILD,generatedAt:new Date().toISOString(),checks:promotionChecks(),regression:state.checks}));$('#markCandidate')?.addEventListener('click',()=>{saveAudit({kind:'Release candidate',message:'v2 satisfied local promotion gates and was marked as a release candidate.'});alert('Release candidate receipt recorded. The legacy site has not been deleted.');render()});$('#buildPrompt')?.addEventListener('click',buildPrompt)}
function mergeUnique(target,source,key='id'){const seen=new Set(target.map(x=>x?.[key]).filter(Boolean));for(const x of source||[]){const k=x?.[key]||uid();if(!seen.has(k)){target.push({...x,[key]:k});seen.add(k)}}return target}
function migrateLegacy(){const l=state.legacy||{},o=state.ops||{};o.tests=mergeUnique(o.tests||[],l.testPlans||l.tests||[]);o.modules=mergeUnique(o.modules||[],l.featureModules||l.modules||[]);o.decisions=mergeUnique(o.decisions||[],[...(l.decisions||[]),...(l.alerts||[]),...(l.approvals||[])]);o.packs=mergeUnique(o.packs||[],l.packLists||[]);o.balance=mergeUnique(o.balance||[],l.balanceReports||[]);localStorage.setItem(KEYS.ops,JSON.stringify(o));state.ops=o;saveAudit({kind:'Legacy migration',message:'Merged recognized legacy collections into v2 Operations. Existing v2 records were preserved.'});render()}
function runRegression(){const x=collect();const serial=JSON.stringify(state.ops);const parsed=JSON.parse(serial);const checks=[{name:'Project state round-trip',pass:!!parsed,detail:'Operations state serializes and parses.'},{name:'Draft identity',pass:x.drafts.every(d=>d.id&&d.name),detail:'Every v2 draft has an internal ID and name.'},{name:'Pack object arrays',pass:x.packs.every(p=>Array.isArray(p.objectIds)),detail:'Every Pack List has an object ID array.'},{name:'Test finding arrays',pass:x.tests.every(t=>Array.isArray(t.findings||[])),detail:'Every test has a findings collection.'},{name:'Feature readiness fields',pass:x.modules.every(m=>typeof m==='object'),detail:'Feature modules are structured records.'},{name:'Restore point availability',pass:(state.ops.restore||[]).length>0,detail:'At least one restore point exists.'},{name:'Stable local export',pass:serial.length>2,detail:`Exportable project state is ${serial.length.toLocaleString()} characters.`},{name:'Critical workflow linkage',pass:x.drafts.length===0||x.packs.length>0||x.tests.length>0,detail:'Authored work can be linked to Pack or testing evidence.'}];state.checks=checks;state.lastRun=new Date().toISOString();saveAudit({kind:'Regression',message:`${checks.filter(c=>c.pass).length}/${checks.length} checks passed.`});render()}
function buildPrompt(){const task=$('#aiTask').value,subject=$('#aiSubject').value.trim(),goal=$('#aiGoal').value.trim(),x=collect();const context={build:BUILD,task,subject,goal,counts:{drafts:x.drafts.length,packs:x.packs.length,balance:x.balance.length,tests:x.tests.length,modules:x.modules.length,work:x.work.length},relevantDrafts:x.drafts.filter(d=>!subject||`${d.name} ${d.stableId}`.toLowerCase().includes(subject.toLowerCase())).slice(0,10),openCriticalFindings:x.tests.flatMap(t=>t.findings||[]).filter(f=>String(f.severity||'').toLowerCase()==='critical')};const prompt=`You are assisting with the Multiversal tabletop RPG platform.\n\nTask: ${task}\nSubject: ${subject||'Project-wide'}\nGoal: ${goal||'Provide a structured, rules-aware review and actionable output.'}\n\nUse this AIOC context:\n${JSON.stringify(context,null,2)}\n\nRequirements:\n- Preserve stable IDs and provenance.\n- Separate suggestions from approved canonical changes.\n- Identify assumptions and missing evidence.\n- Produce field-by-field recommendations and a consolidated final draft.\n- Include balance, testing, dependency, and Pack implications when relevant.`;$('#promptOutput').innerHTML=`<h3>Contextual prompt</h3><textarea style="min-height:360px">${esc(prompt)}</textarea><button id="copyPrompt">Copy prompt</button>`;$('#copyPrompt').onclick=()=>navigator.clipboard.writeText(prompt)}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAudit(){download('multiversal-v2-finalization-audit.json',{build:BUILD,exportedAt:new Date().toISOString(),checks:state.checks,promotion:promotionChecks(),history:state.audit,legacyCollections:legacyCounts()})}
async function runAll(){state.legacy=read(KEYS.legacy,null);runRegression();saveAudit({kind:'Full audit',message:'Ran legacy scan, regression suite, integrity review, and promotion evaluation.'});state.tab='audit';render()}
function boot(){load();nav();render();$('#finalMenu').onclick=()=>document.querySelector('.ops-sidebar').classList.toggle('open');$('#exportAudit').onclick=exportAudit;$('#runAll').onclick=runAll}
boot();