const KEY='mv-aioc-v2-forensic-audit';
const TABS=[['overview','Overview'],['pages','Page Ledger'],['findings','Findings'],['tables','CSV & Tables'],['review','Review Queue'],['coverage','Coverage']];
const state={tab:'overview',pages:[],findings:[],csvFindings:[],summary:null,decisions:{},query:'',family:'',match:''};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)Object.assign(state,x)}catch{}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function nav(){auditNav.innerHTML=TABS.map(([k,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${l}</button>`).join('');auditNav.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;nav();render()})}
const stat=(v,l)=>`<div class="stat"><strong>${Number(v||0).toLocaleString()}</strong><span>${l}</span></div>`;
function allFindings(){return [...state.findings,...state.csvFindings]}
function filtered(){const q=state.query.toLowerCase();return allFindings().filter(f=>{const hay=`${f.title_candidate} ${f.text} ${f.locator} ${JSON.stringify(f.family_scores||{})}`.toLowerCase();return(!q||hay.includes(q))&&(!state.family||f.family_scores?.[state.family])&&(!state.match||f.match_state===state.match)})}
function overview(){const all=allFindings(),pages=state.pages.filter(x=>x.status==='complete'),families={};all.forEach(f=>Object.keys(f.family_scores||{}).forEach(k=>families[k]=(families[k]||0)+1));return `<section class="hero"><span class="badge">FORENSIC CORPUS AUDIT</span><h2>Legacy Coverage Operations</h2><p>Every PDF page and every aaaa CSV row is treated as potentially mechanically meaningful evidence.</p></section><section class="metrics">${stat(pages.length,'Pages completed')}${stat(all.length,'Findings loaded')}${stat(state.csvFindings.length,'CSV row findings')}${stat(all.filter(x=>x.match_state==='exact-name').length,'Exact matches')}${stat(all.filter(x=>x.match_state!=='exact-name').length,'Needs review')}</section><section class="grid two"><div class="panel"><h3>Family distribution</h3>${Object.entries(families).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="row"><b>${esc(k)}</b><span>${v}</span></div>`).join('')||'<div class="empty">Load runner output files.</div>'}</div><div class="panel"><h3>Audit discipline</h3><p>Do not infer completeness from headings. Rules and objects may appear in lore, examples, adventures, sidebars, tables, and unrelated sections.</p><p>Automatic matches remain suggestions until reviewed.</p></div></section>`}
function pages(){return `<section class="hero"><h2>Page Ledger</h2><p>Checkpoint status and finding density across the complete PDF.</p></section><section class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Page</th><th>Status</th><th>Characters</th><th>Findings</th></tr></thead><tbody>${state.pages.slice().sort((a,b)=>a.page-b.page).map(x=>`<tr><td>${x.page}</td><td>${esc(x.status)}</td><td>${Number(x.characters||0).toLocaleString()}</td><td>${x.findings||0}</td></tr>`).join('')}</tbody></table></div></section>`}
function toolbar(){const families=[...new Set(allFindings().flatMap(f=>Object.keys(f.family_scores||{})))].sort();const matches=[...new Set(allFindings().map(f=>f.match_state))].sort();return `<div class="toolbar"><input id="auditQ" placeholder="Search findings" value="${esc(state.query)}"><select id="familyFilter"><option value="">All families</option>${families.map(x=>`<option ${state.family===x?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="matchFilter"><option value="">All match states</option>${matches.map(x=>`<option ${state.match===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div>`}
function findings(){const list=filtered();return `<section class="hero"><h2>All Findings</h2><p>${list.length.toLocaleString()} matching PDF and CSV evidence records.</p></section><section class="panel">${toolbar()}<div class="cards">${list.slice(0,500).map(card).join('')||'<div class="empty">No findings loaded.</div>'}</div></section>`}
function card(f){const d=state.decisions[f.finding_id]||{};return `<article class="card"><span class="badge">${esc(f.source_kind)}</span><h3>${esc(f.title_candidate)}</h3><small>${esc(f.source_path)} · ${esc(f.locator)}</small><p>${esc(String(f.text||'').slice(0,500))}</p><small>Families: ${esc(Object.keys(f.family_scores||{}).join(', ')||'unclassified')} · Match: ${esc(f.match_state)}</small><div class="actions"><select data-decision="${f.finding_id}"><option value="">Needs review</option>${['verified-existing','new-object','partial-conversion','duplicate','conflict','not-game-content','defer'].map(x=>`<option ${d.state===x?'selected':''}>${x}</option>`).join('')}</select></div></article>`}
function tables(){const rows=state.csvFindings.concat(state.findings.filter(x=>x.table_shape));return `<section class="hero"><h2>CSV & Table Evidence</h2><p>Standalone aaaa rows and CSV-like blocks embedded inside the PDF.</p></section><section class="panel"><div class="cards">${rows.slice(0,500).map(card).join('')||'<div class="empty">No table evidence loaded.</div>'}</div></section>`}
function review(){const list=allFindings().filter(f=>f.match_state!=='exact-name'||!state.decisions[f.finding_id]);return `<section class="hero"><h2>Review Queue</h2><p>${list.length.toLocaleString()} records need a human classification or canonical decision.</p></section><section class="panel"><div class="cards">${list.slice(0,500).map(card).join('')||'<div class="empty">Review queue is clear.</div>'}</div></section>`}
function coverage(){const max=Math.max(0,...state.pages.map(x=>x.page||0)),done=new Set(state.pages.filter(x=>x.status==='complete').map(x=>x.page));const blocks=[];for(let start=1;start<=max;start+=50){let c=0;for(let p=start;p<start+50&&p<=max;p++)if(done.has(p))c++;blocks.push({start,end:Math.min(start+49,max),done:c,total:Math.min(50,max-start+1)})}return `<section class="hero"><h2>Coverage Heatmap</h2><p>Page-range completion independent of chapter structure.</p></section><section class="cards">${blocks.map(b=>`<article class="card"><h3>Pages ${b.start}–${b.end}</h3><p>${b.done}/${b.total} complete</p><progress max="${b.total}" value="${b.done}"></progress></article>`).join('')||'<div class="empty">No page ledger loaded.</div>'}</section>`}
function render(){auditView.innerHTML=({overview,pages,findings,tables,review,coverage}[state.tab])();bind()}
function bind(){$('#auditQ')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('#familyFilter')?.addEventListener('change',e=>{state.family=e.target.value;render()});$('#matchFilter')?.addEventListener('change',e=>{state.match=e.target.value;render()});document.querySelectorAll('[data-decision]').forEach(s=>s.onchange=()=>{state.decisions[s.dataset.decision]={state:s.value,at:new Date().toISOString()};save()})}
async function loadFiles(files){for(const file of files){const text=await file.text();const rows=file.name.endsWith('.jsonl')?text.split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x)):JSON.parse(text);if(file.name.includes('page-ledger'))state.pages=rows;else if(file.name.includes('csv-findings'))state.csvFindings=rows;else if(file.name.includes('findings'))state.findings=rows;else if(file.name.includes('summary'))state.summary=rows}save();render()}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'multiversal-forensic-audit-review',version:'1.0.0',createdAt:new Date().toISOString(),decisions:state.decisions,summary:state.summary},null,2)],{type:'application/json'}));a.download='multiversal-forensic-audit-review.json';a.click()}
load();nav();render();menuBtn.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');auditFiles.onchange=e=>loadFiles([...e.target.files]).catch(err=>alert(err.message));exportAudit.onclick=download;
