const KEY='mv-aioc-v2-object-factory-review';
const state={index:null,decisions:{},filters:{tier:'all',type:'all',pack:'all',q:''}};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const stat=(v,l)=>`<div class="stat"><strong>${Number(v||0).toLocaleString()}</strong><span>${esc(l)}</span></div>`;
function loadLocal(){try{state.decisions=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.decisions))}
async function load(){loadLocal();try{const r=await fetch('./audit-data/object-factory/object-factory-index.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);state.index=await r.json()}catch{}render()}
function options(values,current){return ['all',...values].map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${v==='all'?'All':esc(v)}</option>`).join('')}
function candidates(){let rows=state.index?.publishedSample||[];const f=state.filters;return rows.filter(x=>{const e=x.canonicalEnvelope||{};const text=`${e.name} ${e.objectType} ${x.recommendedPack} ${(e.provenance||[]).map(p=>p.sourcePath).join(' ')}`.toLowerCase();return(f.tier==='all'||x.candidateTier===f.tier)&&(f.type==='all'||e.objectType===f.type)&&(f.pack==='all'||x.recommendedPack===f.pack)&&(!f.q||text.includes(f.q.toLowerCase()))})}
function gateRows(g={}){return Object.entries(g).map(([k,v])=>`<span class="badge">${v?'✓':'○'} ${esc(k)}</span>`).join(' ')}
function card(x){const e=x.canonicalEnvelope||{},d=state.decisions[x.candidateId]||{};const src=(e.provenance||[])[0]||{};return `<article class="panel"><div class="row"><div><span class="badge">${esc(x.candidateTier)}</span> <span class="badge">${esc(e.objectType)}</span><h3>${esc(e.name)}</h3><small>${esc(src.sourcePath)} · ${esc(src.locator)}</small></div><strong>${Number(x.quality?.confidence||0).toFixed(1)}</strong></div><p>${esc((e.spec?.legacyText||'').slice(0,700))}</p><div class="row"><small>Pack</small><b>${esc(x.recommendedPack||'Unassigned')}</b></div><div>${gateRows(x.gates)}</div><div class="grid two"><label>Decision<select data-id="${esc(x.candidateId)}" class="decision"><option value="">Unreviewed</option>${['prepare-new','existing-object','partial-conversion','duplicate-evidence','conflict','not-game-content','deferred'].map(v=>`<option ${d.decision===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Canonical ID / note<input data-note="${esc(x.candidateId)}" value="${esc(d.note||'')}"></label></div></article>`}
function render(){const a=document.querySelector('#app');if(!state.index){a.innerHTML='<section class="hero"><span class="badge">WAITING FOR FACTORY RUN</span><h2>Canonical candidates have not been published yet.</h2><p>The active forensic workflow is building schema-oriented candidates. This page will populate automatically after the audit bot commits the factory index.</p></section>';bind();return}const idx=state.index,tiers=Object.keys(idx.tierCounts||{}),types=Object.keys(idx.objectTypeCounts||{}),packs=Object.keys(idx.packCounts||{});const rows=candidates();a.innerHTML=`<section class="hero"><span class="badge">OBJECT FACTORY</span><h2>Evidence becomes reviewable objects—not automatic canon.</h2><p>${esc(idx.authorityNote)}</p></section><section class="metrics">${stat(idx.sourcePromotionCandidateCount,'Promotion candidates')}${stat(idx.consolidatedCandidateCount,'Consolidated objects')}${stat(idx.duplicateEvidenceCollapsed,'Evidence collapsed')}${stat(idx.tierCounts?.['designer-review'],'Designer review')}${stat(idx.tierCounts?.['needs-structure'],'Needs structure')}${stat(idx.tierCounts?.['needs-retitling'],'Needs retitling')}</section><section class="panel"><div class="grid four"><label>Tier<select id="tier">${options(tiers,state.filters.tier)}</select></label><label>Type<select id="type">${options(types,state.filters.type)}</select></label><label>Pack<select id="pack">${options(packs,state.filters.pack)}</select></label><label>Search<input id="q" value="${esc(state.filters.q)}" placeholder="Name, source, pack"></label></div></section><section class="panel"><h3>Published review sample</h3><p class="muted">Showing ${rows.length} bounded candidates. Full factory batches remain in the workflow artifact.</p></section>${rows.map(card).join('')||'<section class="panel"><div class="empty">No candidates match these filters.</div></section>'}`;bind()}
function bind(){document.querySelector('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');for(const id of ['tier','type','pack','q']){const el=document.querySelector('#'+id);if(el)el.oninput=()=>{state.filters[id]=el.value;render()}}document.querySelectorAll('.decision').forEach(el=>el.onchange=()=>{const id=el.dataset.id;state.decisions[id]={...(state.decisions[id]||{}),decision:el.value,updatedAt:new Date().toISOString()};save()});document.querySelectorAll('[data-note]').forEach(el=>el.onchange=()=>{const id=el.dataset.note;state.decisions[id]={...(state.decisions[id]||{}),note:el.value,updatedAt:new Date().toISOString()};save()});document.querySelector('#exportBtn').onclick=()=>{const payload={format:'multiversal-object-factory-review-ledger',version:'1.0.0',createdAt:new Date().toISOString(),decisions:state.decisions};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='multiversal-object-factory-review-ledger.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}}
load();
