const BUILD='3.3.0-project-control';
const KEY='mv-aioc-v2-project-control';
const TABS=[['overview','Overview'],['queue','Work Queue'],['milestones','Milestones'],['releases','Release Train'],['health','Health Checks'],['recovery','Recovery']];
const MODULES=[
['mv-aioc-v2','Core Dashboard','./'],['mv-aioc-v2-operations','Operations Suite','./operations.html'],['mv-aioc-v2-finalization','Finalization Center','./finalization.html'],['mv-aioc-v2-content-completion','Content Completion','./content-completion.html'],['mv-aioc-v2-specialist-studio','Specialist Studio','./specialist-studio.html'],['mv-aioc-v2-canonical-certification','Canonical Certification','./canonical-certification.html'],['mv-aioc-v2-pack-certification','Pack Certification','./pack-certification.html'],['mv-aioc-v2-expert-evidence','Expert Evidence','./expert-evidence.html'],['mv-aioc-v2-ai-workflows','AI Workflows','./ai-workflows.html'],['mv-aioc-v2-database-integrity','Database Integrity','./database-integrity.html'],['mv-aioc-v2-completion-sprint','Completion Sprint','./completion-sprint.html']];
const state={tab:'overview',milestones:[],releases:[],manualTasks:[],history:[]};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random()}`;
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}}
function save(reason){state.history.unshift({id:uid(),at:new Date().toISOString(),reason});state.history=state.history.slice(0,250);localStorage.setItem(KEY,JSON.stringify(state))}
function parse(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function snapshot(){return MODULES.map(([key,name,url])=>{const raw=localStorage.getItem(key);let data=null,error='';if(raw){try{data=JSON.parse(raw)}catch(e){error=e.message}}return{key,name,url,present:raw!==null,bytes:raw?.length||0,data,error}})}
function nav(){pcNav.innerHTML=TABS.map(([k,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${l}</button>`).join('');pcNav.querySelectorAll('button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab))}
function openTab(k){state.tab=k;const m={overview:['Project Overview','Unified state, priorities, milestones, releases, and recovery'],queue:['Prioritized Work Queue','Generated blockers plus manually managed work'],milestones:['Milestones','Outcome-based completion targets and dependencies'],releases:['Release Train','Candidate scope, gates, and evidence'],health:['Cross-workspace Health','State readability, linkage, and recovery checks'],recovery:['Full Recovery','Export, import, snapshots, and rollback evidence']};pcTitle.textContent=m[k][0];pcSubtitle.textContent=m[k][1];nav();render();document.querySelector('.sidebar').classList.remove('open')}
const stat=(v,l)=>`<div class="stat"><strong>${Number(v).toLocaleString()}</strong><span>${l}</span></div>`;
function extractCounts(mods){let records=0,drafts=0,packs=0,tests=0,findings=0,features=0,receipts=0;for(const m of mods){const d=m.data||{};records=Math.max(records,d.records?.length||0);drafts=Math.max(drafts,d.drafts?.length||d.objects?.length||0);packs=Math.max(packs,d.packs?.length||0);tests=Math.max(tests,d.tests?.length||d.testPlans?.length||0);findings=Math.max(findings,d.findings?.filter?.(x=>x.status!=='resolved')?.length||0);features=Math.max(features,d.features?.length||d.featureModules?.length||0);receipts+=d.receipts?.length||d.certifications?.length||0}return{records,drafts,packs,tests,findings,features,receipts}}
function generatedQueue(mods){const q=[];mods.forEach(m=>{if(!m.present)q.push({priority:'High',title:`Initialize ${m.name}`,detail:'No local project state exists yet.',url:m.url});if(m.error)q.push({priority:'Critical',title:`Repair ${m.name} state`,detail:m.error,url:m.url})});const integ=mods.find(x=>x.key.includes('database-integrity'))?.data||{};const sprint=mods.find(x=>x.key.includes('completion-sprint'))?.data||{};const expert=mods.find(x=>x.key.includes('expert-evidence'))?.data||{};const fin=mods.find(x=>x.key.includes('finalization'))?.data||{};const unresolved=(integ.references||integ.missingReferences||[]).filter?.(x=>x.status!=='resolved')||[];if(unresolved.length)q.push({priority:'High',title:'Resolve missing references',detail:`${unresolved.length} unresolved references remain.`,url:'./database-integrity.html'});const blocked=(sprint.receipts||sprint.certifications||[]).filter?.(x=>x.state==='blocked'||x.status==='blocked')||[];if(blocked.length)q.push({priority:'High',title:'Repair blocked canonical objects',detail:`${blocked.length} certification blockers remain.`,url:'./completion-sprint.html'});const critical=(expert.findings||[]).filter?.(x=>String(x.severity).toLowerCase()==='critical'&&x.status!=='resolved')||[];if(critical.length)q.push({priority:'Critical',title:'Resolve critical findings',detail:`${critical.length} critical findings block release.`,url:'./expert-evidence.html'});if(!(fin.audits||fin.regressions||[]).length)q.push({priority:'Medium',title:'Run finalization regression suite',detail:'No recorded full regression evidence was found.',url:'./finalization.html'});return q.concat(state.manualTasks)}
function overview(){const mods=snapshot(),c=extractCounts(mods),q=generatedQueue(mods),healthy=mods.filter(x=>x.present&&!x.error).length,totalBytes=mods.reduce((n,x)=>n+x.bytes,0);return `<section class="hero"><span class="badge">UNIFIED PROJECT CONTROL</span><h2>Multiversal Development Headquarters</h2><p>One view across content, authoring, Packs, evidence, AI reviews, migration, and release readiness.</p></section><section class="metrics">${stat(healthy,'Healthy workspaces')}${stat(q.length,'Open work items')}${stat(state.milestones.filter(x=>x.status!=='complete').length,'Open milestones')}${stat(state.releases.filter(x=>x.status!=='released').length,'Active releases')}</section><section class="grid two"><div class="panel"><h3>Project evidence</h3><div class="metrics">${stat(c.records,'Loaded records')}${stat(c.drafts,'Working objects')}${stat(c.packs,'Pack Lists')}${stat(c.tests,'Test plans')}${stat(c.features,'Feature modules')}${stat(c.receipts,'Receipts')}</div></div><div class="panel"><h3>Immediate priorities</h3>${q.slice(0,8).map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${esc(x.priority)} · ${esc(x.detail)}</small></div><a class="button-label" href="${x.url||'#'}">Open</a></div>`).join('')||'<div class="empty">No generated blockers.</div>'}</div></section><section class="panel"><h3>Workspace inventory</h3>${mods.map(m=>`<div class="row"><div><b>${esc(m.name)}</b><small>${m.present?(m.error?'Unreadable state':`${m.bytes.toLocaleString()} bytes`):'Not initialized'}</small></div><a class="button-label" href="${m.url}">${m.present&&!m.error?'Open':'Initialize'}</a></div>`).join('')}<p class="muted">Combined local state: ${totalBytes.toLocaleString()} bytes.</p></section>`}
function queueView(){const q=generatedQueue(snapshot());return `<section class="hero"><h2>Prioritized Work Queue</h2><p>Generated from current state plus manually entered work.</p></section><section class="panel"><form id="taskForm" class="fields"><label>Task<input name="title" required></label><label>Priority<select name="priority"><option>Critical</option><option>High</option><option selected>Medium</option><option>Low</option></select></label><label class="wide">Detail<textarea name="detail"></textarea></label><button class="primary">Add work item</button></form></section><section class="panel">${q.sort((a,b)=>['Critical','High','Medium','Low'].indexOf(a.priority)-['Critical','High','Medium','Low'].indexOf(b.priority)).map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${esc(x.priority)} · ${esc(x.detail||'')}</small></div>${x.id?`<button data-done-task="${x.id}">Complete</button>`:`<a class="button-label" href="${x.url||'#'}">Open</a>`}</div>`).join('')||'<div class="empty">No open work.</div>'}</section>`}
function milestones(){return `<section class="hero"><h2>Outcome-based Milestones</h2><p>Track dependencies and acceptance evidence rather than vague percentages.</p></section><section class="panel"><form id="milestoneForm" class="fields"><label>Name<input name="name" required></label><label>Target date<input name="target" type="date"></label><label>Status<select name="status"><option>planned</option><option>active</option><option>blocked</option><option>complete</option></select></label><label class="wide">Acceptance criteria<textarea name="criteria"></textarea></label><label class="wide">Dependencies<input name="dependencies" placeholder="comma-separated milestone names"></label><button class="primary">Add milestone</button></form></section><section class="cards">${state.milestones.map(m=>`<article class="card"><span class="badge">${esc(m.status)}</span><h3>${esc(m.name)}</h3><p>${esc(m.criteria||'No acceptance criteria yet.')}</p><small>${esc(m.target||'No target date')} · Dependencies: ${esc((m.dependencies||[]).join(', ')||'None')}</small><div class="actions"><button data-cycle-ms="${m.id}">Advance status</button><button data-delete-ms="${m.id}">Delete</button></div></article>`).join('')||'<div class="empty">No milestones yet.</div>'}</section>`}
function releases(){return `<section class="hero"><h2>Release Train</h2><p>Build candidates from explicit scope and evidence gates.</p></section><section class="panel"><form id="releaseForm" class="fields"><label>Release name<input name="name" required></label><label>Version<input name="version" required></label><label>Status<select name="status"><option>planning</option><option>candidate</option><option>blocked</option><option>approved</option><option>released</option></select></label><label class="wide">Scope<textarea name="scope"></textarea></label><label class="wide">Required gates<input name="gates" value="schema, dependencies, balance, testing, importer, owner approval"></label><button class="primary">Add release</button></form></section><section class="cards">${state.releases.map(r=>{const gates=r.gates||[];return`<article class="card"><span class="badge">${esc(r.status)}</span><h3>${esc(r.name)} ${esc(r.version)}</h3><p>${esc(r.scope||'No scope defined.')}</p><ul>${gates.map(g=>`<li>${r.evidence?.[g]?'✓':'○'} ${esc(g)}</li>`).join('')}</ul><div class="actions"><button data-toggle-gate="${r.id}">Update gates</button><button data-cycle-rel="${r.id}">Advance status</button><button data-export-rel="${r.id}">Export receipt</button></div></article>`}).join('')||'<div class="empty">No release candidates yet.</div>'}</section>`}
function health(){const mods=snapshot();const checks=[];mods.forEach(m=>{checks.push({name:`${m.name} state present`,pass:m.present,detail:m.present?'Local state found':'Workspace has not created local state'});checks.push({name:`${m.name} JSON readable`,pass:!m.present||!m.error,detail:m.error||'Readable'})});const exportable=(()=>{try{JSON.stringify({modules:mods.map(x=>[x.key,x.data])});return true}catch{return false}})();checks.push({name:'Full project state serializes',pass:exportable,detail:exportable?'Pass':'Serialization failed'});checks.push({name:'At least one recovery source exists',pass:mods.some(x=>x.present),detail:'Local states can be included in a unified backup'});return `<section class="hero"><h2>Cross-workspace Health</h2><p>Checks state presence, readability, portability, and recovery readiness.</p></section><section class="metrics">${stat(checks.filter(x=>x.pass).length,'Passing checks')}${stat(checks.filter(x=>!x.pass).length,'Warnings')}${stat(mods.filter(x=>x.present).length,'Initialized modules')}${stat(mods.reduce((n,x)=>n+x.bytes,0),'Stored bytes')}</section><section class="panel">${checks.map(x=>`<div class="row"><div><b>${x.pass?'✓':'⚠'} ${esc(x.name)}</b><small>${esc(x.detail)}</small></div><span class="badge">${x.pass?'pass':'review'}</span></div>`).join('')}</section>`}
function recovery(){return `<section class="hero"><h2>Full-project Recovery</h2><p>Back up every known v2 workspace together, without requiring a server or paid service.</p></section><section class="grid two"><div class="panel"><h3>Unified backup</h3><p>Exports all known v2 local-storage records, project-control state, build metadata, and a checksum-like item count.</p><button id="exportAll2" class="primary">Export full project bundle</button></div><div class="panel"><h3>Restore policy</h3><p>Import previews the bundle and requires confirmation before replacing matching local keys. Unknown keys are ignored.</p><label class="button-label">Choose backup<input id="importAll2" type="file" accept="application/json" hidden></label></div></section><section class="panel"><h3>Recovery history</h3>${state.history.map(h=>`<div class="row"><b>${esc(h.reason)}</b><small>${esc(h.at)}</small></div>`).join('')||'<div class="empty">No project-control history yet.</div>'}</section>`}
function render(){pcView.innerHTML=({overview,queue:queueView,milestones,releases,health,recovery}[state.tab])();bind()}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bundle(){const modules={};MODULES.forEach(([k])=>{if(localStorage.getItem(k)!==null)modules[k]=localStorage.getItem(k)});modules[KEY]=JSON.stringify(state);return{format:'multiversal-aioc-v2-full-backup',version:'1.0.0',build:BUILD,createdAt:new Date().toISOString(),moduleCount:Object.keys(modules).length,modules}}
async function importBundle(file){const data=JSON.parse(await file.text());if(data.format!=='multiversal-aioc-v2-full-backup'||!data.modules)throw new Error('Not a recognized full-project backup');const allowed=new Set([...MODULES.map(x=>x[0]),KEY]);const entries=Object.entries(data.modules).filter(([k])=>allowed.has(k));if(!confirm(`Restore ${entries.length} recognized project-state records? Existing matching local data will be replaced.`))return;entries.forEach(([k,v])=>localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v)));location.reload()}
function bind(){
$('#taskForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.manualTasks.push({id:uid(),title:f.get('title'),priority:f.get('priority'),detail:f.get('detail')});save('added manual work item');render()});
document.querySelectorAll('[data-done-task]').forEach(b=>b.onclick=()=>{state.manualTasks=state.manualTasks.filter(x=>x.id!==b.dataset.doneTask);save('completed manual work item');render()});
$('#milestoneForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.milestones.push({id:uid(),name:f.get('name'),target:f.get('target'),status:f.get('status'),criteria:f.get('criteria'),dependencies:String(f.get('dependencies')||'').split(',').map(x=>x.trim()).filter(Boolean)});save('added milestone');render()});
document.querySelectorAll('[data-cycle-ms]').forEach(b=>b.onclick=()=>{const m=state.milestones.find(x=>x.id===b.dataset.cycleMs),s=['planned','active','blocked','complete'];m.status=s[(s.indexOf(m.status)+1)%s.length];save(`updated milestone ${m.name}`);render()});document.querySelectorAll('[data-delete-ms]').forEach(b=>b.onclick=()=>{state.milestones=state.milestones.filter(x=>x.id!==b.dataset.deleteMs);save('deleted milestone');render()});
$('#releaseForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),g=String(f.get('gates')||'').split(',').map(x=>x.trim()).filter(Boolean);state.releases.push({id:uid(),name:f.get('name'),version:f.get('version'),status:f.get('status'),scope:f.get('scope'),gates:g,evidence:Object.fromEntries(g.map(x=>[x,false]))});save('added release candidate');render()});
document.querySelectorAll('[data-toggle-gate]').forEach(b=>b.onclick=()=>{const r=state.releases.find(x=>x.id===b.dataset.toggleGate),g=prompt(`Gate to toggle:\n${r.gates.join(', ')}`);if(g&&r.gates.includes(g)){r.evidence[g]=!r.evidence[g];save(`updated release gate ${g}`);render()}});document.querySelectorAll('[data-cycle-rel]').forEach(b=>b.onclick=()=>{const r=state.releases.find(x=>x.id===b.dataset.cycleRel),s=['planning','candidate','blocked','approved','released'];r.status=s[(s.indexOf(r.status)+1)%s.length];save(`updated release ${r.name}`);render()});document.querySelectorAll('[data-export-rel]').forEach(b=>b.onclick=()=>{const r=state.releases.find(x=>x.id===b.dataset.exportRel);download(`${r.version}-release-receipt.json`,{format:'multiversal-aioc-release-receipt',build:BUILD,generatedAt:new Date().toISOString(),release:r,allGatesPass:r.gates.every(g=>r.evidence?.[g])})});
$('#exportAll2')?.addEventListener('click',()=>download('multiversal-aioc-v2-full-backup.json',bundle()));$('#importAll2')?.addEventListener('change',e=>importBundle(e.target.files[0]).catch(err=>alert(err.message)))}
function boot(){load();nav();pcMenu.onclick=()=>document.querySelector('.sidebar').classList.toggle('open');exportAll.onclick=()=>download('multiversal-aioc-v2-full-backup.json',bundle());importAll.onchange=e=>importBundle(e.target.files[0]).catch(err=>alert(err.message));render()}
boot();