const BUILD='2.6.0-specialists';
const KEY='mv-aioc-v2-specialists';
const TYPES={
 NPC:{fields:[['role','Role'],['speciesId','Species reference'],['professionId','Profession reference'],['disposition','Disposition'],['attributes','Attributes / ratings'],['abilities','Ability references'],['equipment','Equipment references'],['motivation','Motivation'],['tactics','Tactics']]},
 Species:{fields:[['classification','Classification'],['size','Size'],['lifespan','Lifespan'],['homeworldId','Homeworld reference'],['traits','Trait references'],['adaptations','Environmental adaptations'],['languages','Languages'],['cultures','Culture references']]},
 Spell:{fields:[['discipline','Discipline'],['tier','Tier'],['castingTime','Casting time'],['range','Range'],['duration','Duration'],['resourceCost','Resource cost'],['effects','Effect references'],['requirements','Requirements'],['counterplay','Counterplay']]},
 Ship:{fields:[['shipClass','Ship class'],['scale','Scale'],['crew','Crew'],['capacity','Capacity'],['speed','Speed'],['defenses','Defenses'],['weapons','Weapon references'],['modules','Module references'],['operatingCosts','Operating costs']]},
 Mecha:{fields:[['frame','Frame'],['scale','Scale'],['pilotRequirements','Pilot requirements'],['power','Power'],['mobility','Mobility'],['armor','Armor'],['weapons','Weapon references'],['modules','Module references'],['heat','Heat / strain']]},
 Environment:{fields:[['environmentType','Environment type'],['severity','Severity'],['hazards','Hazard references'],['adaptations','Adaptation references'],['movementRules','Movement rules'],['visibility','Visibility'],['resources','Resource references'],['encounters','Encounter references']]},
 Adventure:{fields:[['premise','Premise'],['recommendedTier','Recommended tier'],['objectives','Objective references'],['scenes','Scenes'],['encounters','Encounter references'],['clues','Clue references'],['rewards','Reward references'],['failureStates','Failure states']]},
 Quest:{fields:[['questType','Quest type'],['giverId','Quest giver reference'],['objectives','Objective references'],['prerequisites','Prerequisite references'],['rewards','Reward references'],['branches','Branches'],['failureStates','Failure states']]},
 Effect:{fields:[['effectType','Effect type'],['targeting','Targeting'],['magnitude','Magnitude'],['duration','Duration'],['stacking','Stacking'],['resistance','Resistance'],['conditions','Condition references'],['resolution','Resolution']]},
 Condition:{fields:[['conditionType','Condition type'],['severity','Severity'],['duration','Duration'],['triggers','Triggers'],['modifiers','Modifiers'],['removal','Removal'],['immunities','Immunity references'],['escalation','Escalation']]},
 Action:{fields:[['actionType','Action type'],['cost','Action cost'],['targeting','Targeting'],['check','Check / roll'],['effects','Effect references'],['requirements','Requirements'],['interrupts','Interrupts'],['failure','Failure outcome']]},
 Resource:{fields:[['resourceType','Resource type'],['maximum','Maximum'],['refresh','Refresh'],['spendRules','Spend rules'],['gainRules','Gain rules'],['overflow','Overflow'],['linkedSystems','Linked-system references']]}
};
const state={source:[],local:[],selected:null,query:'',type:'NPC'};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>crypto.randomUUID?.()||`local-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function loadLocal(){try{state.local=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{state.local=[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state.local))}
async function loadSource(){try{const m=await import('./data/source-loader.js');const p=await m.loadSourceRecords();state.source=(p.records||[]).map((r,i)=>({id:r.id||r.stableId||`source-${i}`,name:r.name||r.title||r.id||'Unnamed',objectType:r.objectKind||r.objectType||r.type||'Unclassified',gameObject:r.gameObject||r,source:true}))}catch(e){console.warn(e)}}
function all(){return [...state.local,...state.source.filter(r=>TYPES[r.objectType])];}
function fillTypes(){const opts=Object.keys(TYPES).map(t=>`<option>${t}</option>`).join('');$('#type').innerHTML=`<option value="">All specialist types</option>${opts}`;$('#newType').innerHTML=opts;}
function filtered(){return all().filter(r=>(!state.type||r.objectType===state.type)&&(!state.query||`${r.name} ${r.id} ${r.objectType}`.toLowerCase().includes(state.query)));}
function renderList(){const rows=filtered();$('#objectList').innerHTML=`<h3>${rows.length} specialist objects</h3>${rows.slice(0,600).map(r=>`<button data-id="${esc(r.id)}" class="${state.selected===r.id?'active':''}"><b>${esc(r.name)}</b><br><small>${esc(r.objectType)} · ${r.source?'repository source':esc(r.stage||'Draft')}</small></button>`).join('')||'<div class="empty">No matching objects.</div>'}`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.id;render()})}
function current(){return all().find(r=>r.id===state.selected)}
function refs(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean)}
function validation(r){const errors=[];if(!r.name?.trim())errors.push('Name is required.');if(!/^[a-z0-9][a-z0-9._:-]{2,}$/i.test(r.id||''))errors.push('Stable ID must be at least three characters and use letters, numbers, dots, colons, underscores, or hyphens.');const profile=TYPES[r.objectType];for(const [key,label] of profile.fields.slice(0,3))if(!String(r.spec?.[key]||'').trim())errors.push(`${label} is not yet defined.`);for(const dep of r.dependencies||[])if(!all().some(x=>x.id===dep))errors.push(`Missing referenced object: ${dep}`);return errors}
function editor(r){if(!r)return '<div class="empty">Select or create an object.</div>';const profile=TYPES[r.objectType];const readOnly=r.source;const errors=validation(r);return `<div class="panel-head"><div><span class="badge">${esc(r.objectType)}</span><h2>${esc(r.name)}</h2><p class="muted">${esc(r.id)}</p></div>${readOnly?'<button id="fork">Create editable copy</button>':'<button id="delete">Delete local object</button>'}</div><div class="field-grid"><label>Name<input id="name" value="${esc(r.name)}" ${readOnly?'disabled':''}></label><label>Stable ID<input id="stable" value="${esc(r.id)}" ${readOnly?'disabled':''}></label><label>Stage<select id="stage" ${readOnly?'disabled':''}>${['Draft','Review','Balance','Testing','Approved','Released'].map(x=>`<option ${r.stage===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Tags<input id="tags" value="${esc((r.tags||[]).join(', '))}" ${readOnly?'disabled':''}></label>${profile.fields.map(([key,label])=>`<label class="${['motivation','tactics','premise','scenes','branches','resolution','modifiers','removal','spendRules','gainRules'].includes(key)?'wide':''}">${esc(label)}<textarea data-field="${key}" ${readOnly?'disabled':''}>${esc(r.spec?.[key]||'')}</textarea></label>`).join('')}<label class="wide">Declared dependencies<input id="deps" value="${esc((r.dependencies||[]).join(', '))}" ${readOnly?'disabled':''}></label><label class="wide">Manual entry<textarea id="manual" ${readOnly?'disabled':''}>${esc(r.manualEntry||'')}</textarea></label></div>${readOnly?'':`<div class="top-actions"><button id="save" class="primary">Save specialist object</button><button id="export">Export JSON</button></div>`}<h3>Validation summary</h3><div class="checks">${errors.length?errors.map(e=>`<div class="check bad">${esc(e)}</div>`).join(''):'<div class="check good">Identity, profile minimums, and declared references currently pass.</div>'}</div><h3>Structured preview</h3><pre>${esc(JSON.stringify(toCanonical(r),null,2))}</pre>`}
function toCanonical(r){return{id:r.id,name:r.name,objectKind:r.objectType,schemaVersion:'specialist-1',contentVersion:'0.1.0',canonStatus:r.stage==='Approved'||r.stage==='Released'?'approved':'draft',lifecycleStatus:(r.stage||'Draft').toLowerCase(),tags:r.tags||[],dependencies:r.dependencies||[],spec:r.spec||{},manualEntry:r.manualEntry||'',provenance:{source:r.source?'Repository source':'AIOC v2 Specialist Studio',updatedAt:r.updatedAt||new Date().toISOString()}}}
function render(){renderList();$('#editor').innerHTML=editor(current());bindEditor()}
function bindEditor(){const r=current();if(!r)return;$('#fork')?.addEventListener('click',()=>{const copy={...structuredClone(r),source:false,id:`${r.id}.working`,stage:'Draft',updatedAt:new Date().toISOString()};state.local.unshift(copy);state.selected=copy.id;save();render()});$('#delete')?.addEventListener('click',()=>{state.local=state.local.filter(x=>x.id!==r.id);state.selected=null;save();render()});$('#save')?.addEventListener('click',()=>{r.name=$('#name').value.trim();r.id=$('#stable').value.trim();r.stage=$('#stage').value;r.tags=refs($('#tags').value);r.dependencies=refs($('#deps').value);r.manualEntry=$('#manual').value;r.spec={};document.querySelectorAll('[data-field]').forEach(x=>r.spec[x.dataset.field]=x.value);r.updatedAt=new Date().toISOString();save();render()});$('#export')?.addEventListener('click',()=>download(`${r.id}.json`,toCanonical(r)))}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function boot(){loadLocal();fillTypes();await loadSource();$('#type').value='NPC';$('#search').oninput=e=>{state.query=e.target.value.toLowerCase();render()};$('#type').onchange=e=>{state.type=e.target.value;render()};$('#newObject').onclick=()=>$('#newDialog').showModal();$('#createObject').onclick=e=>{e.preventDefault();const d=Object.fromEntries(new FormData($('#newForm')));const r={id:`${d.type.toLowerCase()}.${uid().slice(0,8)}`,name:d.name,objectType:d.type,stage:'Draft',tags:[],dependencies:[],spec:{},manualEntry:'',source:false,createdAt:new Date().toISOString()};state.local.unshift(r);state.selected=r.id;state.type=r.objectType;save();$('#newDialog').close();render()};$('#exportAll').onclick=()=>download('multiversal-specialist-objects.json',{format:'multiversal-specialist-objects',build:BUILD,records:state.local});render()}
boot();