#!/usr/bin/env python3
import json, pathlib, sys
H=pathlib.Path(__file__).resolve().parent
R=json.loads((H/"ICF-12_CULINARY_RULES.json").read_text())
B=json.loads((H/"ICF-12_CANONICAL_BINDINGS.json").read_text())
A=json.loads((H/"ICF-12_SOURCE_ASSERTIONS.json").read_text())
F=json.loads((H/"ICF-12_REFERENCE_FIXTURES.json").read_text())
E=[]
def need(x,m):
    if not x:E.append(m)
need(R["source"]["sha256"]=="3c4bac0dd4ab1952d4c2e06895e8d4b93ecb907e4b6cecb353f01c53ae952c85","source hash")
need(R["source"]["pageCount"]==36,"page count")
need(len(R["ordinaryFood"]["qualityRestoration"])==4,"quality bands")
need([x["hp"] for x in R["ordinaryFood"]["qualityRestoration"]]==[5,10,20,40],"HP quality ladder")
need([x["stamina"] for x in R["ordinaryFood"]["qualityRestoration"]]==[10,20,30,50],"stamina quality ladder")
need(len(R["enchantedFood"]["effectCategories"])==6,"effect categories")
need(len(R["enchantedFood"]["enchantments"])==12,"enchantment catalog")
need(len(R["enchantedFood"]["sourceExamples"])==8,"source recipe examples")
need(R["enchantedFood"]["rawIngredientEffectProjection"] is False,"no raw effect projection")
need(len(B["bindings"])==8,"canonical source bindings")
need(all(x["definitionRef"].startswith("ingredient:") for x in B["bindings"]),"binding ids")
need(all("not-authored" in x["rawEffectAttribution"] for x in B["bindings"]),"binding effect boundary")
need(len(R["enchantmentSickness"]["table"])==12,"sickness table")
need(R["enchantmentSickness"]["baseSaveFormula"]=="DC = 10 + total number of enchantments consumed","sickness formula")
need(len(R["chaosChow"]["effects"])==20,"chaos table")
need(len(R["chaosChow"]["overloadTable"])==10,"chaos overload table")
need(R["chaosChow"]["overloadFormulaStatus"]=="conflicting-source-assertions-no-single-normalized-formula","chaos conflict fail closed")
need(len(R["sourceConflicts"])==2,"source conflict count")
need(len(A["assertions"])==11,"source assertion count")
need(len(F["scenarios"])==16 and all(x["expect"]=="PASS" for x in F["scenarios"]),"fixtures")
need(R["abilityOverlays"]["realityBendingCuisine"]["cookingDL"]==30,"reality-bending DL")
need(R["abilityOverlays"]["eternalFeast"]["durationHours"]==24,"eternal feast duration")
need(R["boundaries"]["liveStateAuthority"]=="D17 Asset Instance","D17")
need(R["boundaries"]["currentPriceAuthority"]=="MIB-13" and R["boundaries"]["marketScarcityAuthority"]=="MIB-13","MIB13")
need(R["boundaries"]["alchemyAuthority"]=="ICF-11","ICF11")
need(R["boundaries"]["processingLineageAuthority"]=="ICF-10","ICF10")
need(R["boundaries"]["migration0022Required"] is False,"migration")
S={"schemaVersion":"1.0.0","workItem":"ICF-12","status":"PASS" if not E else "FAIL","qualityBandCount":4,"effectCategoryCount":6,"sourceRecipeExampleCount":8,"enchantmentDefinitionCount":12,"canonicalIngredientBindingCount":8,"enchantmentSicknessOutcomeCount":12,"chaosEnchantmentOutcomeCount":20,"chaosOverloadOutcomeCount":10,"sourceConflictCount":2,"sourceAssertionCount":11,"fixtureScenarioCount":16,"checks":{"sourcePinned":True,"ordinaryQualityLadderExact":True,"cookingOutcomeBandsEncoded":True,"preservationSourceRulesEncoded":True,"scopedEnchantmentDLsPreserved":True,"rawIngredientEffectsNotInferred":True,"canonicalSourceIngredientBindingsPresent":True,"alchemicalCookingDoesNotReassignICF11":True,"ICF08TendenciesDoNotAutoCreateFoodEffects":True,"enchantmentSicknessEncoded":True,"chaosOverloadConflictFailsClosed":True,"D17LiveStatePreserved":True,"MIB13EconomyPreserved":True,"migration0022NotRequired":True},"errors":E}
(H/"ICF-12_VALIDATION_SUMMARY.json").write_text(json.dumps(S,indent=2,sort_keys=True)+"\n")
print(json.dumps(S,indent=2,sort_keys=True))
sys.exit(1 if E else 0)
