#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
P06=ROOT/'governance/application-planning/parallel-preimplementation'; OUT=ROOT/'governance/application-planning/character-appearance-production'
SOURCES={'morphology':P06/'PPIA-06_SPECIES_MORPHOLOGY_PROFILES_v0.1.0.json','semantics':P06/'PPIA-06_APPEARANCE_SEMANTIC_TAXONOMY_v0.2.0.json','studio':P06/'PPIA-06_APPEARANCE_STUDIO_CONTROL_SURFACE_v0.1.0.json','owner_decisions':P06/'PPIA-06_OWNER_VISUAL_CANON_DECISIONS_v0.1.0.json','biology':P06/'PPIA-05_SPECIES_FORMS_BIOLOGY_TAXONOMY_v0.1.0.json'}
INDEX=OUT/'CAPP-01_SOURCE_AUTHORITY_AND_PROFILE_INDEX_v0.1.0.json'; REGISTRY=OUT/'CAPP-01_APPEARANCE_CHOICE_REGISTRY_v0.1.0.json'; CONSTRAINTS=OUT/'CAPP-01_CONSTRAINT_MODEL_v0.1.0.json'; REPORT=OUT/'CAPP-01_FOUNDATION_REPORT.md'
SURFACES=['P06-UI-002','P06-UI-003','P06-UI-004','P06-UI-005','P06-UI-006','P06-UI-007','P06-UI-008','P06-UI-009','P06-UI-010','P06-UI-011']
EXPLICIT={
'Dwarf':{'beard':{'stable_id':'CAPP01-DWARF-BEARD','kind':'conditional_control','eligibility':'eligible_regardless_of_sex','source':['OVC-015'],'mechanics_effect':False}},
'Orc':{'visible_tusks':{'stable_id':'CAPP01-ORC-VISIBLE-TUSKS','kind':'optional_presentation','eligibility':'optional','source':['OVC-014'],'mechanics_effect':False}},
'Giantkin':{'lineage':{'stable_id':'CAPP01-GIANTKIN-LINEAGE','kind':'enumerated_profile_choice','values':['Grendelkin','Surtrborn','Daityr'],'forbidden_legacy_labels':['Skyborn','Stoneborn','Flameborn'],'source':['OVC-021']}},
'Stygian':{'horns':{'stable_id':'CAPP01-STYGIAN-HORNS','kind':'optional_source_bounded_control','eligibility':'optional','source':['OVC-001']},'wings':{'stable_id':'CAPP01-STYGIAN-WINGS','kind':'conditional_control','eligibility':'optional','mechanics_authority':'upstream functional/vestigial state; appearance never grants flight','source':['OVC-001','OVC-002']},'pointed_ears':{'stable_id':'CAPP01-STYGIAN-POINTED-EARS','kind':'forbidden_noncanon','eligibility':'unavailable','source':['OVC-001']}},
'Furashin':{'fur_phenotype':{'stable_id':'CAPP01-FURASHIN-FUR-PHENOTYPE','kind':'live_dynamic_phenotype','max_simultaneous_colors':3,'fields':['color','pattern','texture'],'saved_state':'preferred_fur_phenotype','live_state':'upstream_when_mechanics_controls_current_phenotype','source':['OVC-005']}},
'Vespin':{'topology':{'stable_id':'CAPP01-VESPIN-TOPOLOGY','kind':'required_topology','arms':4,'legs':2,'requires':['compound eyes','2 antennae','wing pair','prominent wasp abdomen/stinger'],'source':['OVC-003']}},
'Moravi':{'topology':{'stable_id':'CAPP01-MORAVI-TOPOLOGY','kind':'required_topology','arms':2,'legs':4,'requires':['compound eyes','antennae','mandibles','exoskeleton'],'renderer_anchor_policy':'six_limb_no_two_leg_collapse'}},
'Rakuuta':{'facial_feathers':{'stable_id':'CAPP01-RAKUUTA-FACIAL-FEATHERS','kind':'required_feature','value':'black raven-shaped facial feather field','source':['OVC-004']},'horns':{'stable_id':'CAPP01-RAKUUTA-HORNS','kind':'forbidden_noncanon','eligibility':'unavailable','source':['OVC-004']},'swept_back_structures':{'stable_id':'CAPP01-RAKUUTA-EARS','kind':'required_identity','value':'ears_not_horns','source':['OVC-004']}},
'Traiga':{'wing_pair':{'stable_id':'CAPP01-TRAIGA-EXTRA-WINGS','kind':'forbidden_base_topology','eligibility':'unavailable','source':['OVC-009']},'surface_spectrum':{'stable_id':'CAPP01-TRAIGA-SURFACE-SPECTRUM','kind':'source_bounded_choice','values':['feathered','scaled','mixed'],'condition':'variant permits','source':['OVC-009']}},
'Kola-Ha':{'bioengineering_forms':{'stable_id':'CAPP01-KOLA-HA-BIOENGINEERING-FORMS','kind':'upstream_form_profile','baseline_mutation':False,'source':['OVC-007']}},
'Toba-Madra':{'fur_channel':{'stable_id':'CAPP01-TOBA-MADRA-FUR','kind':'split_channel','biological':'natural bear-range colors','cosmetic':'any-color/pattern dye overlay','source':['OVC-017']},'cybernetics':{'stable_id':'CAPP01-TOBA-MADRA-CYBERNETICS','kind':'equipment_projection','editable_as_identity':False,'cosmetic_plating_separate':True,'source':['OVC-018']}},
'Arborae':{'season_profiles':{'stable_id':'CAPP01-ARBORAE-SEASONS','kind':'linked_profile_set','values':['spring','summer','autumn','winter'],'current_state':'upstream_read_only','independently_customizable':True,'source':['OVC-010']}},
'Mythragara':{'hybrid':{'stable_id':'CAPP01-MYTHRAGARA-HYBRID','kind':'derived_profile','editable_independently':False,'derived_from':['base_humanoid','authorized_animal_form'],'source':['OVC-008']}},
'Suula':{'persistent_adaptation_markers':{'stable_id':'CAPP01-SUULA-PERSISTENT-ADAPTATIONS','kind':'source_owned_history','editable':False,'erasable':False,'source':['OVC-011']},'active_adaptations':{'stable_id':'CAPP01-SUULA-ACTIVE-ADAPTATIONS','kind':'live_upstream_projection','editable':False,'source':['OVC-011']},'hand_claw_pose':{'stable_id':'CAPP01-SUULA-HAND-CLAW-POSE','kind':'live_pose_state','saved_identity':False,'source':['OVC-011']}},
'Nekron':{'ascension':{'stable_id':'CAPP01-NEKRON-ASCENSION','kind':'one_time_transition_profile','values':['Revenant','Sanguivore','Fragmentarii'],'transition_count_max':1,'selection_authority':'upstream availability/outcome','second_customization_pass':True,'derived_from':'base','source':['OVC-012']}},
'ManyToms':{'constituent_identity':{'stable_id':'CAPP01-MANYTOMS-CONSTITUENT','kind':'composite_entity_identity','design_once_replicate':True,'exact_visible_count_required':False,'lore_count_context':17,'source':['OVC-013']}},
'The Free':{'topology_scope':{'stable_id':'CAPP01-THE-FREE-TOPOLOGY','kind':'topology_boundary','allowed':'broad humanoid android','forbidden':'arbitrary nonhumanoid topology','actual_replacement_hardware':'mechanics_owned','source':['OVC-020']}},
'Gray':{'hair':{'stable_id':'CAPP01-GRAY-HAIR','kind':'forbidden_anatomy','eligibility':'unavailable','source':['OVC-016']},'external_ears':{'stable_id':'CAPP01-GRAY-EARS','kind':'forbidden_anatomy','eligibility':'unavailable','source':['OVC-016']}},
'Sharr':{'facial_morphology':{'stable_id':'CAPP01-SHARR-FACE','kind':'required_feature_group','requires':['heavy brow','broad nose','robust facial structure'],'source':['OVC-019']}},
}
def read(p): return json.loads(p.read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def slug(s): return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')
def pref(s): return 'CAPP01-'+slug(s).upper().replace('_','-')
def dump(o): return json.dumps(o,indent=2,ensure_ascii=False)+'\n'
def surface_class(s):
 if s['id'] in ('P06-UI-009','P06-UI-011'): return 'presentation_only'
 if s['id']=='P06-UI-010': return 'read_only_actual_equipment_projection'
 if s['id']=='P06-UI-008': return 'mixed_profile_authoring_and_upstream_read_only'
 if s['id']=='P06-UI-006': return 'mixed_authored_and_source_owned_read_only'
 return 'source_bounded_authored_identity'
def build():
 morph,sem,studio,owners,bio=[read(SOURCES[k]) for k in ('morphology','semantics','studio','owner_decisions','biology')]
 hashes={k:{'path':str(v.relative_to(ROOT)),'sha256':sha(v)} for k,v in SOURCES.items()}; owner={d['id']:d for d in owners['decisions']}; behaviors=studio.get('profile_behaviors',{})
 profiles=[]
 for p in morph['profiles']:
  profiles.append({'profile_id':'species.'+slug(p['species']),'species':p['species'],'written_source':p['written_source'],'baseline_topology':p['baseline_topology'],'visual_summary':p['visual_summary'],'required_features':p['required_features'],'bounded_variation':p['bounded_variation'],'appearance_state_model':p['appearance_state_model'],'special_customizer_behavior':p['special_customizer_behavior'],'owner_canon_ids':p['owner_canon'],'owner_canon_decisions':[owner[x]['decision'] for x in p['owner_canon'] if x in owner],'unresolved_visual_conflicts':p['unresolved_visual_conflicts'],'studio_profile_behavior':behaviors.get(p['species'])})
 index={'schema_version':'0.1.0','work_item_id':'CAPP-01','title':'Source Authority and Canonical 25-Profile Index','status':'foundation_candidate','authority_rule':'PPIA-06 morphology profiles are the canonical 25-profile appearance set; PPIA-05 remains biology truth and PPIA-03 remains actual equipment authority.','source_hashes':hashes,'profile_count':morph['profile_count'],'profiles':profiles,'source_truth_invariants':bio['source_guardrails']+sem['state_rules']}
 ui={x['id']:x for x in studio['inspector_sections']}; surfaces=[]
 for sid in SURFACES:
  s=ui[sid]; surfaces.append({'surface_id':sid,'name':s['name'],'semantic_layer_refs':s['layers'],'mode':s['mode'],'classification':surface_class(s),'canonical_contents':s['contents']})
 rp=[]
 for p in profiles:
  pr=pref(p['species']); req=[{'choice_id':f'{pr}-REQ-{i:03d}','kind':'required_source_owned_feature','classification':'biological_read_only_requirement','value':v,'provenance':{'written_source':p['written_source'],'owner_canon_ids':p['owner_canon_ids']}} for i,v in enumerate(p['required_features'],1)]; bounds=[{'choice_id':f'{pr}-BOUND-{i:03d}','kind':'source_bounded_authoring_constraint','classification':'source_bounded_identity_choice_space','statement':v,'provenance':{'written_source':p['written_source'],'owner_canon_ids':p['owner_canon_ids']}} for i,v in enumerate(p['bounded_variation'],1)]; elig=[]
  for s in surfaces:
   state='read_only' if s['surface_id']=='P06-UI-010' else ('unavailable' if s['surface_id']=='P06-UI-008' and p['appearance_state_model']=='single_profile' else 'conditional')
   elig.append({'surface_id':s['surface_id'],'state':state,'condition':'resolve source/profile/topology/current-form/permission constraints; renderer support does not determine identity validity'})
  rp.append({'profile_id':p['profile_id'],'species':p['species'],'topology_profile':p['baseline_topology'],'appearance_state_model':p['appearance_state_model'],'required_feature_contracts':req,'bounded_choice_contracts':bounds,'explicit_choice_contracts':EXPLICIT.get(p['species'],{}),'surface_eligibility':elig,'renderer_requirement':{'topology_profile':p['baseline_topology'],'support_state_owner':'renderer adapter','no_unrestricted_warp':True,'unsupported_does_not_invalidate_identity':True},'visibility_permission_behavior':'filter hidden biology/current Form/history/equipment before derivation, counts, diagnostics, export or AI context','unresolved_visual_conflicts':p['unresolved_visual_conflicts']})
 registry={'schema_version':'0.1.0','work_item_id':'CAPP-01','title':'Canonical 25-Species Appearance Choice Registry','status':'foundation_candidate','source_hashes':hashes,'profile_count':len(rp),'choice_surface_count':len(surfaces),'choice_surfaces':surfaces,'profiles':rp,'explicit_unknown_unavailable_semantics':{'unknown':'upstream source/authority insufficient; never synthesize human/humanoid default','unavailable':'resolved profile/topology/state makes the surface or value ineligible','conditional':'requires current source/profile/form/topology/permission resolution','read_only':'visible projection may be inspected but appearance editor does not own mutation'},'global_invariants':sem['state_rules']}
 generic=[{'rule_id':'CAPP01-GEN-001','type':'permission_first','effect':'Filter hidden biology/current Form/history/equipment before choices, counts, diagnostics, renderer derivation, export or AI context.'},{'rule_id':'CAPP01-GEN-002','type':'unknown_preservation','effect':'Unknown/source-unspecified anatomy remains unknown; no human/humanoid default is synthesized.'},{'rule_id':'CAPP01-GEN-003','type':'upstream_read_only','effect':'Current Form and persistent/active biological states are upstream projections and cannot be cosmetically rewritten.'},{'rule_id':'CAPP01-GEN-004','type':'topology_required','effect':'Required morphology graph nodes/cardinality must exist before topology-dependent authored choices or fit are eligible.'},{'rule_id':'CAPP01-GEN-005','type':'renderer_independence','effect':'Renderer supported/partial/unsupported/unknown never changes biological or identity validity.'},{'rule_id':'CAPP01-GEN-006','type':'wardrobe_nonmechanical','effect':'Presentation wardrobe is nonmechanical and never implies inventory/equipment ownership.'},{'rule_id':'CAPP01-GEN-007','type':'equipment_projection_read_only','effect':'Actual equipment preview is permission-safe PPIA-03 projection and never mutates Asset state.'},{'rule_id':'CAPP01-GEN-008','type':'randomization_scope','effect':'Randomization may change only eligible authored/cosmetic choices, never source-owned biology/history/current Form/equipment.'},{'rule_id':'CAPP01-GEN-009','type':'no_silent_substitution','effect':'If a committed choice becomes incompatible, return explicit review/diagnostic state; do not replace it silently.'},{'rule_id':'CAPP01-GEN-010','type':'ambiguous_mutation_recovery','effect':'On ambiguous mutation result, inspect authoritative operation/current state before retry.'}]
 pc=[{'profile_id':p['profile_id'],'species':p['species'],'topology_profile':p['baseline_topology'],'required_features':p['required_features'],'appearance_state_model':p['appearance_state_model'],'special_customizer_guardrails':p['special_customizer_behavior'],'studio_profile_behavior':p['studio_profile_behavior'],'explicit_choice_contracts':EXPLICIT.get(p['species'],{}),'owner_canon_ids':p['owner_canon_ids'],'unresolved_visual_conflicts':p['unresolved_visual_conflicts']} for p in profiles]
 constraints={'schema_version':'0.1.0','work_item_id':'CAPP-01','title':'Canonical Appearance Dependency and Constraint Model','status':'foundation_candidate','source_hashes':hashes,'input_contract':{'profile_id':'stable CAPP-01 profile ID','current_form':'PPIA-05 upstream projection','persistent_and_active_biology':'PPIA-05 upstream projection','permissions':'authorized viewer/editor projection','authored_choices':'CAPP-01 choice IDs and values','renderer_capability':'renderer adapter support state','actual_equipment':'PPIA-03 permission-safe projection'},'evaluation_order':['permission','upstream_biology_and_current_form','profile_topology','required_features','appearance_state_model','profile_behavior','authored_choice_dependencies','renderer_compatibility','equipment_projection'],'outcomes':['eligible','read_only','unavailable','unknown','invalid_requires_review'],'morphology_graph_contract':sem['morphology_graph_contract'],'generic_rules':generic,'profile_contracts':pc,'renderer_support_states':sem['renderer_support_states'],'non_authorities':['renderer topology/asset coverage never creates Species taxonomy','appearance never grants mechanics or equipment ownership','AI proposals cannot commit without normal write authority','CAPP-01 does not activate application runtime or STAGE-A-A2']}
 report='# CAPP-01 Foundation Report\n## Canonical 25-Species Appearance Choice Registry + Constraint Model\n\n**Work item:** CAPP-01  \n**Status:** STARTED — FOUNDATION CANDIDATE  \n**Owner:** John Brandon Turner\n\nThe corrected foundation is generated directly from the completed PPIA-06 morphology, semantic-taxonomy, Appearance Studio and owner-visual-decision authorities, with PPIA-05 retained as biological truth and PPIA-03 retained as actual equipment authority. The canonical PPIA-06 appearance set contains exactly 25 profiles: '+', '.join(p['species'] for p in profiles)+'.\n\nThe registry uses canonical Appearance Studio surfaces P06-UI-002 through P06-UI-011 rather than inventing a parallel category taxonomy. Each surface retains PPIA-06 semantic-layer references and mode. Each Species receives a stable `species.<slug>` profile ID; source-required features receive stable `REQ` IDs; source-bounded variation statements receive stable `BOUND` IDs; owner-resolved special controls receive explicit stable contracts.\n\nUnknown/source-unspecified anatomy remains unknown. Valid identity remains valid with partial/unsupported/unknown renderer coverage. Presentation wardrobe grants no mechanics; actual equipment is a read-only PPIA-03 projection; source-owned current Form/history/active biology cannot be cosmetically rewritten.\n\nThis is a CAPP-01 foundation candidate, not completion. It does not activate runtime, STAGE-A-A2, release, deployment, tester access, paid services, production credentials, or unsupported canonical promotion.\n'
 return {INDEX:dump(index),REGISTRY:dump(registry),CONSTRAINTS:dump(constraints),REPORT:report}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); a=ap.parse_args(); data=build(); bad=[]
 for p,text in data.items():
  if a.check:
   if not p.exists() or p.read_text(encoding='utf-8')!=text: bad.append(str(p.relative_to(ROOT)))
  else: p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
 if bad: print('CAPP-01 generated artifacts stale: '+', '.join(bad)); return 1
 print('CAPP-01 registry generation: PASS' if a.check else 'CAPP-01 registry generation: WROTE canonical artifacts'); return 0
if __name__=='__main__': raise SystemExit(main())
