#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/"governance/application-planning/parallel-preimplementation"
FEATURES=ROOT/"governance/application-planning/internal-alpha/feature-packets"
FILES={"manifest":BASE/"PPIA-14_SOURCE_MANIFEST_v0.1.0.json","taxonomy":BASE/"PPIA-14_MESSAGE_STATE_TAXONOMY_v0.1.0.json","boundary":BASE/"PPIA-14_AUTHORITY_AND_HIDDEN_INFORMATION_BOUNDARY_MATRIX_v0.1.0.json","delivery":BASE/"PPIA-14_ACTOR_CONTEXT_AND_DELIVERY_MATRIX_v0.1.0.json","affordances":BASE/"PPIA-14_SAFE_AFFORDANCE_CLASSES_v0.1.0.json","access":BASE/"PPIA-14_ACCESSIBILITY_MOBILE_NONVISUAL_LOCALIZATION_REQUIREMENTS_v0.1.0.json","gaps":BASE/"PPIA-14_SOURCE_GAPS_v0.1.0.json","cases":BASE/"PPIA-14_FOUNDATION_REFERENCE_CASES_v0.1.0.json"}
INVENTORY=BASE/"PPIA-14_FOUNDATION_SOURCE_AND_MESSAGE_STATE_INVENTORY_v0.1.0.md"; BACKLOG=BASE/"PPIA_PROGRAM_BACKLOG.json"; CHECKPOINT=ROOT/"governance/ai/work-state/PPIA-14-attempt-001.json"; POINTER=ROOT/"governance/ai/runtime/CURRENT_WORK_POINTER.json"; STATUS=ROOT/"governance/ai/runtime/CURRENT_IMPLEMENTATION_STATUS.json"; F020=FEATURES/"MV-IA-F020_PERMISSIONS_AND_HIDDEN_INFORMATION.md"; F021=FEATURES/"MV-IA-F021_AUTOSAVE_RECONNECT_RECOVERY_AND_BOUNDED_OFFLINE_USE.md"; F025=FEATURES/"MV-IA-F025_ONBOARDING_HELP_DIAGNOSTICS_AND_ISSUE_REPORTING.md"; F025_MATRIX=FEATURES/"MV-IA-F025_ONBOARDING_SUPPORT_MATRIX.json"; P13_MANIFEST=BASE/"PPIA-13_SOURCE_MANIFEST_v0.1.0.json"; P13_AUTHORITY=BASE/"PPIA-13_AUTHORITY_AND_BOUNDARY_MATRIX_v0.1.0.json"; P13_DELIVERY=BASE/"PPIA-13_AUDIENCE_CONTEXT_AND_DELIVERY_MATRIX_v0.1.0.json"
def fail(m): raise SystemExit("PPIA-14 FOUNDATION: FAIL — "+m)
def req(c,m):
    if not c: fail(m)
def load(p): req(p.exists(),f"missing {p.relative_to(ROOT)}"); return json.loads(p.read_text(encoding="utf-8"))
def main():
    docs={k:load(p) for k,p in FILES.items()}; backlog,checkpoint,pointer,status=map(load,(BACKLOG,CHECKPOINT,POINTER,STATUS))
    for p in (INVENTORY,F020,F021,F025,F025_MATRIX,P13_MANIFEST,P13_AUTHORITY,P13_DELIVERY): req(p.exists(),f"missing source/artifact {p.relative_to(ROOT)}")
    manifest=docs["manifest"]; req(manifest.get("work_item_id")=="PPIA-14","manifest work item changed"); req([x.get("id") for x in manifest.get("repository_sources",[])]==[f"P14-SRC-{i:03d}" for i in range(1,10)],"nine repository-source IDs changed"); req(manifest.get("source_precedence",[None])[0]=="current canonical repository governance and owner decisions","source precedence changed")
    gaps={x.get("id"):x for x in manifest.get("explicit_source_gaps",[])}; req(set(gaps)=={"P14-GAP-001","P14-GAP-002"},"Foundation gap set changed"); req(gaps["P14-GAP-001"].get("inherited_id")=="P13-GAP-001" and "F024" in gaps["P14-GAP-001"].get("subject",""),"F024 gap inheritance missing"); req("Do not invent" in gaps["P14-GAP-001"].get("foundation_rule",""),"F024 no-invention rule missing"); req("final" in gaps["P14-GAP-002"].get("subject","").lower(),"final-copy gap missing")
    f025=load(F025_MATRIX); roles=["invited-tester","player","game-master","assistant-gm","content-creator","observer","owner-admin","service-actor","ai"]; req([x.get("role") for x in f025.get("roles",[])]==roles,"canonical F025 role vocabulary changed"); req(f025.get("defaultHelpDecision")=="deny-unless-topic-is-public-or-context-authorized","F025 Help default changed"); req(f025.get("defaultDiagnosticDecision")=="exclude" and f025.get("defaultIssueDecision")=="deny","F025 diagnostic/issue defaults changed"); req(f025.get("implementationAuthorized") is False and f025.get("productionAuthorized") is False and f025.get("publicReleaseAuthorized") is False,"F025 authorization boundary changed")
    taxonomy=docs["taxonomy"]; states=taxonomy.get("message_states",[]); req([x.get("id") for x in states]==[f"P14-MS-{i:03d}" for i in range(1,19)],"18 message-state IDs changed"); keys={x.get("key") for x in states}
    for k in ("safe-unavailable","hidden-information-suppressed","stale-version","conflict-review-required","offline-bounded-local","reconnecting","status-unknown","accepted-event-projection-pending","idempotent-operation-retry-eligible","approval-pending-visible","diagnostics-redacted","source-gap-unsupported"): req(k in keys,f"message-state coverage missing {k}")
    rules=taxonomy.get("global_rules",{});
    for k in ("permission_filter_before_copy_selection","permission_filter_before_counts_search_diagnostics_support_exports_notifications_ai","status_unknown_is_not_failure","accepted_event_is_distinct_from_projection","offline_local_state_is_not_authoritative_mutation","hidden_and_missing_must_not_be_distinguished_when_existence_is_protected"): req(rules.get(k) is True,f"state rule changed: {k}")
    req(rules.get("final_prose_library_defined_by_foundation") is False and rules.get("copy_can_change_authoritative_state") is False,"Foundation authority boundary changed"); req(len(taxonomy.get("selection_pipeline",[]))==8 and "authorization" in taxonomy["selection_pipeline"][2],"permission-safe message-selection pipeline changed")
    boundary=docs["boundary"]; req([x.get("id") for x in boundary.get("authority_domains",[])]==[f"P14-AU-{i:03d}" for i in range(1,9)],"eight authority domains changed"); req([x.get("id") for x in boundary.get("hidden_information_boundaries",[])]==[f"P14-HB-{i:03d}" for i in range(1,12)],"11 hidden-information boundaries changed"); eq=boundary.get("equivalence_rule","").lower()
    for phrase in ("existence is protected","missing","exists but hidden","copy state","counts","timing"): req(phrase in eq,f"hidden/missing equivalence missing {phrase!r}")
    blocking=" ".join(boundary.get("blocking_invariants",[])).lower()
    for phrase in ("permission and entitlement projection precede copy selection","hidden objects and fields","status unknown is not failure","accepted durable event","f024","no application runtime"): req(phrase in blocking,f"blocking invariant missing {phrase!r}")
    delivery=docs["delivery"]; req([x.get("role") for x in delivery.get("role_profiles",[])]==roles,"PPIA-14 role profiles changed"); req(delivery.get("help_contexts")==f025.get("helpContexts"),"F025 help contexts changed"); req(len(delivery.get("delivery_channels",[]))==7 and len(delivery.get("context_rules",[]))==6,"delivery surface counts changed"); dtext=json.dumps(delivery,ensure_ascii=False).lower()
    for phrase in ("same protected fact","role changes","deep link","service-actor","optional ai","gm truth"): req(phrase in dtext,f"delivery rule missing {phrase!r}")
    aff=docs["affordances"]; req([x.get("id") for x in aff.get("affordance_classes",[])]==[f"P14-AF-{i:03d}" for i in range(1,14)],"13 safe-affordance IDs changed"); atext=json.dumps(aff,ensure_ascii=False).lower()
    for phrase in ("blind retry","proves a hidden resource exists","permission escalation","raw diagnostics","f024","operation_id"): req(phrase in atext,f"affordance safety missing {phrase!r}")
    access=docs["access"]; areq=access.get("accessibility_requirements",{})
    for k in ("keyboard_complete","touch_complete","screen_reader_complete","mobile_single_focus_supported","high_zoom_reflow_supported","reduced_motion_supported","noncolor_equivalent_required","safe_semantic_parity_visual_nonvisual"): req(areq.get(k) is True,f"accessibility requirement changed: {k}")
    ltext=" ".join(access.get("interpolation_rules",[])).lower()
    for phrase in ("allowlisted after authorization","hidden names","pluralization","concatenating fragments","internal status","screen-reader"): req(phrase in ltext,f"localization rule missing {phrase!r}")
    req("No final localized strings" in access.get("copy_status",""),"Foundation improperly claims final copy"); gapdoc=docs["gaps"]; req({x.get("id") for x in gapdoc.get("gaps",[])}=={"P14-GAP-001","P14-GAP-002"},"gap document changed"); req("invent" in " ".join(gapdoc.get("rules",[])).lower(),"gap no-invention rule missing")
    cases=docs["cases"]; req(cases.get("classification")=="synthetic_qa_foundation_fixture" and cases.get("noncanonical") is True,"case classification changed"); req(cases.get("case_count")==32 and len(cases.get("cases",[]))==32,"32 Foundation cases changed"); req([x.get("id") for x in cases.get("cases",[])]==[f"PPIA14-FC-{i:03d}" for i in range(1,33)],"Foundation case IDs changed"); ctext=json.dumps(cases,ensure_ascii=False).lower()
    for phrase in ("hidden-vs-missing-object-equivalence","ambiguous-mutation-status-unknown","no-blind-retry","accepted-event-projection-lag","approval-pending-hidden-to-observer","diagnostics-redacted-preview","service-actor-no-scope-bypass","ai-hidden-context-excluded","screen-reader-hidden-equivalence","localization-hidden-count-pluralization","pack-f024-source-gap","copy-never-authoritative"): req(phrase in ctext,f"reference coverage missing {phrase!r}")
    req(all(v is False for v in cases.get("policy",{}).values()),"Foundation case nonactivation policy changed"); inventory=INVENTORY.read_text(encoding="utf-8").lower()
    for phrase in ("18 stable semantic message states","status-unknown","accepted durable event","hidden-information nonleak boundary","blind retry","nine canonical","localization","p13-gap-001","32 synthetic","not ppia-14 completion"): req(phrase in inventory,f"inventory missing {phrase!r}")
    tranches={x.get("work_item_id"):x for x in backlog.get("tranches",[])}; req(tranches.get("PPIA-08",{}).get("status")=="completed_verified","PPIA-08 dependency changed"); req(tranches.get("PPIA-13",{}).get("status")=="completed_verified","PPIA-13 dependency not completed_verified"); req(tranches.get("PPIA-14",{}).get("status") in {"started","ready_for_review"},"PPIA-14 must remain unfinished during Foundation"); req(backlog.get("current_work_item_id")=="PPIA-14","PPIA-14 no longer current"); req(checkpoint.get("attempt_id")=="PPIA-14-attempt-001" and checkpoint.get("branch")=="governance/ppia-14-error-recovery-permission-microcopy","PPIA-14 checkpoint identity changed"); req(checkpoint.get("status") in {"started","ready_for_review"},"PPIA-14 Foundation cannot claim completion"); req(checkpoint.get("unresolved_failures")==[] and checkpoint.get("owner_decision_required") is False,"PPIA-14 unresolved state"); req(pointer.get("primary_attempt_id")=="PPIA-14-attempt-001","current pointer does not select PPIA-14"); req(status.get("primary",{}).get("work_item_id")=="PPIA-14","compact status does not select PPIA-14")
    bounds=backlog.get("boundaries",{})
    for k in ("application_runtime_mutation_authorized","a2_activation_authorized","release_authorized","deployment_authorized","tester_access_authorized","canonical_promotion_without_source_evidence_authorized"): req(bounds.get(k) is False,f"program boundary changed: {k}")
    print("PPIA-14 FOUNDATION: PASS"); print("states=18 hidden_boundaries=11 roles=9 affordances=13 reference_cases=32"); print("permission_filter_before_copy=true hidden_missing_equivalence=true status_unknown_not_failure=true"); print("accepted_event_projection_distinct=true f024_gap_explicit=true final_copy_not_claimed=true"); print("accessibility=mobile+keyboard+touch+screen-reader+high-zoom+reduced-motion+noncolor"); print("runtime_activation=false a2_activation=false release=false deployment=false")
if __name__=="__main__": main()
