#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'governance/application-planning/parallel-preimplementation'; IA=ROOT/'governance/application-planning/internal-alpha/feature-packets'
MAN=BASE/'PPIA-06_SOURCE_MANIFEST_v0.1.0.json'; TAX=BASE/'PPIA-06_APPEARANCE_SEMANTIC_TAXONOMY_v0.1.0.json'; AUTH=BASE/'PPIA-06_AUTHORITY_AND_BOUNDARY_MATRIX_v0.1.0.json'; REN=BASE/'PPIA-06_PIXEL_ART_RENDERER_CONTRACT_v0.1.0.json'; CASES=BASE/'PPIA-06_FOUNDATION_REFERENCE_CASES_v0.1.0.json'; INV=BASE/'PPIA-06_SOURCE_AND_DESIGN_INVENTORY.md'; CAND=BASE/'PPIA-06_FOUNDATION_CANDIDATE.md'; P05=BASE/'PPIA-05_COMPLETION_REPORT.md'; P03=BASE/'PPIA-03_COMPLETION_REPORT.md'; F004=IA/'MV-IA-F004_CHARACTER_CREATION_AND_ADVANCEMENT.md'; CP=ROOT/'governance/ai/work-state/PPIA-06-attempt-001.json'; PTR=ROOT/'governance/ai/runtime/CURRENT_WORK_POINTER.json'; STATUS=ROOT/'governance/ai/runtime/CURRENT_IMPLEMENTATION_STATUS.json'; BACKLOG=BASE/'PPIA_PROGRAM_BACKLOG.json'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def req(x,msg):
    if not x: raise AssertionError(msg)
def main():
    for p in (MAN,TAX,AUTH,REN,CASES,INV,CAND,P05,P03,F004,CP,PTR,STATUS,BACKLOG): req(p.exists(),f'missing {p.relative_to(ROOT)}')
    m,t,a,r,c,cp,ptr,status,backlog=map(load,(MAN,TAX,AUTH,REN,CASES,CP,PTR,STATUS,BACKLOG)); inv=INV.read_text(encoding='utf-8').lower(); cand=CAND.read_text(encoding='utf-8').lower(); p05=P05.read_text(encoding='utf-8').lower(); p03=P03.read_text(encoding='utf-8').lower(); f004=F004.read_text(encoding='utf-8').lower()
    req(m['work_item']==t['work_item']==a['work_item']==r['work_item']==c['work_item']=='PPIA-06','package identity')
    req([x['id'] for x in m['evidence_classes']]==['source_truth','inherited_contract','project_source_design_contract','player_authored_appearance','renderer_metadata','unresolved_gap'],'evidence classes')
    req(len(m['sources'])==6 and [x['id'] for x in m['sources']]==[f'P06-SRC-{i:03d}' for i in range(1,7)],'source manifest')
    req(m['verified_inherited_counts']=={'ppia05_direct_pdfs':29,'ppia05_direct_pages':654,'ppia05_supporting_adaptation_pdfs':6,'ppia05_supporting_adaptation_pages':233,'ppia05_mixed_ability_rows':2203,'ppia05_supporting_ability_rows':1018,'ppia05_environment_based_rows':296,'ppia03_item_csv_rows':5389},'inherited counts')
    req(all(v is False for v in m['explicit_non_assumptions'].values()),'non-assumptions')
    req(m['design_requirements']['sd105_controls']==['Body','Face','Hair','Colors','Clothing preview','Equipment preview','Accessibility preview'],'SD-105 controls'); req(m['design_requirements']['sd105_supports']==['Randomize','Save preset','Import/export appearance'],'SD-105 supports')
    req(set(m['design_requirements']['accessibility'])=={'desktop','tablet','mobile','keyboard','touch','screen-reader','high-zoom','reduced-motion','noncolor-status','no-hover-only-core-flow'},'accessibility set')
    req('29 direct species/form/biology pdfs / 654 pages' in p05 and '6 supporting environment/adaptation pdfs / 233 pages' in p05,'PPIA-05 provenance')
    for s in ('unknown/source-unspecified anatomy','current body/form state','hidden biological non-inference','ppia-06'): req(s in p05,f'PPIA-05 boundary {s}')
    req('5,389 governed rows' in p03 and 'definition versus asset instance' in p03 and 'permission-before-projection' in p03,'PPIA-03 boundary')
    for s in ('player-authored descriptive fields are stored separately from governed mechanics','mobile','keyboard','screen-reader','high-zoom','reduced-motion','noncolor-status','visual appearance'): req(s in f004,f'F004 boundary {s}')
    layers=t['identity_state_layers']; req(len(layers)==18 and [x['id'] for x in layers]==[f'P06-L{i:02d}' for i in range(1,19)],'18 semantic layers'); req([x['id'] for x in t['compatibility_dimensions']]==[f'P06-COMP-{i:02d}' for i in range(1,5)],'compatibility dimensions'); req(t['renderer_support_states']==['supported','partial','unsupported','unknown'],'support states')
    state=' '.join(t['state_rules']).lower()
    for s in ('unknown or source-unspecified anatomy','current form','valid character remains valid','permission-filtered before','equipment preview','randomization','semantic nonvisual'): req(s in state,f'state rule {s}')
    req(r['renderer_id']=='pixel-art-v1' and r['renderer_version']=='0.1.0','renderer identity'); req(r['future_renderer_boundary']['future_3d_supported_by_contract'] is True and r['future_renderer_boundary']['core_state_may_not_require_sprite_or_pixel_fields'] is True,'future 3D boundary'); req(len(r['semantic_render_bands'])==8 and [x['id'] for x in r['semantic_render_bands']]==[f'P06-RB-{i:02d}' for i in range(1,9)],'render bands'); req(r['anchors']['universal_semantic']==['root','visual_center','portrait_focus','occupancy_bounds'] and r['anchors']['pixel_coordinates_authoritative'] is False,'anchors'); req(r['topology']['profiles_are_renderer_compatibility_classes_not_species_taxonomy'] is True and r['topology']['humanoid_default_forbidden'] is True and r['topology']['nonhumanoid_supported_as_first_class'] is True,'topology'); req(r['palette']['semantic_names_required'] is True and r['palette']['noncolor_labels_required'] is True and r['palette']['color_alone_forbidden'] is True,'palette')
    rand=r['randomization']; req(set(rand['deterministic_inputs'])=={'seed','lock_set','eligible_choice_set_version','appearance_state_version'} and rand['source_owned_fields_excluded'] is True and rand['locks_must_be_respected'] is True,'randomization')
    perm=r['permission_and_export']; req(all(perm[k] is True for k in ('permission_filter_before_asset_selection','permission_filter_before_derivatives','permission_filter_before_export','permission_filter_before_ai_context')) and perm['hidden_derivative_leak'] is False,'permission filter'); failure=' '.join(r['failure_behavior']).lower(); req('never fabricates' in failure and 'no silent latest-version substitution' in failure,'failure behavior')
    req(len(a['domains'])==7 and [x['id'] for x in a['handoffs']]==[f'P06-HO-{i:03d}' for i in range(1,7)],'authority/handoffs'); guard=' '.join(a['blocking_invariants']).lower()
    for s in ('never rewrite species/form biology','unknown/source-unspecified anatomy','not species, lineage','renderer coverage does not determine character validity','equipment preview never grants','permission filtering occurs before','hidden form/marker','randomization never mutates','color is not the only semantic channel','first renderer, not the permanent','no application runtime'): req(s in guard,f'guardrail {s}')
    cases=c['cases']; req(c['case_count']==len(cases)==24 and [x['id'] for x in cases]==[f'PPIA06-FC-{i:03d}' for i in range(1,25)],'24 cases'); req(all(x['classification']=='synthetic_qa_foundation_fixture' and x['noncanonical'] is True for x in cases),'noncanonical cases'); req({x['renderer_support'] for x in cases}=={'supported','partial','unsupported','unknown'},'case support states'); text=' '.join(x['title']+' '+x['expected'] for x in cases).lower()
    for s in ('nonhumanoid','unsupported renderer','unknown anatomy','transformation','hidden biological marker','authorized equipment preview','unauthorized equipment','mobile','keyboard','screen-reader','randomization','asset-pack lock','version mismatch','required anchor','occlusion mask','portrait','token','future 3d','reduced-motion'): req(s in text,f'case coverage {s}')
    req(all(v is False for v in c['policy'].values()),'case policy')
    for s in ('six evidence','eighteen renderer-independent','four separate compatibility','`supported`, `partial`, `unsupported`, or `unknown`','pixel-art-v1','`root`, `visual_center`, `portrait_focus`, and `occupancy_bounds`','randomization is deterministic','permission filtering occurs before','future 3d renderer','twenty-four'): req(s in inv,f'inventory {s}')
    for s in ('bounded foundation candidate','six evidence','eighteen renderer-independent','four separate compatibility','twenty-four noncanonical','pixel-art-v1','valid character stays valid','future-3d','ppia-06 remains'): req(s in cand,f'candidate {s}')
    tr={x['work_item_id']:x for x in backlog['tranches']}; req(tr['PPIA-06']['status'] in {'started','in_progress','completed_verified'},'backlog state'); req(cp['work_item_id']=='PPIA-06' and cp['attempt_id']=='PPIA-06-attempt-001' and cp['branch']=='governance/ppia-06-character-appearance-creator','checkpoint identity'); req(cp['owner_decision_required'] is False and cp['unresolved_failures']==[],'checkpoint blocked')
    if backlog['current_work_item_id']=='PPIA-06':
        req(cp['status'] in {'started','in_progress','ready_for_review'},'active checkpoint'); req(ptr['primary_attempt_id']=='PPIA-06-attempt-001','pointer'); req(status['primary']['work_item_id']=='PPIA-06','status'); continuity='active_ppia06'
    else:
        order=backlog['execution_order']; req(order.index(backlog['current_work_item_id'])>order.index('PPIA-06'),'historical ordering'); req(tr['PPIA-06']['status']=='completed_verified','historical completion'); continuity='historical_after_ppia06'
    for k in ('application_runtime_mutation_authorized','a2_activation_authorized','release_authorized','deployment_authorized','tester_access_authorized','canonical_promotion_without_source_evidence_authorized'): req(backlog['boundaries'][k] is False,f'forbidden boundary {k}')
    print('PPIA-06 FOUNDATION: PASS'); print('evidence_classes=6 semantic_layers=18 compatibility_dimensions=4 renderer_support_states=4'); print('pixel_art_v1=8 render bands / stable assets / semantic anchors / occlusion / palette / deterministic composition'); print('reference_cases=24 noncanonical; nonhumanoid=true future_3d_boundary=true'); print('biology_rewrite=false equipment_mutation=false hidden_leak=false humanoid_default=false runtime_activation=false'); print('continuity_mode='+continuity)
if __name__=='__main__': main()
