import base64,io,tarfile,json,subprocess
from pathlib import Path
ARCHIVE=''.join(Path(f'.tmp/ia-d04-001/chunk{i:02d}.txt').read_text() for i in range(1,6))
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(ARCHIVE)),mode='r:gz') as tf: tf.extractall('.')
packet_path=Path('governance/application-planning/internal-alpha/feature-packets/MV-IA-F006_FIRST_PLAYABLE_ACTION_AND_GM_APPROVAL_LOOP.md')
packet=packet_path.read_text()
compatibility='''\n### Explicit compatibility anchors\n\nMV-IA-F003, MV-IA-F004, and MV-IA-F005 are explicit controlling dependencies for identity/workspace, Character, and Campaign/Scene/Session authority.\n\nAction history and My Proposals remain secondary. Offline authoritative mutation is prohibited. Realtime messages are advisory.\n'''
if '### Explicit compatibility anchors' not in packet:
    packet=packet.replace('\n## 4. ',compatibility+'\n## 4. ',1)
packet_path.write_text(packet)
reg_path=Path('governance/application-planning/internal-alpha/INTERNAL_ALPHA_FEATURE_REGISTRY.json')
reg=json.loads(reg_path.read_text())
reg['version']='0.11.0'
f006=next(x for x in reg['features'] if x['featureId']=='MV-IA-F006')
f006.update({'designStatus':'implementation-ready','packetPath':'feature-packets/MV-IA-F006_FIRST_PLAYABLE_ACTION_AND_GM_APPROVAL_LOOP.md','packetVersion':'0.1.0','companionFiles':['feature-packets/MV-IA-F006_ACTION_APPROVAL_MATRIX.json','feature-packets/MV-IA-F006_IMPLEMENTATION_TRACEABILITY.json'],'implementationBoundary':'Design complete; application implementation remains dependency-gated by the active P9-06 sequence, IA-D02-006 shared foundations, IA-D03-005 Character/Campaign preparation contracts, and concrete identity, permission, Character, Campaign, Scene, Session, persistence, Event, realtime, recovery, diagnostic, backup, restore, and provider-exit foundations. No application activation, paid service, production credential, real-user data collection, internal-alpha release, production deployment, or public release is authorized.'})
reg_path.write_text(json.dumps(reg,separators=(',',':'))+'\n')
p=Path('governance/application-planning/internal-alpha/INTERNAL_ALPHA_DESIGN_BACKLOG.md'); t=p.read_text()
t=t.replace('**Version:** 0.12.0','**Version:** 0.13.0',1)
t=t.replace('1. **IA-D04-001 — MV-IA-F006 First Playable Action and GM Approval Loop — next.**','1. **IA-D04-001 — MV-IA-F006 First Playable Action and GM Approval Loop — complete.**',1)
t=t.replace('2. IA-D04-002 — proposal and approval shared-component contract.','2. **IA-D04-002 — proposal and approval shared-component contract — next.**',1)
t=t.replace('\n## Current next design item\n','\n## IA-D04-001 completion record\n\nThe implementation-ready First Playable Action and GM Approval Loop provides:\n\n- Player Action draft, quick rule inspection, target selection, costs, requirements, roll/seed, modifiers, computed result, proposed Effects, warnings, confirmation, submit, pending state, and result;\n- GM notification and inspection with Player/controller, actor, Action, source-linked rules, targets, costs, roll, modifiers, computed result, proposed Effects, and warnings;\n- approve, deny, and explicit field-addressed modify-and-approve decisions with attributable receipts;\n- the same governed review, decision, atomic commit, and history model for GM-controlled NPC and enemy Actions;\n- one durable authoritative outcome through accepted decisions and atomic `ActionResultCommitted` Events;\n- role-filtered synchronized projections with logs and My Proposals secondary in the Player view;\n- duplicate-submit suppression, stale-version conflict preservation, status lookup after ambiguous failure, reconnect, missed-event recovery, and revocation handling;\n- bounded offline drafts with no offline authoritative submit, decision, or commit;\n- fourteen deterministic fixtures, ten implementation slices, twenty blocking acceptance criteria, and zero blocking findings;\n- zero-AI and zero-paid-service core operation.\n\nImplementation remains dependency-gated by P9-06.\n'+'\n## Current next design item\n',1)
t=t.replace('**IA-D04-001 — MV-IA-F006 First Playable Action and GM Approval Loop — next.**','**IA-D04-002 — Proposal and Approval Shared-Component Contract — next.**',1)
p.write_text(t)
p=Path('governance/application-planning/internal-alpha/README.md'); t=p.read_text()
t=t.replace('**Version:** 0.12.0','**Version:** 0.13.0',1)
t=t.replace('\n## Preparation boundary\n','\n## IA-D04-001 — First Playable Action and GM Approval Loop\n\nCompleted at design level with:\n\n- 24 numbered sections and twenty blocking acceptance criteria;\n- 24 shared-foundation and 28 Character/Campaign preparation contracts;\n- explicit Player proposal, GM review, approve/deny/modify, atomic result, projection, history, and recovery contracts;\n- GM-controlled NPC and enemy Action parity;\n- 18 states, 28 proposal fields, 20 decision-receipt fields, 28 validation classes, 28 operations, 28 Events, and 40 denied cases;\n- fourteen deterministic fixtures, ten dependency-ordered implementation slices, and zero blocking findings;\n- secondary Player logs and proposals;\n- bounded offline drafts, accessible responsive parity, privacy-safe diagnostics, and zero-AI/zero-service core operation.\n\nPrimary artifacts:\n\n- `feature-packets/MV-IA-F006_FIRST_PLAYABLE_ACTION_AND_GM_APPROVAL_LOOP.md`\n- `feature-packets/MV-IA-F006_ACTION_APPROVAL_MATRIX.json`\n- `feature-packets/MV-IA-F006_IMPLEMENTATION_TRACEABILITY.json`\n- `feature-packets/MV-IA-F006_REVIEW_RECEIPT.md`\n- `feature-packets/MV-IA-F006_READINESS_RECORD.md`\n- `feature-packets/MV-IA-F006_COMPLETION_RECORD.json`\n- `validate_first_playable_action_approval_loop.py`\n'+'\n## Preparation boundary\n',1)
t=t.replace('**IA-D04-001 — MV-IA-F006 First Playable Action and GM Approval Loop.**','**IA-D04-002 — Proposal and Approval Shared-Component Contract.**',1)
p.write_text(t)
p=Path('governance/application-planning/internal-alpha/feature-packets/README.md'); t=p.read_text()
row='| MV-IA-F006 | First Playable Action and GM Approval Loop | entry-critical | implementation-ready | not started; dependency-gated | `MV-IA-F006_FIRST_PLAYABLE_ACTION_AND_GM_APPROVAL_LOOP.md` | `MV-IA-F006_ACTION_APPROVAL_MATRIX.json`; traceability; receipt; readiness; completion |\n'
anchor='| MV-IA-F005 | Campaign, Scene, and Session Builder | entry-critical | implementation-ready | not started; dependency-gated | `MV-IA-F005_CAMPAIGN_SCENE_AND_SESSION_BUILDER.md` | `MV-IA-F005_CAMPAIGN_SCENE_SESSION_MATRIX.json`; traceability; receipt; readiness; completion |\n'
if row not in t: t=t.replace(anchor,anchor+row,1)
t=t.replace('\n## Next item\n','\n## First playable loop result\n\nMV-IA-F006 defines the complete Campaign-to-Character-to-Scene-to-Action-to-GM-decision-to-persistent-result vertical slice. It preserves attributable approve, deny, and modify-and-approve decisions, atomic accepted results, role-safe projections, NPC/enemy parity, idempotency, reconnect recovery, accessibility, and zero-service operation.\n'+'\n## Next item\n',1)
t=t.replace('**IA-D04-001 — MV-IA-F006 First Playable Action and GM Approval Loop.**','**IA-D04-002 — Proposal and Approval Shared-Component Contract.**',1)
p.write_text(t)
p=Path('governance/ai/runtime/ROADMAP_INDEX.json'); road=json.loads(p.read_text()); road['updated_at']='2026-08-06T09:45:00+00:00'
if not any(x['work_item_id']=='IA-D04-002' for x in road['entries']): road['entries'].append({'work_item_id':'IA-D04-002','track':'internal-alpha-feature-design','governing_document':'governance/application-planning/internal-alpha/INTERNAL_ALPHA_DESIGN_BACKLOG.md','roadmap_document':'governance/application-planning/internal-alpha/INTERNAL_ALPHA_DESIGN_BACKLOG.md','roadmap_section':'IA-D04-002 — Proposal and approval shared-component contract','dependencies':['IA-D04-001'],'completion_gate':'A normalized reusable proposal-and-approval component contract for live Actions and future social, content, AI, destructive, and promotion requests, with authority, projection, decision-receipt, history, accessibility, deterministic fixtures, validation, CI, and merge evidence.'})
p.write_text(json.dumps(road,separators=(',',':'))+'\n')
subprocess.run(['python','-m','py_compile','governance/application-planning/internal-alpha/validate_first_playable_action_approval_loop.py'],check=True)
subprocess.run(['python','governance/application-planning/internal-alpha/validate_first_playable_action_approval_loop.py'],check=True)
